### ISSUE TITLE
On linux the add content from file button freezes the entire app

### ISSUE THREAD

**Issue by giopera** [modrinth/code#1000]
### Describe the bug

When trying to add content to an instance from your filesystem, with the dedicated button, the program will try to open a window to select the file but it will result in crashing the entire program, making you restart it

### Steps to reproduce

1. Go to an instance in the library
2. Click the instance and go in the content menu 
3. Click in the top right corner "Add from file"
4. Enjoy

### Expected behavior

I expect to be able to select a file and add it to the content list

### System information

I run on Arch Linux x86_64 with
Kernel: 6.6.10-arch1-1 
DE: Plasma 5.27.10
WE: KWin
GPU: Intel HD Graphics
CPU: Intel i5-3570 (4) @ 3.800GHz
The app is in the AppImage format and no other modification was done other than changing the original name to another one.

### Additional context

https://github.com/modrinth/theseus/assets/89829281/ba805ead-ea18-4712-a642-0fd3c8de6923

**Comment by Felix14-v2** [comment]
Yoo, issue #1000 🙃

**Comment by Rajala1404** [comment]
Same but you get at Least a Icon on the packs

**Comment by praecipitator** [comment]
Happens for me as well

OS: Ubuntu 22.04 jammy
Kernel: x86_64 Linux 6.5.0-17-generic
DE: Xfce 4.16.1
WM: Xfwm4 4.16.1
CPU: AMD Ryzen 7 PRO 5850U with Radeon Graphics @ 16x 4.507GHz
GPU: RENOIR (renoir, LLVM 15.0.7, DRM 3.54, 6.5.0-17-generic)

Installed the app via the file `modrinth-app_0.6.3_amd64.deb`

**Comment by Rajala1404** [comment]
Is now Fixed in newest Version
