### ISSUE TITLE
Modrinth App logger breaks non-Latin symbols

### ISSUE THREAD

**Issue by w26ad** [modrinth/code#1004]
### Describe the bug

Modrinth App logger breaks non-Latin symbols (Russian in example)
Here you can see two logs made on Vanilla 1.20.4 in singleplayer
The first is from Minecraft Launcher:
[latest.log](https://github.com/modrinth/theseus/files/13980268/latest.log)

The second is from Modrinth Launcher:
[latest.log](https://github.com/modrinth/theseus/files/13980280/latest.log)

As you can see, MC Launcher logger saves non-Latin symbols (Russian/other Cyrillic in example) correctly, and Modrinth App doesn't.

So log is unusable when you want to check written messages after playing on a server.

### Steps to reproduce

1. Go to Minecraft Launcher
2. Install and open Vanilla version (like 1.20.4)
3. Change your MC language to non-Latin (like Russian/other Cyrillic language)
4. Change your keyboard language to non-Latin (like Russian/other Cyrillic language)
5. Go to Singleplayer -> World  or  Multiplayer -> Server
6. Write some messages using this language
7. Quit game
8. Go to Modrinth Launcher
9. Repeat Steps 2 - 7
10. Check your logs in launchers
11. You'll see that Modrinth App logger breaks non-Latin symbols

### Expected behavior

App logger doesn't break non-Latin symbols and saves them correctly

### System information

Windows 11 23H2 22635.3061 (Beta channel)
Theseus v0.6.3

**Comment by Felix14-v2** [comment]
Duplicates #749
