### ISSUE TITLE
Not showing fabric mods for Quilt Instance

### ISSUE THREAD

**Issue by DovydasTEDS** [modrinth/code#1028]
### Describe the bug

I have to override the loader to show fabric mods.

### Expected behavior

It shows the fabric mods + lets me download it.

### System information

Windows 11
Theseus v0.6.3

**Comment by wlad26** [comment]
> This is tedious as I have to do it for every mod I want to update and install. It used to show fabric mods too. Quilt supports fabric mods as quilt is a fork of fabric, and works using QFAPI / QSL.

This is completely wrong, not every Fabric mod is compatible with Quilt, and also in the opposite.
You can update mods by clicking Update button, doesn't matter _what modloader you're using_

**Comment by Norbiros** [comment]
Duplicate of #1188

**Comment by blryface** [comment]
I think it would be more correct to say #1188 is a duplicate of #1028

**Comment by Minenash** [comment]
True, but the other issue has a bit more detail and a response from the team
