### ISSUE TITLE
App not loading

### ISSUE THREAD

**Issue by ultimateshadsform** [modrinth/code#1046]
### Describe the bug

It stays on this screen forever and won't load the app.

![image](https://github.com/modrinth/theseus/assets/151234273/c9c852df-36e9-42ac-ba8a-efe75b352934)

![image](https://github.com/modrinth/theseus/assets/151234273/94a7f9de-3c5d-4984-ab85-05072a9993f3)

### Steps to reproduce

Open the app after not using for a while.

### Expected behavior

To open app and work

### System information

![image](https://github.com/modrinth/theseus/assets/151234273/5425ad07-2d0e-4809-9e10-4c0caf89f96c)

**Comment by shmove** [comment]
Also encountering this at the moment, not sure what would have occurred in between recent launches to cause this to happen. Attempting to close the window gives the prompt "An action is currently in progress. Are you sure you want to exit?", but choosing "Ok" will do nothing. Reinstalling fixes this issue.

**Comment by IllagerCaptain** [comment]
Getting this error too.

**Comment by Minenash** [comment]
I know it's been a while, but does this still happen?

**Comment by ultimateshadsform** [comment]
Actually no. It solved itself after update or something.  It hasn't happened again for me at least.
