### ISSUE TITLE
Modrinth won't bootup to the launcher

### ISSUE THREAD

**Issue by notJBear2003** [modrinth/code#1047]
### Describe the bug

I'm not sure how to describe it other than failing to boot up the Minecraft launcher, i posted the doc I put the log into this submission.

[](https://docs.google.com/document/d/1XuPSiL9jywLbKAMEcnG65h6rvEHt4eYJbkf8acy8Mus/edit)

### System information

latest Windows as of Christmas 2023

### Additional context

Im sorry its not much to go on

**Comment by notJBear2003** [comment]
link to the log: https://docs.google.com/document/d/1XuPSiL9jywLbKAMEcnG65h6rvEHt4eYJbkf8acy8Mus/edit

**Comment by Peperehobbit01** [comment]
Hey notJBear2003, i'am gonna look for a solution but did you try reinstalling Modrinth? If it's the case well i will ask you if you have the Microsoft web view 2 program installed, if not well install the program, he is required for Modrinth to work.

**Comment by notJBear2003** [comment]
> Hey notJBear2003, i'am gonna look for a solution but did you try reinstalling Modrinth? If it's the case well i will ask you if you have the Microsoft web view 2 program installed, if not well install the program, he is required for Modrinth to work. 

Sorry, you don't need to now. My friends helped me update my driver's and it somehow fixed it? I appreciate it

**Comment by Peperehobbit01** [comment]
Well that's great :)
