### ISSUE TITLE
`com.modrinth.theseus` file path breaks structure NBT saving in Minecraft 

### ISSUE THREAD

**Issue by TelepathicGrunt** [modrinth/code#1048]
### Describe the bug

Vanilla Minecraft has a bug that affected many Minecraft versions. This bug was originally found on 1.20.4 Minecraft but likely exists for a large number of older versions. The bug is Vanilla has a regex that will reject any file path that has a folder name starting with `com.` and the Modrinth app creates a folder called `com.modrinth.theseus`
![image](https://github.com/modrinth/theseus/assets/40846040/0cb9da0d-52ce-4a93-85b9-5325fce6d9aa)

This means trying to save structures to NBT files using the Structure Block in game will fail and break. Any mod using the vanilla method to save an area into NBT files will also be broken. Example, Bumblezone's Essence Arenas will fail to start since they cannot save the pre-arena area to NBT anymore when using Modrinth app.

### Steps to reproduce

- `\give @s structure_block`
- Place the structure block down
- Open the Structure Block's GUI by right clicking it
- Put it in Save mode with size of 1 for all dimensions. 
- Give it the name `test`. 
- Try hitting save. 
- Will say it is unable to save the structure in chat.

How to use Structure Blocks: https://www.youtube.com/watch?v=umhuRXinD3o

### Expected behavior

Saving structures to nbt files should work with vanilla Minecraft with no mods on when using Modrinth App

### System information

This is on Windows OS.

### Additional context

Quick solution probably is to rename the folder path to just `modrinth.theseus` or something idk

**Comment by TelepathicGrunt** [comment]
Jira issue report: https://bugs.mojang.com/browse/MC-268617

**Comment by TelepathicGrunt** [comment]
Regex golf done by Random here building on the Regex that Gravy, me, and others were helping to craft
https://discord.com/channels/313125603924639766/733055378371117127/1224558499225272381

**Comment by TheD0ct0r101** [comment]
Hope we dont ignore this because I can confirm. The problem persists in 1.17.1.
