### ISSUE TITLE
Forge 1.12.2 won't start up

### ISSUE THREAD

**Issue by Cod1ngGamer** [modrinth/code#1049]
### Describe the bug

Upon clicking play on an installation with forge 1.12.2, it instantly stops.

### Steps to reproduce

Make a new forge 1.12.2 instance
Launch it
It instantly exits.

### Expected behavior

What should happen is it should launch the instance. At least, that's what I assume.

### System information

Windows 11, newest version of Modrinth

### Additional context

This is the same issue that happened to cad3264 on Oct 28, 2023, so it has happened to multiple people. Also, there is no log after it crashes. All that happens is I press the play button, it turns into the stop button, and not even a quarter of a second later, it becomes the play button again.
My point is, don't just immediately close the issue please.

**Comment by Cod1ngGamer** [comment]
Update: this bug also apparently happened to Useott, and I found the link to the original commentor:
https://github.com/modrinth/theseus/issues/843#issue-1966727049

**Comment by GerG0Gadget** [comment]
I'm having the same issue, anyverion of 1.12.x is also broken

**Comment by Cod1ngGamer** [comment]
Yeah, it's really annoying because when I want to play Scape and Run or any other mod from 1.12.2 I have to use CurseForge.

**Comment by G1RL4NDA** [comment]
I had the same issue. When I installed the recomended Java 17 and Java 8 in modrinth settings, I was able to resolve this problem

**Comment by Cod1ngGamer** [comment]
OMG IT WORKS TYSM
you have no idea how long I've needed a solution to this.

**Comment by Cod1ngGamer** [comment]
![meme1](https://github.com/modrinth/theseus/assets/137913869/ee8f01c6-8ff3-42be-b84b-2bbb63541a53)
