### ISSUE TITLE
Modrinth App not launching

### ISSUE THREAD

**Issue by 4xlm** [modrinth/code#1052]
### Describe the bug

I downloaded the Modrinth App (not into the program files folder, but onto the desktop), but it doesn't launching at all. When I try to run it as Administrator, it shows up for a moment in the task manager and then it goes away.

### Steps to reproduce

Double click on the shortcut on the desktop

### Expected behavior

It should atleast show a loading screen

### System information

Windows 10, latest version
Latest Modrinth download

**Comment by Peperehobbit01** [comment]
Hey 4xlm,

   Did you have microsoft web view 2 installed, if it's not the case install that first if it is reply here.

**Comment by Minenash** [comment]
Closing as stale
