### ISSUE TITLE
Twice-refreshing any page 'breaks' Settings page

### ISSUE THREAD

**Issue by w26ad** [modrinth/code#1053]
### Describe the bug

Twice-refreshing any page 'breaks' Settings page and causes a lot of time, CPU & Network resources to load it.
It depends on PC specs but may be up to 10s, 60% & 20 Mb/s for me

### Steps to reproduce

1. Open any page (it can be even Settings page)
2. Refresh it twice using F5 / Ctrl+Shift+R / etc. 
3. Go to Settings page
4. See that it 'breaks' (uses a lot of time, CPU & Network to load)

### Expected behavior

Twice-refreshing any page doesn't 'break' Settings page

### System information

Theseus v0.6.3 -> 0.7.1

**Comment by Felix14-v2** [comment]
Can't reproduce on Windows 11 with 0.8.x
