### ISSUE TITLE
Search in an instance can't find some mods

### ISSUE THREAD

**Issue by Felix14-v2** [modrinth/code#1056]
### Describe the bug

Some mods are not displayed when searching them in an instance content.

### Steps to reproduce

- Go to https://github.com/LemonCaramel/Mica/actions/runs/7853859960
- Download the build and extract the mod to the mods folder
- Launch Minecraft and verify that the mod loads correctly
- Try to search it in the instance content
- See the issue

### System information

OS: Windows 11
App: v0.6.3

### Additional context

![image](https://github.com/modrinth/theseus/assets/75726196/62062876-09e7-48ce-9f46-d06db487918a)

**Comment by wlad26** [comment]
Can't reproduce it

**Comment by Felix14-v2** [comment]
Still can randomly reproduce with other mods.

**Comment by Felix14-v2** [comment]
Closing as I haven't observed this behavior in recent app versions.
