### ISSUE TITLE
Mod Versions

### ISSUE THREAD

**Issue by Vmstellar** [modrinth/code#1058]
### Is your suggested enhancement related to a problem? Please describe.

I cannot change the version of a mod in a modpack. it would be great if the team added a "redownload' button and gave you the option to pick mod versions that have been released to the community.

### Additional context

Mod = Project

**Comment by ItsTeraBytes** [comment]
You can actually already do that. Works for mods, resource packs, and shaders

https://github.com/modrinth/theseus/assets/88017555/933c4975-64c4-449f-a219-a054b1f06bab
