### ISSUE TITLE
Image bug

### ISSUE THREAD

**Issue by Xyndra** [modrinth/code#1070]
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/71836523/da94c043-cfaa-421f-8ba2-916cfb9d4e65)

### Steps to reproduce

1. Download the MSI
2. Open it

### Expected behavior

Everything working as normal

### System information

Windows 11

### Additional context

Debugger says the link is from Discord, which is probably a bad idea

**Comment by Norbiros** [comment]
Now we use https://launcher-files.modrinth.com/ for hosting image files. It was fixed in #1118

**Comment by Xyndra** [comment]
👍
