### ISSUE TITLE
Auto MC Version Mods Update

### ISSUE THREAD

**Issue by L0leas0** [modrinth/code#1078]
### Is your suggested enhancement related to a problem? Please describe.

Problem being, if you have 1000 mods (not really but it makes the point) there's no way to update all of them to newest Minecraft version automatically.

### Describe the solution you'd like

An extension of the mod auto update feature to allow for "mc" version updates instead of only "mod" version updates, so if you made a mod pack and want to update all of it's mods to the newest "mc" version it's not so tedious.

### Describe alternatives you've considered

Maybe this exists? I have searched for this feature but it doesn't seem to be clear. Not on the app nor the modrinth support site (i asked the bot), it's just the "mod" version update check.

**Comment by alexpado** [comment]
The update all feature already exists. I used it few weeks back, but the fact that it does not appear might be linked to #1075

**Comment by Minenash** [comment]
As stated above, update all exists, and there is an issue about it not always detecting the latest
