### ISSUE TITLE
just installed modrinth, it refuses to open

### ISSUE THREAD

**Issue by h5ninjaplays** [modrinth/code#1086]
### Describe the bug

basicly i try to open modrinth, i found out that it instantly closed again.(taskmanager)

i have not had this app before, i was going to use it to make some of my own modpacks.
i orginally had the app on the d drive, then installed on c drive to see if that worked.
also tried finding a way to fix, doesn't seem to be anything.

### Steps to reproduce

1: click on modrinth app
2: wait/ have taskmanager open when it opens and closes.

### Expected behavior

the app opens to something(i persume the login or something for modrinth)

### System information

windows version: 10
cpu: intel core i5-9400f
gpu: navida geforce gtx 1650(with updated drivers)
verson of modrinth app: the one it wants you to download from website.
i have two disk drives, a 1tb hd(second/ d drive), 250gb sd(main/ c drive)

### Additional context

basicly: i try to open app and nothing happens. it's like a problem i had with roblox but it doesn't stay open in the background.(aka roblox opens but no window)
this is a family pc but i use it the most.

**Comment by h5ninjaplays** [comment]
i found the launcher log:
2024-03-23T21:54:28.620845500+00:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
(basicly that about every time)

**Comment by h5ninjaplays** [comment]
same problem when i try to open with admim perms, i have allowed it past the firewall.

**Comment by brawaru** [comment]
You have uninstalled Microsoft Edge WebView2. Check out this article to learn how to resolve this: https://support.modrinth.com/en/articles/8797765-corrupted-microsoft-edge-webview2-installation.

**Comment by h5ninjaplays** [comment]
thats not the problem, i have that installed. i checked just in case.

**Comment by h5ninjaplays** [comment]
it could be that my pc has somewhat broke because i uninstalled microsoft edge with linux.

**Comment by h5ninjaplays** [comment]
its because i uninstalled edge. microsoft edge webview2 can't be installed/updated without edge.

**Comment by h5ninjaplays** [comment]
update: can't install microsoft edge webview2: reqires microsoftedgeupdate.exe
i don't have edge on my pc because i uninstalled it via linux.

**Comment by h5ninjaplays** [comment]
I've said previously: i had this probelm/ kind of problem with roblox. now: i'm pretty sure roblox needs microsoft edge webview2, i fixed my problem with roblox by reinstalling windows 10. is there a different fix that doesn't require reinstalling windows 10

**Comment by h5ninjaplays** [comment]
![Screenshot_5](https://github.com/modrinth/theseus/assets/102249831/6c20f890-68fa-47a8-abce-3c0f4e84b0d9)
welp, i have microsoft edge webview2. so i don't see the problem.

**Comment by brawaru** [comment]
Run the WebView2 installer as administrator 🙂

**Comment by h5ninjaplays** [comment]
i did, i can't reinstall it as i dont have microsoftedgeupdate.exe
it's not microsoft egde webview2

**Comment by h5ninjaplays** [comment]
modrinth still doesn't work, even when i just found out webview2 can be installed without edge(sorry for that.) but reinstalling it did nothing. modrinth doesn't work.

**Comment by h5ninjaplays** [comment]
> modrinth still doesn't work, even when i just found out webview2 can be installed without edge(sorry for that.) but reinstalling it did nothing. modrinth doesn't work.

i'm debating it could be because i don't have tpm enabled, i'm not sure what modrinth requires for pcs to run but i would think it's the same as minecraft. i don't think i'll be allowed to enable tpm unless otherwise or when i have to update to windows 11.

**Comment by h5ninjaplays** [comment]
opened event viewer.
i had opened modrinth 4 times, faulting process ID is different as well as report ID.

Faulting application name: Modrinth App.exe, version: 0.6.3.0, time stamp: 0x657b21f3
Faulting module name: Modrinth App.exe, version: 0.6.3.0, time stamp: 0x657b21f3
Exception code: 0xc0000409
Fault offset: 0x0000000000413826
Faulting process ID: 0x14b4
Faulting application start time: 0x01da8375ed6af87c
Faulting application path: C:\Program Files\Modrinth App\Modrinth App.exe
Faulting module path: C:\Program Files\Modrinth App\Modrinth App.exe
Report ID: f8d1cd2e-77fd-4928-b679-605fd1c472f0
Faulting package full name: 
Faulting package-relative application ID: 


this may help, i think it's breaking at the same point.

**Comment by brawaru** [comment]
Yes, this error means that you don't have Edge WebView2 installed.

Perhaps try a standalone evergreen installer from here:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by h5ninjaplays** [comment]
i did that one(standalone evergreen installer), it's not webview2 i have it installed

> modrinth still doesn't work, even when i just found out webview2 can be installed without edge(sorry for that.) but reinstalling it did nothing. modrinth doesn't work.

what i'm saying is that i have webview2 and modrinth still doesn't work, 

> ![Screenshot_5](https://private-user-images.githubusercontent.com/102249831/318135857-6c20f890-68fa-47a8-abce-3c0f4e84b0d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTc1NDQsIm5iZiI6MTcxMTg5NzI0NCwicGF0aCI6Ii8xMDIyNDk4MzEvMzE4MTM1ODU3LTZjMjBmODkwLTY4ZmEtNDdhOC1hYmNlLTNjMGY0ZTg0YjBkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxNTAwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGUwZTgwMjBhYTNlMGZmMGVhNWI1OTgwZTA4NzgzYmMwNzgyZTJjNmJhMDc2NDIzZjU2YzRlNTRhZjY4ZmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N8e0eKO8FHKpSNv1X_XPjy8toCS4G7Qvz4sheVkbyK8) welp, i have microsoft edge webview2. so i don't see the problem.

this is the image from that installer.
i ran it as admin and it closed itself afterwards(i persume it installed webview2)
i would create a dump file but i can't as modrinth closes too quickly.
and i also would think that roblox wouldn't be working or many apps wouldn't be working properly if i didn't have webview2.
IT IS NOT WEBVIEW2

**Comment by h5ninjaplays** [comment]
when i ran it as admin it did have a progress bar(i think it installed webvie2)

**Comment by brawaru** [comment]
You can use [WinDbg](https://apps.microsoft.com/detail/9pgjgd53tn86?hl=en-US&gl=US) to debug `Modrinth App.exe` (depends on where you installed it). But I'm pretty sure it *is* WebView2:
```
WebView2: Failed to find an installed WebView2 runtime or non-stable Microsoft Edge installation.
(670.2d6c): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT 
Modrinth_App+0x413826:
00007ff7`24233826 cd29            int     29h
```
(note the exception code and fault offset)

**Comment by h5ninjaplays** [comment]
> You can use [WinDbg](https://apps.microsoft.com/detail/9pgjgd53tn86?hl=en-US&gl=US) to debug `Modrinth App.exe` (depends on where you installed it). But I'm pretty sure it _is_ WebView2:
> 
> ```
> WebView2: Failed to find an installed WebView2 runtime or non-stable Microsoft Edge installation.
> (670.2d6c): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
> Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT 
> Modrinth_App+0x413826:
> 00007ff7`24233826 cd29            int     29h
> ```
> 
> (note the exception code and fault offset)

i've just noticed in your reply: 'non-stable microsoft edge installation'   this suggests that modrinth may require microsoft edge.
and i also don't know how to use the app. much.

**Comment by h5ninjaplays** [comment]
> > You can use [WinDbg](https://apps.microsoft.com/detail/9pgjgd53tn86?hl=en-US&gl=US) to debug `Modrinth App.exe` (depends on where you installed it). But I'm pretty sure it _is_ WebView2:
> > ```
> > WebView2: Failed to find an installed WebView2 runtime or non-stable Microsoft Edge installation.
> > (670.2d6c): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
> > Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT 
> > Modrinth_App+0x413826:
> > 00007ff7`24233826 cd29            int     29h
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (note the exception code and fault offset)
> 
> i've just noticed in your reply: 'non-stable microsoft edge installation' this suggests that modrinth may require microsoft edge. and i also don't know how to use the app. much.

ok, so somehow it's webview2. i've reinstalled it, i feel like a bunch of the apps i use would of broken if i didn't have webview2(as webview2 is basically needed for most apps(i looked online)) i think it's because i don't have edge. i was able to install roblox(had a similar problem, fixed by reinstalling windows, including edge) and it worked, i got rid of edge as i don't use it and it gets in the way, i think modrinth needs some kind of working edge browser just to work. the only webbrowser i have on this pc is firefox(i only use chrome at school because it's the only one i can use at school)
I have a feeling its edge. not webview2, no matter how many times i reinstall webview2 it won't work, and i am not reinstalling windows. i'm just asking for a fix that doesn't require reinstalling edge or windows.

**Comment by h5ninjaplays** [comment]
i also don't fully trust windows apps from the microsoft store. i had decided to use the microsoft store version of roblox. it played as it was the mobile version of roblox. i don't like that version. yes there are a few apps(like games) i trust work properly, as they are games(e.g. halo infinite). you could give me another debugger that works and not from microsoft as i would prefer to make sure mulitple apps that do a similar thing to give the same result. i did get what you mentioned in your latest comment(that i quote commented)

**Comment by h5ninjaplays** [comment]
> i also don't fully trust windows apps from the microsoft store. i had decided to use the microsoft store version of roblox. it played as it was the mobile version of roblox. i don't like that version. yes there are a few apps(like games) i trust work properly, as they are games(e.g. halo infinite). you could give me another debugger that works and not from microsoft as i would prefer to make sure mulitple apps that do a similar thing to give the same result. i did get what you mentioned in your latest comment(that i quote commented)

update: managed to reinstall edge modrinth now opens but stays in background prosesses. going to restart pc to see what that does.

**Comment by h5ninjaplays** [comment]
restarting pc did nothing, as well as installing edge again. is it me or do i have to reinstall windows. which i don't want to do.

**Comment by rowandevving** [comment]
are you reinstalling all of edge? because edge is completely seperate from edge webview2, which is a core system component. Edge itself doesn't even use edge webview2, which you'll have to reinstall seperately from https://developer.microsoft.com/en-gb/microsoft-edge/webview2

**Comment by h5ninjaplays** [comment]
> are you reinstalling all of edge? because edge is completely seperate from edge webview2, which is a core system component. Edge itself doesn't even use edge webview2, which you'll have to reinstall seperately from https://developer.microsoft.com/en-gb/microsoft-edge/webview2

i've already reinstalled webview2, please read the previous comments that i and the other person has made.

**Comment by h5ninjaplays** [comment]
> I have, I was just making sure that you had reinstalled it again using that tool. Are you sure the webview2 installer is actually working?

yes. i have, even ran it as admin. i'll do again for like probably the 5th time of reinstalling or trying to rinstall webview2. maybe more.

**Comment by h5ninjaplays** [comment]
> > I have, I was just making sure that you had reinstalled it again using that tool. Are you sure the webview2 installer is actually working?
> 
> yes. i have, even ran it as admin. i'll do again for like probably the 5th time of reinstalling or trying to rinstall webview2. maybe more.

![image](https://github.com/modrinth/theseus/assets/102249831/072562ab-4d18-4a34-bb97-cc9ec0a3cbe5)
i've done it. it worked. now time to uninstall edge. again.
all i needed to do was install edge and then reinstall webview2. webview2 reqires edge to reinstall/install. the main problem was edge.
