### ISSUE TITLE
Profile's "profile.json" file getting erased.

### ISSUE THREAD

**Issue by waste-of-spac** [modrinth/code#1107]
### Describe the bug

So, sometimes when I boot up modrinth all my profiles disappear. although it is possible to fix the bug manually, it is a pain in the ass. (also sorry for lack of writing, I'm not the best writer)

### Steps to reproduce

Sometimes during sudden power off

**Comment by Minenash** [comment]
This doesn't seem relevant anymore, as the app no longer uses profile.json
