### ISSUE TITLE
Opening uploaded logs on browser opens two tabs

### ISSUE THREAD

**Issue by ChromaPIE** [modrinth/code#1136]
### Describe the bug

Title.

### Steps to reproduce

1. Print some logs on the console
2. Upload the log to mclo.gs
3. Click the globe icon to open it on browser
4. It opens two browser tabs

### Expected behavior

Opens one

### System information

Windows 11
Theseus v0.7.1

**Comment by w26ad** [comment]
Duplicates https://github.com/modrinth/theseus/issues/1074
