### ISSUE TITLE
Modrinth path name "com.modrinth.theseus" causes datapacks to not function correctly (exists through many versions)

### ISSUE THREAD

**Issue by TheD0ct0r101** [modrinth/code#1138]
### Describe the bug

the path name Modrinth creates, "com.modrinth.theseus", prevents Minecraft from being able to access certain datapack functions, particularly structure related commands, completely breaking certain gameplay experiences. The part causing the problem is the "com" part.

The issue is easily resolved by simply changing the path name to "modrinth.theseus"

The problem is not exclusive to newer versions. It exists in 1.17.1 as well, so presumably the problem plagues any version of Minecraft with this datapack functionality.

### System information

Windows 10 - 64 bit

**Comment by Treetrain1** [comment]
Sorry if this is a bit off topic
It would also be nice if the path could be migrated to “Modrinth App” because “com.modrinth.theseus” doesn’t make a whole lot of sense, since (I don’t think) the app mentions that the technical name is Theseus

**Comment by Felix14-v2** [comment]
I believe only `.modrinth` would be enough. Duplicates #1048.

**Comment by brawaru** [comment]
You can drop the dot as well, given Modrinth App uses correct directory on Linux, it's never needed.

**Comment by Felix14-v2** [comment]
Dot is convenient for alphabetical sorting. I'd rather keep it.

**Comment by brawaru** [comment]
It's unconventional, and no apps[^1] do that. We really shouldn't be repeating `.minecraft`'s mistake. If you are worried about finding the directory, on Windows in Explorer you can just start typing the name and it will automatically select it for you.

[^1]: Apps ported from Unix and trashing the entire home directory do not count.

**Comment by Felix14-v2** [comment]
> If you are worried about finding the directory, on Windows in Explorer you can just start typing the name and it will automatically select it for you

Why do we need to perform additional actions? By convenience, I mean that the folder always retains its position above the others. Are there any objective cons of a dot? Why do you think `.minecraft` is a mistake?

**Comment by brawaru** [comment]
@Felix14-v2 dots in front of the config directories is a Linux thing, meant to hide the folders, and even there it's discouraged in favour of single [standardised directories](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

It's unconventional on Windows, as does nothing, and Windows has a proper Hidden attribute. I don't think it was intended to bring Minecraft on top of the list. So yes, this is a mistake, and no other things besides ported Unix software do that.

Don't forget that you are able to change the app directory so you can actually have `.modrinth`, if you want to, but I think it would be bad to use this name by default.
