### ISSUE TITLE
UI Scale

### ISSUE THREAD

**Issue by redpenguinyt** [modrinth/code#1141]
### Is your suggested enhancement related to a problem? Please describe.

With the most recent update (On Hyprland/Wayland) the launcher is now too small. 

### Describe the solution you'd like

It would be nice to be able to control the UI scale in-app using a keybind and setting, equivalent to `Ctrl +` and `Ctrl -` in browsers and web apps such as Electron-based applications

**Comment by Norbiros** [comment]
Duplicate of #214
