### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by ItsPasi** [modrinth/code#1143]
### Describe the bug

Rescaling the Modrinth window creates some weird issues with the UI scaling ever since version v0.7.1

### Steps to reproduce

1. Install version v0.7.1
2. Rescale the window
3. Press on certain profiles and see the UI scale change, making interaction impossible

### Expected behavior

No UI scale changes should happen

### System information

Windows 11

### Additional context

https://github.com/modrinth/theseus/assets/12584747/3817c19e-d4a8-4360-9b63-4143b53b997b

**Comment by w26ad** [comment]
Should be marked as https://github.com/modrinth/theseus/issues/1161 duplicate 'cause of bad description
