### ISSUE TITLE
Light theme visibility issues

### ISSUE THREAD

**Issue by ItsPasi** [modrinth/code#1144]
### Describe the bug

Certain elements within the light theme have edges that shouldn't be visible as well as scroll bars that are not visible at all

### System information

Windows 11

### Additional context

![grafik](https://github.com/modrinth/theseus/assets/12584747/e1ec835a-2b29-42f9-bba5-4e4a94b37ff1)

**Comment by Felix14-v2** [comment]
Please, provide system information.

**Comment by ItsPasi** [comment]
> Please, provide system information.

Updated original post
