### ISSUE TITLE
Login into modrinth account through Theseus v0.71 fails

### ISSUE THREAD

**Issue by JosueGalRe** [modrinth/code#1147]
### Describe the bug

When trying to login into the launcher using my Modrinth account, I try to copy and paste my password (I use a password manager). When I try to click the login button it fails and shows the error message attached below.

### Steps to reproduce

1. Go to configuration
2. Click on Sign In
3. Enter your username
4. Copy and paste your password
5. Click on login

### Expected behavior

I should be prompt to the next screen, and be asked for the 2FA value

### System information

Processor	AMD Ryzen 9 5950X 16-Core Processor               3.40 GHz
Installed RAM	64.0 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Pro
Version	23H2
OS build	22631.3447
Experience	Windows Feature Experience Pack 1000.22688.1000.0
Card name	NVIDIA GeForce RTX 3080
Manufacturer	NVIDIA
App version	Theseus v0.71

### Additional context

![image](https://github.com/modrinth/theseus/assets/6238927/cb13c8ab-3339-482e-b3ce-4e78167b8674)

**Comment by AlyxPink** [comment]
I'm not sure if it's related, but just before getting this message, I was having an error message about the captcha and same thing: the captcha form never showed up.

**Comment by JosueGalRe** [comment]
> I'm not sure if it's related, but just before getting this message, I was having an error message about the captcha and same thing: the captcha form never showed up.

I had the same issue too

**Comment by brawaru** [comment]
Modrinth is using Turnstile CAPTCHA by Cloudflare that automatically completes in background. We've recently added completion indication to the site, but we are yet to add it to Modrinth App. But if you see this message, all you need to do is to wait a bit (usually 10 seconds is plenty for it to complete). IIRC the CAPTCHA resets every time you press the button, so spamming it doesn't help.

**Comment by TankHero0815** [comment]
Any news here? Having this issue since downloading the app in April. Every time I get this error:

![image](https://github.com/modrinth/theseus/assets/24494005/02e93f12-d1a4-49be-86ce-6510cc756ba5)

**Comment by brawaru** [comment]
No news, you'd see the updates on the issue if there were any. Just skip singing in to your Modrinth account altogether, it doesn't do anything anyway. It seems that the CAPTCHA is completely borked, and it doesn't have anything to do with the waiting.

**Comment by Cragsand** [comment]
Also having this issue. Logging in via a browser works fine but through the launcher is broken. I'm pretty sure a captcha is supposed to be shown but the UI for it doesn't show for some reason.

![image](https://github.com/modrinth/theseus/assets/49168045/eaafc5a5-1f9f-4101-9108-f98f037abbdd)
"An error occurred
invalid args `challenge` for command `login_pass`: command login_pass missing required key challenge"

**Comment by rockdemon696** [comment]
The "invalid args 'challenge' for command 'login_pass' : command login_pass missing required key challenge seem related to 2FA. I got the other message about "captcha" first, checked I could log in to the site, while there noticed I could enable 2FA, enabled 2FA, then went back to the app and got the message about "login_pass".

**Comment by John-Development** [comment]
> Modrinth is using Turnstile CAPTCHA by Cloudflare that automatically completes in background. We've recently added completion indication to the site, but we are yet to add it to Modrinth App. But if you see this message, all you need to do is to wait a bit (usually 10 seconds is plenty for it to complete)


Currently in the web cloudflare is requesting (at least for me during all the day) user input when I try to login. This tab opens every time I try to login into modrinth, so I am guessing that waiting in the app for cloudflare to finish the verification is not a valid option anymore.

![imagen](https://github.com/modrinth/theseus/assets/38006800/117677b1-bcdb-4858-85cf-b59b15a159c8)

**Comment by brawaru** [comment]
That's because you use a privacy pass extension, which shows its own CAPTCHA with interactive challenge in order to get a pass. Without it, it should complete without interactive challenge.

**Comment by John-Development** [comment]
Oh I didnt know that, thank you! Now it logins without asking for interacion in the web :D

**Comment by pedroffabrin** [comment]
Man, I'm having the same problem, on the same version, what's happening?

**Comment by Franco227** [comment]
Same captcha issue on Fedora 40 (using the AppImage file)

**Comment by markaabo** [comment]
This is still an issue in august

**Comment by John-Development** [comment]
Can confirm
