### ISSUE TITLE
Error goes out of the window

### ISSUE THREAD

**Issue by w26ad** [modrinth/code#1182]
### Describe the bug

![Modrinth_App_KlNOhXtPgS](https://github.com/modrinth/theseus/assets/65756919/734ae250-035d-4e04-94cc-80e0d562ecd9)
![Modrinth_App_gI4wjN8lY5](https://github.com/modrinth/theseus/assets/65756919/fffb1312-a6fe-4751-ae08-d0291e2e1a37)

### Steps to reproduce

1. Go to instance settings
2. Set Java path to any long and nonexistent
3. Try to launch instance
4. See that error goes out of the window

### System information

Theseus 0.7.1

**Comment by brawaru** [comment]
Mandatory comment.

![“CSS is awesome” in a square but word “awesome” overflows and goes beyond border](https://github.com/modrinth/theseus/assets/10401817/03f90bb8-bfcb-496c-a6db-487929db4cd4)

**Comment by Norbiros** [comment]
Fixed in #1325
