### ISSUE TITLE
Error installing / changing to Forge 1.18.2 v40.2.15 and above.

### ISSUE THREAD

**Issue by MrPogostyc** [modrinth/code#1191]
### Describe the bug

The Modrinth App doesn't allow you to download versions of the Forge Mod loader for 1.18.2 past 40.2.14 which is a problem because certain mods DOWNLOADABLE on the Modrinth site, require later forge versions to function. [For example, the mod "waterframes" requires version 40.2.15, and the latest you can get from modrinth, is 40.2.14]
![image](https://github.com/modrinth/theseus/assets/59030023/c9f381c8-7212-4b48-91ee-a1102fd98ce5)

![image](https://github.com/modrinth/theseus/assets/59030023/d3b9c33e-eca2-4b78-9bde-670e10c7ad90)

Tried reinstalling the app with a fresh install, and continued to happen. I even made a modpack from Curse with the latest version, and tried importing, and it gave me an error about not being able to downloaded the before mentioned Forge 1.18.2 version.

I mainly need Forge 1.18.2 | 40.2.15 for this pack to even function, and I'd really rather not port the pack to Curse or any other launcher.

### Steps to reproduce

1. Get to a point where you need to select an Pack instance version. In my case, you can navigate to the pack options and select "Change Instance Version"
2. Select "Forge" as the Loader, "1.18.2" as the Game Version
3. You can clearly see the latest version is only 40.2.14, where there are clearly later versions on Forge's website for the game version.

### Expected behavior

I imagine that this list of Forge versions is supposed to be synced to some sort of available repo that has all the latest forge versions. Whether that is hosted by Modrinth, or directly via Forge's API, it hasn't been updating beyond version 40.2.14. 

### System information

Win11, 64x based OS, 16GB DDR4, Core I7-8700k, Geforce RTX 3050, 3TB of SSD storage (Two Drives of which are SATA and the other NVME m.2).

### Additional context

A feature might be nice where you could inject a Forge installer so if this happens again, all i need to do is get my own Forge 1.18.2 40.2.14 Installer, and inject it manually through the Modrinth App.

**Comment by blryface** [comment]
im pretty sure this is the same issue on modern forge, where Forge installer changed and Modrinth has to figure out how to make it work.
I could be wrong but if it's that, yeah it's a known issue

**Comment by Aijokey** [comment]
Same problem
