### ISSUE TITLE
Update Check Button

### ISSUE THREAD

**Issue by Fyoncle** [modrinth/code#1211]
### Is your suggested enhancement related to a problem? Please describe.

Yes, i'm always annoyed to refresh the app's page about 120 times just to make the update button appear, that is just HELL.

And i have motion sickness, and when i keep refreshing, it also creates flashing lights that annoys me, there SHOULD be a easy way like prism has, an update checker that is MANUAL.

### Describe the solution you'd like

A button called "Check For Updates" would be great, that will check every single mod's releases and then make the "Update All" button appear afterwards if theres any.

### Describe alternatives you've considered

Prism obviously.

**Comment by blryface** [comment]
That's.. a suggestion for sure
I've never had issues with the app not displaying that the mod pack has an update, that seems like an issue in your end, instead of just refreshing the page you should just try reopening the app
A manual update checker could be useful, but I think the app does it pretty frequently if not only on launch

**Comment by Fyoncle** [comment]
> That's.. a suggestion for sure I've never had issues with the app not displaying that the mod pack has an update, that seems like an issue in your end, instead of just refreshing the page you should just try reopening the app A manual update checker could be useful, but I think the app does it pretty frequently if not only on launch

Nope, i tried over 5 relaunches but even tho update was 37 minutes before, it didn't appear, the update checking thingy is kinda broken, and manual checker would be useful as hell.

**Comment by Fyoncle** [comment]
So as you can see here, i got no updates rn right?
![No updates](https://github.com/modrinth/theseus/assets/63975256/fa079d17-29b0-45f0-8938-3c0b4597d58c)

But i relaunched the app, then refreshed the page about 4 times with 2 seconds of stop in each one.

And heres the updates now appeared even tho they are hours before.
![Updates](https://github.com/modrinth/theseus/assets/63975256/4d3a56a0-12e5-45fc-95c9-fe831e542fdf)

**Comment by Jamalam360** [comment]
Obligatory https://shouldiblamecaching.com/

**Comment by Fyoncle** [comment]
> Obligatory https://shouldiblamecaching.com/

Hm?

**Comment by Jamalam360** [comment]
The issue is probably caused by API caching, meaning even though an update has been released it won't show up in the API for a bit.

That's purely speculation though

**Comment by Fyoncle** [comment]
> The issue is probably caused by API caching, meaning even though an update has been released it won't show up in the API for a bit.
> 
> That's purely speculation though

Yea so, we need that update check button :v

**Comment by Jamalam360** [comment]
Adding a button to the launcher won't help with caching on the API server. Whether it's triggered by a button or done automatically on app launch, the update check is doing the same thing

**Comment by Fyoncle** [comment]
> Adding a button to the launcher won't help with caching on the API server. Whether it's triggered by a button or done automatically on app launch, the update check is doing the same thing

😭

**Comment by blryface** [comment]
this thread is very

**Comment by Thinkseal** [comment]
> Obligatory https://shouldiblamecaching.com/

I feel like a solution to this because I have had a similar problem is just to have a button to clear your cache which then could fix the problem

**Comment by Fyoncle** [comment]
Added in Modrinth App v0.8.1
