### ISSUE TITLE
Using forge doesn't work

### ISSUE THREAD

**Issue by LoganDaBest3916** [modrinth/code#1225]
### Describe the bug

When I try to create a new instance and choose forge, then after putting in the mods I want, I press "play" and after taking a little to load, it just stops. I've tried playing with no mods and different versions, but nothing changes, vanilla, fabric, and quilt all work it's only forge. 

### Steps to reproduce

It's just what you would normally do to make an instance with forge

### Expected behavior

I expected it to work, idk. All I know is that this is extremely annoying.

### System information

I'm using windows on what I'm pretty sure is the latest version.

### Additional context

The only time I was able to play with it being forge is when my friend sent me a download link but now even that doesn't work.

**Comment by Thinkseal** [comment]
do you have java installed?

**Comment by LoganDaBest3916** [comment]
well, i probably would have to because its only forge that does this, the other ones open up java Minecraft and it's on my account
