### ISSUE TITLE
libwebkit2gtk-4.0-37 dependency not available for download from apt (Ubuntu 24.04 LTS)

### ISSUE THREAD

**Issue by yesseruser** [modrinth/code#1230]
### Describe the bug

The `modrinth-app` package (downloaded from website) requires an old dependency `libwebkit2gtk-4.0-37`. This dependency cannot be downloaded from `apt`.

### Steps to reproduce

1. Make sure you are on Ubuntu version 24.04
2. Download modrinth-app deb file, install it using `dpgk` and run `modrinth-app` in terminal, or dowload the appimage and try running it via terminal (to see console output)
3. Observe the app not starting

### Expected behavior

The app should start without those problems, or should use a newer version of this package that's available on `apt`.

### System information

Ubuntu 24.04 LTS,
Modrinth app 0.7.1

### Additional context

Logs when installing deb package with dpkg:
```
Selecting previously unselected package modrinth-app.
(Reading database ... 213713 files and directories currently installed.)
Preparing to unpack modrinth-app_0.7.1_amd64.deb ...
Unpacking modrinth-app (0.7.1) ...
dpkg: dependency problems prevent configuration of modrinth-app:
 modrinth-app depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.

dpkg: error processing package modrinth-app (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 modrinth-app
```

**Comment by timkicker** [comment]
Same issue here on 24.04 LTS

**Comment by blryface** [comment]
Is it not being on apt a modrinth problem?

**Comment by blryface** [comment]
Wait no I see the last part now, I think this is a Tauri issue but idk

**Comment by jkirkpatrick** [comment]
same here: Ubutnu 24.04

4.1 incompatible with 4.0 ... yikes

`libwebkit2gtk-4.1-dev` can be installed but `modrinth-app_0.7.1_amd64.deb` depends on version 4.0. And unfortunately libwebkit2gtk-4.0-x isn't available as a package.

I know 4.0 can be downloaded from Jammy by adjusting apt sources but I'm going to wait for a newer release of Modrinth instead

**Comment by Norbiros** [comment]
> Wait no I see the last part now, I think this is a Tauri issue but idk

Yes, it's upstream problem: https://github.com/tauri-apps/tauri/issues/9662
