### ISSUE TITLE
modrinth crashes after opening logs (mint)

### ISSUE THREAD

**Issue by russendle** [modrinth/code#1237]
### Describe the bug

I use Linux mint, I open the logs to find an issue I'm having, frozen

### Steps to reproduce

1. open Modrinth
2. open Minecraft (or not doesn't matter)
3. open logs from Library > Instance
4. frozen, only way to close Modrinth is to kill it

### Expected behavior

Expected to see the Logs, IDK what to write here tbh

### System information

Linux Mint 21.3 Virginia

### Additional context

I found others with the same issue here. but they are closed

**Comment by drgndk** [comment]
Can reproduce on Arch Linux 6.9.2
