### ISSUE TITLE
Freezes when clicking Add content or Browse buttons

### ISSUE THREAD

**Issue by Icey67** [modrinth/code#1244]
### Describe the bug

It doesn't let me open the list of mods to download either in "Add content" or "Browse"

### Steps to reproduce

Method 1: From Instances
1. Go to Library
2. Select an instance
3. Press "Add Content"

Method 2: Accessible anywhere
1. On the sidebar, click "Browse"

### Expected behavior

I should be able to click either "Add content" or "Browse" and show me the list of mods or shaders ;-;

### System information

OS: Garuda Linux x86_64
Kernel: Linux 6.9.7-zen1-1-zen
DE: KDE Plasma 6.1.1
WM: Kwin (Wayland)
CPU: AMD Phenom II X6 1090T
GPU: AMD Radeon RX 580 2048SP
RAM: 16GB

### Additional context

https://github.com/modrinth/theseus/assets/60461186/51964792-fd24-4b55-8314-f11ab06a5963

**Comment by Icey67** [comment]
Does no one else experience this issue?

**Comment by blryface** [comment]
maybe they do, but I'm pretty sure this is a duplicate issue

**Comment by Icey67** [comment]
> maybe they do, but I'm pretty sure this is a duplicate issue

Yeah, maybe it is #520

**Comment by Icey67** [comment]
apparently there's nothing being worked on about this issue so i'll just close this post here
