### ISSUE TITLE
Add content type tabs to Desktop App

### ISSUE THREAD

**Issue by WestPrime** [modrinth/code#1308]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [X] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

App

### Is your suggested feature related to a problem? Please describe.

All the content is mixed in a modpack's menu. 
![изображение](https://github.com/user-attachments/assets/08d791f9-8d5f-486b-856b-04d48aea7a06)
It would be much better if it had such tabs above the list:
Mods | Resourcepacks | Shaders

### Describe the solution you'd like

To have browser-like content tabs in the modpack page

**Comment by Geometrically** [comment]
It exists already! Next to the search bar, use the dropdown which says "All"
