### ISSUE TITLE
My skin isn't set in-game

### ISSUE THREAD

**Issue by EJSnow** [modrinth/code#1314]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.7.1

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

So I have this skin set on Minecraft, right? (Screenshot from minecraft.net)
![Screenshot (458)](https://github.com/user-attachments/assets/1b85deaa-7f95-465f-a95e-a9c3f81dffc4)

On the Modrinth app, it shows my skin's face correctly in the top-left, but if I launch the game and load into a world, it doesn't set my skin in Minecraft properly. It falls back to another one.
![Screenshot (459)](https://github.com/user-attachments/assets/699b1798-5264-4970-af44-1d0ead6ecf8a)
What's this?

### Steps to reproduce

1. Go to https://www.minecraft.net/en-us/msaprofile/mygames/editskin and see what your current skin is
2. Open the Modrinth app, and launch a Minecraft instance
3. Once Minecraft loads, go into a world, and once that loads, go to third-person (F5)

### Expected behavior

The skin is supposed to be set correctly in Minecraft

### Additional context

The instance I saw this on was originally Minecraft 1.20.4 when I created it, and then my skin seemed to work OK. A couple weeks ago I upgraded it to Minecraft 1.20.6, and I think that's when I noticed the issue pop up. The instance has some optimization mods on it because otherwise Minecraft runs awfully on my laptop. Also just checked on another instance, which is vanilla 1.21, and the issue still shows up. So this is definitely with the Modrinth app as a whole, not just a bugged Minecraft instance.

**Comment by rotgruengelb** [comment]
I don't think this is a modrinth bug.

**Comment by Win761** [comment]
Thanks, that fixed it! Probably just a caching issue on my end. I'm closing this now

**Comment by cookieanimators-maker** [comment]
i cant get onto the change skin page :(
