### ISSUE TITLE
Using JVM arguments causes "OpenGL 3.3 Test" window to appear and then promptly closes without crash.

### ISSUE THREAD

**Issue by Mentalgen** [modrinth/code#1315]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.7.2 (AUR r1394.90f7442-1)

### What operating systems are you seeing the problem on?

Linux

### Describe the bug

When starting Minecraft through the launcher with these JVM arguments 
```
-XX:-UseG1GC -XX:+UseShenandoahGC -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+UseNUMA -XX:ShenandoahGCHeuristics=static -XX:ShenandoahMinFreeThreshold=25 -XX:ShenandoahGarbageThreshold=30
``` 
with 8GiB's of RAM allocated, Minecraft fails to start correctly. Instead, a black or transparent tiny screen with a title of "OpenGL 3.3 Test" pops up for a while, and then closes without almost any info whatsoever. The only bit of info I can find is starting Modrinth App from the terminal and seeing the final line ``*** stack smashing detected ***: terminated`` that gets printed when the blank window appears. This does **not** happen on PolyMC, which lead me to suspect some sort of launcher bug is going on.

### Steps to reproduce

1. Download -> [The Boys 1.0.1.zip](https://github.com/user-attachments/files/16355091/The.Boys.1.0.1.zip) and install the profile within the launcher.

2. Set the settings I've described above, ie. the JVM arguments, Azul's Java 21, and using 8GiB of RAM.

3. Start the game

### Expected behavior

Minecraft booting correctly into the main menu.

### Additional context

It seems to only happen in combination with a lot of mods but so far I've been unsuccessful in figuring out either what mod it is, or if it's truly the fault of Modrinth App. Seems like using Azul's JVM or OpenJDK's doesn't matter, as long as you're using some combination of non-default arguments.

This is being ran on an Arch Linux system that installed the -git package. I've tried others with the same results.

**Comment by Norbiros** [comment]
I can't reproduce this bug; the game launches successfully for me. Can you test it with other launchers to confirm if it's a Modrinth app issue?

**Comment by Mentalgen** [comment]
I've tested with PolyMC (fork of MultiMC) and this does not happen.

What other ways of debugging is there? Its hard to say what exactly is going on when the log or terminal is giving me nothing...

**Comment by Norbiros** [comment]
Hmm, very interesting... I couldn't find exactly why it crashes, and why it happens only in Modrinth app, but I'm pretty sure it is a problem with incorrect java flags. For example, you are enabling 2 different GCs: `-XX:-UseG1GC` `-XX:+UseShenandoahGC`. 

I found those flags working for Shenandoah `-XX:+UseShenandoahGC  -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat`

**Comment by Mentalgen** [comment]
I thought "-XX:-UseG1GC" with the minus disable the GC, and "-XX:+UseShenandoahGC" with the plus enables this GC, regardless I tried using this without the G1 argument and it still happens, in fact, just using "-XX:+UseShenandoahGC" causes this bad behavior.

I've tried your flags too with the same exact result. Only thing that fixes this is by just removing the "-XX:+UseShenandoahGC" flag entirely, but that means I can only use G1 since that's the default flag GC that's enabled.

I've also tried ZGC and that fails to start as well. Only other GC, Parallel works however??

**Comment by Norbiros** [comment]
Did the other launcher use the same JVM as the Modrinth app?

**Comment by Mentalgen** [comment]
![image](https://github.com/user-attachments/assets/56e8f4a4-953b-4912-9478-eb85464c4025)
This is what I have it set to, and it starts just fine.

**Comment by Norbiros** [comment]
> so technical explanation: LWJGL packages GLFW, but the version packaged in, 3.3.1 iirc, has a bug with that build of GLFW that causes a stack smashing error. The issue does NOT exist in 3.2.2, and from what I hear it also does not happen in the absolute newest GLFW (built from source) libraries either. The current solution is to either use an older version of LWJGL (3.2.2 where the issue doesnt happen), or to force LWJGL to use your source-built GLFW libraries (a bit more tedious since LWJGL is picky apparently). The newest builds of LWJGL may also be fine, I havent tested those though.

Minecraft `1.20.1` uses LWJGL `3.3.1` which crashes. To fix this problem we have to update our library patches in[daedalus]( https://github.com/modrinth/daedalus) to use `3.3.3`.

**Comment by Mentalgen** [comment]
I can confirm that by using ``-Dorg.lwjgl.glfw.libname=/usr/lib/libglfw.so`` when installing GLFW from the AUR, this fixes the problem, entirely. For now this seems like a good workaround.
