### ISSUE TITLE
Images can't be/aren't displayed on the same line.

### ISSUE THREAD

**Issue by rotgruengelb** [modrinth/code#1317]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

When images are embedded on the same line, they are not displayed on the same line but are instead displayed on new lines.

**Example:**
```md
![alt1](... link1 ...) ![alt2](... link2 ...)
``` 

![grafik](https://github.com/user-attachments/assets/95a6c6dc-163c-4461-8e2a-3e2ee4525ee8)

 

### Steps to reproduce

Example Modrinth Project Sites: 
- https://modrinth.com/mod/your_time
- https://modrinth.com/mod/snow-under-trees-remastered
- https://modrinth.com/mod/autoreglib

### Expected behavior

Something more like this:
![grafik](https://github.com/user-attachments/assets/4149e4e0-169b-47a3-ad39-addff9ea6867)

### Additional context

Expected behavior applied before an update broke it.

**Comment by ramnaresh8** [comment]
Would love to work on it, if the expected behavior should be in the same line. Can it be assigned to me
