### ISSUE TITLE
Starting the Modrinth app from a URL scheme starts the app but does not bring up the modpack installation screen

### ISSUE THREAD

**Issue by hax4dazy** [modrinth/code#1335]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.7.1

### What operating systems are you seeing the problem on?

Windows, MacOS

### Describe the bug

While the modrinth app is not running, starting the app with a URL scheme to install a modpack does start the app but does not retain the parameter. 

### Steps to reproduce

1. Close the Modrinth app
2. Open your browser and go to `modrinth://modpack/sop`
3. Observe as the Modrinth app starts but the window to install the modpack does not come up

### Expected behavior

The prompt to install the modpack to come up

**Comment by Mineandcraft201** [comment]
Same but Windows doesn't recognize the modrinth:// sheme and Modrinth doesn't open at all.

**Comment by hax4dazy** [comment]
Turns out that this got silently fixed in somewhere along me making this issue and the latest update. Would be nice if we got some kind of feedback on the issues, even if its just an acknowledgement saying that they can replicate the issue.
