### ISSUE TITLE
`display: flex` on project's h1 causes causes bad wrapping

### ISSUE THREAD

**Issue by T3sT3ro** [modrinth/code#1363]
### Describe the bug

[Take a look at this page](https://modrinth.com/mod/modmanager)

Now at this screenshot:
![image](https://github.com/modrinth/knossos/assets/5300963/d898d2b5-652c-498c-bff9-af080e423342)

I know we can all agree that the text shouldn't wrap like that :D

### Steps to reproduce

1. Go to [Take a look at this page](https://modrinth.com/mod/modmanager), look at the h1 of the project description
2. Voila xD

### Expected behavior

Normally wrapping text xd

### Additional context

h1's display is `display: flex`. Using regular `display: block` looks OK.

**Comment by Erb3** [comment]
This was fixed in #2231, please close
