### ISSUE TITLE
Vercel deployment failing

### ISSUE THREAD

**Issue by scriptcoded** [modrinth/code#1391]
### Describe the bug

The Vercel deployment on master is failing since cb1c8be87023008e7577a51da69d52de738d1367 with status "Account is blocked.".

### Steps to reproduce

1. Go to commit cb1c8be87023008e7577a51da69d52de738d1367.
2. Open the checks for the commit indicated by a ❌.
3. Note that the Vercel check failed with "Vercel — Account is blocked."

### Expected behavior

Vercel deployments should pass or be removed from the checks.

### Additional context

![image](https://github.com/modrinth/knossos/assets/6452991/4722bb73-82ca-407d-96ef-a80ddff00883)

**Comment by Minenash** [comment]
This has been "solved" by no longer using Vercel
