### ISSUE TITLE
Advertisement takes a lot of space

### ISSUE THREAD

**Issue by w26ad** [modrinth/code#1413]
### Is your suggested enhancement related to a problem? Please describe.

Ad block takes a lot of space on small width devices (smartphones)
Because text block doesn't use all the adv space:
![msedge_JDQFeqUJL6](https://github.com/modrinth/knossos/assets/65756919/5ea3e6a2-8d43-4ae2-b765-d9dd192fc5d6)

### Describe the solution you'd like

Advertisement takes less screen space:
![bisecthost_fixed](https://github.com/modrinth/knossos/assets/65756919/53b770a8-f74c-4836-91b4-f7b878b38cba)

**Comment by Minenash** [comment]
I guess in a way this is solved, as there's currently not any ads on mobile. Though even if/when they get added back, it probably would be worth doing a new issue as the ad (and general design language) is now different
