### ISSUE TITLE
'About' user's window UI should be the same as org's

### ISSUE THREAD

**Issue by w26ad** [modrinth/code#1414]
### Is your suggested enhancement related to a problem? Please describe.

Here you can see that User's page has lot of free/irrationally used space, Report button seems bad and 'About' UI depends on browser's tab scale:
![msedge_ubfOlLHI35](https://github.com/modrinth/knossos/assets/65756919/1c896162-72fb-4297-87bd-d64109362882)
![EFMBHFyRje](https://github.com/modrinth/knossos/assets/65756919/6a26514e-89b9-4b89-a3c6-5e11f6f8906b)

And Organization's page UI is good in all aspects and scales:
![msedge_t8V8ZD8YjC](https://github.com/modrinth/knossos/assets/65756919/135e8a1a-a77f-41ac-baf4-9abc86073369)

### Describe the solution you'd like

'About' user's window UI should be the same as org's:
![msedge_ygspF2aYuR](https://github.com/modrinth/knossos/assets/65756919/c6231f7c-5176-4011-b52b-f2dd1ed0e492)

**Comment by Minenash** [comment]
They now match
