### ISSUE TITLE
Disappearing withdrawals screen

### ISSUE THREAD

**Issue by Jab125** [modrinth/code#1462]
### Describe the bug

https://github.com/modrinth/knossos/assets/67534807/62b06f1f-73a5-45b8-8ce4-e7e0b0e64961

The entire interface disappears

### Steps to reproduce

Go to the withdrawals screen

Press backspace when the country selector's text box is empty

### Expected behavior

Nothing to happen

**Comment by Minenash** [comment]
This seems to have been fixed
