### ISSUE TITLE
Some GIFs are broken

### ISSUE THREAD

**Issue by Felix14-v2** [modrinth/code#1478]
### Describe the bug

When browsing mods on some pages you can see the broken GIFs. For example, [here](https://modrinth.com/mod/shimmer!#:~:text=for%20quick%20configuration-,Auxiliary%20Screen,-Eyedropper) – GIF just doesn't loaded. When opening it in separate tab you can see this error message:
```
{"status":"error","code":404,"message":"Input image exceeds pixel limit. Width x height should be less than 71000000"}
```
But the source page on GitHub displays GIF without any issues.

### Steps to reproduce

1. Open [this page](https://modrinth.com/mod/shimmer!)
3. Find the broken GIF manually or paste [this link](https://modrinth.com/mod/shimmer!#:~:text=for%20quick%20configuration-,Auxiliary%20Screen) into the URL field and go through it (this is due to another Modrinth bug that breaks these links by loading a page twice)
4. See the error
5. Open the gif in separate tab

### Images
![image](https://github.com/modrinth/knossos/assets/75726196/a6cfb2a8-b9e6-4ac9-bd1c-2706b9d46566)

### Additional
![image](https://github.com/modrinth/knossos/assets/75726196/673d9689-5b54-4c8f-bcb6-5089d183599b)

**Comment by Minenash** [comment]
This doesn't happen in the link provided anymore, but that could be due to updating the image. That being said, (unless the error is wrong), the image would have had to be over 8426x8426 (or equivalent amount of pixels, like the error says). That is def too large to be using in a description

**Comment by Felix14-v2** [comment]
> This doesn't happen in the link provided anymore, but that could be due to updating the image

Still happening for me
![image](https://github.com/user-attachments/assets/e882558d-7ab8-4caf-953c-f729f2b58985)

**Comment by Felix14-v2** [comment]
Still an issue in 2026
