### ISSUE TITLE
Markdown in profile bio

### ISSUE THREAD

**Issue by 0PandaDEV** [modrinth/code#1480]
### Is your suggested enhancement related to a problem? Please describe.

My problem is that in the profile bio links are not clickable and also I cannot create a new line to separate content in my bio

### Describe the solution you'd like

The solution would be that the bio supports markdown the same as with the normal project descriptions.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by Minenash** [comment]
The team has confirmed that they don't plan to support markdown in bio. However they do have plans to add a links section

**Comment by KnightMiner** [comment]
Any update on the plans for a links section? There has been more than 1 recent incident where it would be very helpful that a project posted to modrinth has an easy way to claim a related social account.

Recent case involved an author who had their modrinth mods copied to curseforge without their permission, their post on the subject came from a social account that could not be linked on their modrinth profile without just adding it to the bio (which has a max length!!!)
