### ISSUE TITLE
Image with float styling breaks layout in description.

### ISSUE THREAD

**Issue by qtchaos** [modrinth/code#1497]
### Describe the bug

Though the warning in the editor suggests that styling isn't supported, it seems to still support float on images (might be intended), using either left or right float will make the element break the layout when its the last element in the description.

![image](https://github.com/modrinth/knossos/assets/72168435/c2f8dcb8-7a35-488c-bf3f-37f615f1bbfc)

### Steps to reproduce

1. Edit a project description
2. Add an image element to the bottom with the `float:left;` or `float:right;` styling.
3. ![image](https://github.com/modrinth/knossos/assets/72168435/059be7df-c3c4-43c5-bfb5-56e2bcfbb78f)

### Expected behavior

![image](https://github.com/modrinth/knossos/assets/72168435/338202ae-10f5-4f73-b620-def6aa4786fe)

### Additional context

Having anything below the image in the description will fix the layout.

**Comment by Minenash** [comment]
Fixed by #2231
