### ISSUE TITLE
Pressing back button in browser causes an error

### ISSUE THREAD

**Issue by shane-smith** [modrinth/code#1500]
### Describe the bug

Rather than loading the datapack version details, as expected, an error occurs when pressing back to return to the version page.

![image](https://github.com/modrinth/knossos/assets/943942/2915d058-fa34-4ad4-b770-436fe05a7b8f)

### Steps to reproduce

1. Go to a version page, e.g. https://modrinth.com/datapack/wood_cutter/version/gcxecSnl
2. Click the Sign in button
3. Press back in the web browser
4. The URL is correct (and refreshing does load the page correctly), but without refreshing an error message is displayed.

### Expected behavior

Display the version details page for the datapack.

**Comment by Minenash** [comment]
This issue doesn't seem to happen anymore, but there is now a different bug ^
