### ISSUE TITLE
Move "Project Members" Section above release section

### ISSUE THREAD

**Issue by QarthO** [modrinth/code#1502]
### Is your suggested enhancement related to a problem? Please describe.

Currently on a project, the authors are towards the bottom. Modrinth is THE platform where it puts its developers and community first. However on projects finding the author of it can be sometimes hard.

For example, Fabric API, (currently the most downloaded mod) https://modrinth.com/mod/fabric-api
You are having to scroll A LOT just to see the authors.
*Side note: the app doesn't even show projects authors on mods or modpacks.. but looks like someone already made an issue about this

### Describe the solution you'd like

Swap the "Featured versions" and "Project members" sections

### Describe alternatives you've considered

An alternative (and maybe better option) would be to move it all the up into the top sidebar. Maybe between the stats and the report/follow buttons

**Comment by Minenash** [comment]
The featured version section is no more
