### ISSUE TITLE
CAPTCHA error

### ISSUE THREAD

**Issue by ubionexd** [modrinth/code#1514]
### Describe the bug

When logging in using a password manager on mobile, a CAPTCHA error is shown. Resubmitting the form wouldn't work either.
![Screenshot_2023-09-03-09-08-45-032_com brave browser-edit](https://github.com/modrinth/knossos/assets/70473378/c1b952fc-08ef-43c3-95aa-d4fb88deb75c)

### Steps to reproduce

1. Go to the Modrinth login page
2. Autofill your creditentials using a password manager with Gboard
3. Click login
4. The error is shown

### Expected behavior

It lets you log in.

### Additional context

Android 13
Brave Browser
Bitwarden
Gboard

**Comment by SunSparc** [comment]
This seems to have returned. Happening in version `0.8.9 (20241016.025915)` on macOS.

**Comment by tuflinxpost-netizen** [comment]
https://roomstyler.com/users/bcclubtk
