### ISSUE TITLE
Auth session doesn't persist between www. and nil subdomains

### ISSUE THREAD

**Issue by falseresync** [modrinth/code#1520]
### Describe the bug

If you login on the www. subdomain, you remain signed out on the nil subdomain (ie no subdomain) and vice versa

### Steps to reproduce

1. Login on the website
2. Go to the www. subdomain and see that you're logged out

### Expected behavior

Auth should persist between www. and no subdomain

**Comment by Minenash** [comment]
This no longer seems to be an issue
