### ISSUE TITLE
Inconsistent page navigation from 5th page of search results

### ISSUE THREAD

**Issue by obnyis** [modrinth/code#1572]
### Is your suggested enhancement related to a problem? Please describe.

When navigating through multiple pages of search results, to go from the 5th page to the 6th you need to use the next page arrow.

This should switch to the `1 - 4 5 6 - X` form to allow continued navigation by selection of a page number.

### Describe the solution you'd like

Line 96 in ui/Pagination.vue should be updated to `else if (this.page > 4) {`

https://github.com/modrinth/knossos/blob/05d994889d8567240148047e5a0384c1819615ee/components/ui/Pagination.vue#L96C36-L96C36

### Additional context

When on the 5th page:
![image](https://github.com/modrinth/knossos/assets/601189/eeef0249-7434-4586-847c-aed77fdffaf4)

After navigating to the 6th page:
![image](https://github.com/modrinth/knossos/assets/601189/119045c5-5502-48bd-ba3b-ce629a795085)

When on the 4th from last page:
![image](https://github.com/modrinth/knossos/assets/601189/b6fe9d7f-d897-47bc-92f3-ba46d3acfbdd)

After navigating to the 5th from last page:
![image](https://github.com/modrinth/knossos/assets/601189/519921bd-7a08-4617-80fe-7600975132fc)

**Comment by Minenash** [comment]
Fixed at some point
