### ISSUE TITLE
Search: Advert position swaps place when filter menu is opened

### ISSUE THREAD

**Issue by MMK21Hub** [modrinth/code#1584]
### Describe the bug

On mobile viewports, filters can be used by pressing the **Filters...** button to "open" the card containing the filters.

When this card is closed, the advert (tagged with the class GBBNWLJVGRHFLYVGSZKSSKNTHFYXHMBD) appears below the search controls. However, when the filters are open, the advert is shown above the search controls.

This upsets the expected order of UI elements, and also stops the focus order matching the visual order of elements.

### Steps to reproduce

1. Use a viewport less than 1024px wide
2. Go to https://modrinth.com/mods
    → :heavy_check_mark: The advert is above the search controls
4. Click the **Filters...** button
    → :x: The advert is now below the search controls

### Expected behavior

The advert would stay above the search controls (the top-to-bottom order would be filters card, advert, search controls, pagination, search results)

#### Expected behaviour (when filters aren't shown)

![Cropped screenshot showing the advert placed above the search filters](https://github.com/modrinth/knossos/assets/50421330/512d4329-3cf7-4daa-83be-40829854972d)

#### Unexpected behaviour (when filters are shown)

![Cropped screenshot showing the advert placed below the search filters. The "Filters..." button is highlighted green to indicate its active state](https://github.com/modrinth/knossos/assets/50421330/7f22eebd-bab3-4b22-b14c-8efd8131b0ac)

**Comment by Minenash** [comment]
This seems to be fixed with the new ad system
