### ISSUE TITLE
Window size + location not preserved

### ISSUE THREAD

**Issue by srnyx** [modrinth/code#161]
### Describe the bug

When resizing/moving the app and relaunching, it resets it's window size and location

### Steps to reproduce

1. Resize app and/or move it
2. Close app
3. Launch app and it won't be in the same location/size

### Expected behavior

Same size/location as previous launches

**Comment by thesuzerain** [comment]
Seems to be replaced by this new issue, right, unless I'm misunderstanding?
https://github.com/modrinth/theseus/issues/374
Closing this one in favour of that
