### ISSUE TITLE
Search returns right results in the wrong order

### ISSUE THREAD

**Issue by Prospector** [modrinth/code#162]
### Describe the bug

Website:
![image](https://github.com/modrinth/theseus/assets/6166773/4335ba7a-e726-414a-a3e1-c1cb0319b40c)

App:
![image](https://github.com/modrinth/theseus/assets/6166773/8d2be5de-2c26-49a3-b85d-92c48f52c2d0)

**Comment by thesuzerain** [comment]
Seems to be working now, not sure when this was fixed

![image](https://github.com/modrinth/theseus/assets/10837000/0944dc50-0cbf-4aa2-a477-1eabfc183ff2)
