### ISSUE TITLE
500 Internal error page when navigating to /moderation

### ISSUE THREAD

**Issue by MagnusHJensen** [modrinth/code#1662]
### Describe the bug

When navigating to `/moderation` and not being a Moderator or Admin, results in a 500 Internal server Error page.
This happens due to the axios call to retrieve projects that need moderation, returns 401 which is not handled properly in the promise.all call.

### Steps to reproduce

1. Go to https://modrinth.com/moderation
2. See 500 page

### Expected behavior

To see either a 401 Forbidden page, or just a 404 since that route "should not" exist for regular users.

### Additional context

Prod:
![image](https://user-images.githubusercontent.com/32039051/219874151-e1003064-6f75-42d5-a849-61fb6de448af.png)

Local dev:
![image](https://user-images.githubusercontent.com/32039051/219874177-ebfd9bd5-f716-4454-8335-7e95383b63e9.png)

**Comment by AroonGit** [comment]
Now, why can I access this site? Thats the question. (I'm not a mod)

<p>

![image of the site](https://i.imgur.com/P5hqy0R.png)

**Comment by Erb3** [comment]
Why not? You don't have access to anything there anyways. Those stats are public in the API. The source is open source, there is no reason to hide the page.
