### ISSUE TITLE
Lower-case letters snipped at top

### ISSUE THREAD

**Issue by srnyx** [modrinth/code#172]
### Describe the bug

The lower-case letters here appear to be snipped by a few pixels at their tops

### Steps to reproduce

Look at text with lower-case letters (preferably on the homepage as I'm not sure if this occurs elsewhere)

### Expected behavior

The entire letter should be present

### Additional context

![image](https://github.com/modrinth/theseus/assets/25808801/1de8ead2-6037-48c4-b28d-f69136c7fa94)

**Comment by Geometrically** [comment]
don't think this is a bug worth fixing- also likely a rendering issue we have no control over
