### ISSUE TITLE
New release metadata screen is ugly

### ISSUE THREAD

**Issue by CodeF53** [modrinth/code#1745]
### Is your suggested enhancement related to a problem? Please describe.

The new release metadata screen looks garbage. 

Not sure where this is currently active, but I saw it first at the [datapack test](https://knossos-git-datapack-support-modrinth.vercel.app/mod/test-project/version/wdawdwda+mod).

### Describe the solution you'd like

Written by @Obscure2020:
The title bar that also contains the download, back, and report buttons should be shrunk leftwards so it is the same width as the Changelog and Files bubbles. The Metadata bubble should then be moved upwards so that its top aligns with the title bar bubble. Lastly, the title bar bubble, the Changelog bubble, and the Files bubble should be combined into one singular bubble. Make them sections of one bubble, not three separate bubbles.
![image](https://user-images.githubusercontent.com/37855219/209768787-b7744823-aa3d-48e4-be84-e861b258afa5.png)

### Additional context

How it is:
![image](https://user-images.githubusercontent.com/37855219/209768957-1f440885-c32b-4f28-b0cb-815206fbd651.png)

What I think would look better (hacky fast image edit, excuse bad margins):
![image](https://user-images.githubusercontent.com/37855219/209769212-bf3b06f3-1bc1-4e9d-9cd6-c983a6e4caa3.png)

**Comment by Obscure2020** [comment]
Was a little bit confused why I got an email about this issue report after such a long wait. Must have been because the issue was moved out of knossos. Thanks for continuing to consider our critiques seriously.

**Comment by Minenash** [comment]
The metadata is now to the side of title card
