### ISSUE TITLE
Metadata-Minecraft versions doesn't show as versions choosed

### ISSUE THREAD

**Issue by HowardZHY** [modrinth/code#1787]
### Environment

Website

### Describe the bug

https://modrinth.com/mod/legacyinputpatch/version/1.0.7
I choosed 1.4,1.4.1,1.4.2 y 1.4.3, but only showed 1.4-1.4.1

### Steps To Reproduce

<img width="665" alt="image" src="https://user-images.githubusercontent.com/96782166/198584755-9294d547-e725-4c95-b5de-337a8416a13d.png">
<img width="385" alt="image" src="https://user-images.githubusercontent.com/96782166/198584859-a371da05-9ed5-4a83-9d12-180d91c4bef0.png">

### Expected behavior

Minecraft versions should be same as versions choosed

**Comment by Minenash** [comment]
At least in this case, it's fixed. It now shows as 1.4-1.4.1, 1.4.2-1.4.4 (it's separated due to 1.4/1.4.1 being technically snapshots)
