### ISSUE TITLE
information buttons at home screen overlaps with cards in some window sizes

### ISSUE THREAD

**Issue by Caliel666** [modrinth/code#185]
### Describe the bug

i believe this happens due to them changing size depending on text length 

https://github.com/modrinth/theseus/assets/38433434/efb1523f-dc46-4c33-932c-fc9f5458071c

### Steps to reproduce

1. go to home page
2. have projects with images
3. resize window

### Expected behavior

properly fixed sized cards so that this doesn't happen

**Comment by Geometrically** [comment]
fixed
