### ISSUE TITLE
List supported loaders (logos only?) underneath title on project pages

### ISSUE THREAD

**Issue by Herobrine2143** [modrinth/code#1857]
### Is your feature request related to a problem? Please describe.

Is not a problem but rather a simple and more easily to identify the modloaders/clients that the mod supports. Currently the clients/modloaders are alongside the filters that we use, and that's not very intuitive.

### Describe the solution you'd like

Therefore, I noticed that there was some space right below the icon of the mod. The icon of the modloader/client can be put there for simplicity and compact space. That way, it would be easier to identify that that spot is going to be for the modloader/clients that it can support.

### Describe alternatives you've considered

It could be a toggle-able option if it may. Right beside the author's name there's also space and it can be either used for the compact version of it, if anyone prefers it that way, or use the icon and name of the modloader/client. If it doesn't fit it can slide from left to right and vice-versa.

**Comment by Minenash** [comment]
Supported loaders are now in the new compatibility card
