### ISSUE TITLE
The UI elements looks really close / squished in

### ISSUE THREAD

**Issue by stantios** [modrinth/code#186]
### Describe the bug

Basically the title, this bug makes most if not all UI elements close / squished together which looks really weird. I think it is best if I show you screenshots to describe this issue.

*sorry if that was not best explanation, I was not sure how else to explain it.*

Screenshots:

![image](https://github.com/modrinth/theseus/assets/98621617/425bfb4a-5bdc-49c0-a08b-9d6595cc9f06)
![image](https://github.com/modrinth/theseus/assets/98621617/23881a0a-2f98-474a-95e8-69a8c481466f)
![image](https://github.com/modrinth/theseus/assets/98621617/3f163e09-5b57-4232-815a-61c1f6fd8cb2)
![image](https://github.com/modrinth/theseus/assets/98621617/fb23d71b-2eee-496f-b3fd-450d901b96df)
![image](https://github.com/modrinth/theseus/assets/98621617/1aa1b328-e01e-4c5b-9439-36838471e7c8)
![image](https://github.com/modrinth/theseus/assets/98621617/6f078d78-028f-4abd-93e4-98c9c07db018)

### Steps to reproduce

1. Launch the Modrinth Launcher
2. Go through each of tabs in the launcher or click on an instance or mod
3. You have found the bug!

### Expected behavior

The expected behaviour is for the UI elements to be more far apart rather than cose together, I am thinking that this could be an incompatibility with my macOS version as I am on version 10.13.6.

### Additional context

Model: iMac (27-inch, Mid 2010)
macOS: High Sierra
macOS Version: 10.13.6

**Comment by RealmKebab** [comment]
can you resize it

**Comment by Imzxhir** [comment]
Yeah, I have tried resizing the launcher / application but it did not work.

**Comment by Geometrically** [comment]
oops, didn't mean to close

**Comment by Imzxhir** [comment]
I tried to reinstall the launcher and restart it after reinstalling, but that did not work and the issue still remains.

I am thinking that it could be an issue with me being on a really old macOS version (10.13.6) or it could be an issue with my display resolution which is 2560 x 1440 and my display is 27-inch.

**Comment by triphora** [comment]
I don't even think that's macOS, it might as well be OS X with how old that is.

It is probably the old macOS version. Maybe we should have a warning when trying to run theseus on very old versions? This isn't like a breaking issue or anything, it can still be used, but it is far from welcome, even though it's more than likely a wontfix.

**Comment by Geometrically** [comment]
yeah- this is a won'tfix
