### ISSUE TITLE
Clicking on "Open Folder" doesn't open instance Folder

### ISSUE THREAD

**Issue by Arbee4ever** [modrinth/code#188]
### Describe the bug

The context menu button "Open folder" doesn't open the folder, just like the "Folder" button in the instance Overview. I think this is a Fedora/Linux specific issue.

### Steps to reproduce

1. Go to "Home"
2. rightclick on instance
3. "Open Folder" does nothing
4. leftclick on instance
5. "Folder" does nothing

### Expected behavior

Open the instance's Folder

**Comment by Norbiros** [comment]
I can reproduce this bug on Linux (Gentoo).

**Comment by KingZeus96** [comment]
I can also reproduce this error on Garuda via the AUR package.

the first click elicits no response. the second click produces the error. running via terminal modrinth-app --verbose did not produce any useful information.

I have also noticed that inside minecraft itself clicking open the mods folder has no result. same with open resource pack folder. Could be related?
![Screenshot_20220394](https://github.com/modrinth/theseus/assets/82551443/9ff652d6-1723-48fd-b913-d7e178dcb9c6)
