### ISSUE TITLE
Show supported versions on mod page

### ISSUE THREAD

**Issue by Awakened-Redstone** [modrinth/code#1897]
### Is your feature request related to a problem? Please describe.

I think the project could show the supported versions
One issue I find when using another mod platform is that while it shows the supported version, it shows of the last release, and with this, I need to check the files to see if the mod supports a newer version, or an older one, it would be great to be able to just quickly go on the page an see if the mod supports the game version you want, checking the "Featured versions" isn't really practical, specially when the mod supports many versions, and so the list becomes quite large

### Describe the solution you'd like

The supported could be shown under update and create date, being on a location where it is easy to spot

I made an example image of how it could look like
![image](https://user-images.githubusercontent.com/40528665/166165282-3b9647fc-e8d2-45dd-a108-ec89e93e0b88.png)

### Describe alternatives you've considered

An alternative I have considered is show supported versions above the description
![image](https://user-images.githubusercontent.com/40528665/166165529-b9298951-f6f5-421d-9080-ccb93e622778.png)

**Comment by Minenash** [comment]
Added in design refresh
