### ISSUE TITLE
Change dark mode behaviour for theme toggles

### ISSUE THREAD

**Issue by triphora** [modrinth/code#1952]
Currently, the theme toggler in the navbar switches only between light and dark mode. There's also a hidden OLED mode accessible only from being logged in.

Instead of changing between all three (light, dark, OLED) options in the settings and only between the two (light, dark) in the navbar, the setting should let you choose whether your dark mode should be standard dark or OLED dark, so that the navbar toggler switches between light mode and the chosen dark mode.

Carried over from the redesign bug trello

**Comment by Minenash** [comment]
I think this can be marked as solved, as if you select dark mod or oled in the settings, and then click the toggle, it'll toggle back to what ever was selected

**Comment by Prospector** [comment]
yup this was fixed quite a while back
