### ISSUE TITLE
Intense use of CPU by the launcher while an instance is running

### ISSUE THREAD

**Issue by ghost** [modrinth/code#197]
### Describe the bug

While an instance is running, Modrinth App manages to use up to 30% CPU, which is sometimes more than the game itself.

### Steps to reproduce

- Launch an instance

- See issue

### Expected behavior

No CPU usage spike

### Additional context

Running on Windows 10

**Comment by christopher317** [comment]
adding on, it appears to be maxing out one cpu core. closing the launcher while the game is running does not close the game but completely fixes the issue.
