### ISSUE TITLE
List GPL 3 in license dropdown

### ISSUE THREAD

**Issue by sekelsta** [modrinth/code#1992]
**Is your feature request related to a problem? Please describe.**
It is a very common license and having to find the link is annoying.

**Describe the solution you'd like**
Add GPL 3 to the license dropdown menu for creating a mod, like the other licenses.

**Describe alternatives you've considered**
This is a big QOL improvement over having to pick "Custom license".

**Comment by Geometrically** [comment]
GPL3 is not a valid license for Minecraft mods, as GPL requires you to only depend on GPL compatible libraries, with a linking exception for system libraries. Minecraft does not fall under this.

**Comment by triphora** [comment]
> When is a program and its plug-ins considered a single combined program?

> It depends on how the main program invokes its plug-ins. If the main program uses fork and exec to invoke plug-ins, and they establish intimate communication by sharing complex data structures, or shipping complex data structures back and forth, that can make them one single combined program. A main program that uses simple fork and exec to invoke plug-ins and does not establish intimate communication between them results in the plug-ins being a separate program.

> If the main program dynamically links plug-ins, and they make function calls to each other and share data structures, we believe they form a single combined program, which must be treated as an extension of both the main program and the plug-ins. If the main program dynamically links plug-ins, but the communication between them is limited to invoking the ‘main’ function of the plug-in with some options and waiting for it to return, that is a borderline case.

Source: https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins

Using the GPL or AGPL opens yourself up to DMCA from Mojang. Just look what happened to CraftBukkit.
