### ISSUE TITLE
So 1.20 crashes when pressing play

### ISSUE THREAD

**Issue by CosminCiur** [modrinth/code#200]
### Describe the bug

I chose a 1.20 fabric profile to be created. No extra mods and I get a crash

### Steps to reproduce

1. Create a fabric 1.20 profile (1.20.1 seems to work)
2. Press play
3. Cry in agony

### Expected behavior

It doesn't crash at boot

### Additional context

[stdout.log](https://github.com/modrinth/theseus/files/11818483/stdout.log)

**Comment by Casmin7** [comment]
This also works with any 1.20 modpack (fabric/quilt) (forge is not affected)

**Comment by V3AI-Seven** [comment]
I have also had this issue. It seems to be complaining about file extensions or something.

**Comment by thesuzerain** [comment]
Hey! Thanks for your report and patience. Can you please try this again on the latest update 0.3.0 and let me know if it still occurs? 
We also have a profile repair function that is worth trying, which may fix it depending on what is causing it. Thanks!

**Comment by Geometrically** [comment]
try recreating the instance. it should work

**Comment by Geometrically** [comment]
closing as cannot repro
