### ISSUE TITLE
Loading logo stay to the bottom while scrolling.

### ISSUE THREAD

**Issue by wret8385** [modrinth/code#203]
### Describe the bug

When the search is loading it shows the loading logo but if you scroll down it will stay to the bottom of the screen.

### Steps to reproduce

1. Go to the bar on the left then click 'Browse'
2. Click resourcepacks then search whatever you like 
3. You will see the loading logo now scroll down 
4. As you can see the loading logo stays to the bottom while scrolling down.

**Comment by TonoCatMeow** [comment]
I'm getting the bug to.
![image](https://github.com/modrinth/theseus/assets/86448220/f50951fc-cf1c-47e7-9227-daa4a8b081cc)

**Comment by thesuzerain** [comment]
Should be fixed with 0.3.0
