### ISSUE TITLE
Choosing a "Other" loader version prompts you to select a game version first if you haven't already, even if you've chosen Fabric/Quilt as the loader

### ISSUE THREAD

**Issue by ghost** [modrinth/code#206]
### Describe the bug

Fabric and Quilt are mostly version-agnostic, but I'm required to select a game version before being able to select their loader version.

### Steps to reproduce

1. Go to the create new instance dialog
2. Click "Show advanced"
3. Select Fabric or Quilt as the loader
4. Select "Other" loader version

### Expected behavior

I can select the loader version before I've selected game version in case I'm planning to run Fabric/Quilt.

**Comment by triphora** [comment]
I don't think it would be a good idea to have special casing here for these loaders. Certain loader versions do not work on certain game versions, but this information just isn't in Daedalus. If we wanted to add this information in the future, or if Fabric/Quilt adds it to their metas, this would end up becoming the case again.
