### ISSUE TITLE
After editing the icon of a pack, Modrinth breaks

### ISSUE THREAD

**Issue by GeraldTM** [modrinth/code#212]
### Describe the bug

As in title, modrinth breaks after you edit the icon of a pack. home and library become blank pages, and explore takes forever to load, if it loads at all.

### Steps to reproduce

1. install a modpack
2. edit the icon
3. done

### Expected behavior

icon to update and the launcher continue to work

### Additional context

note: removing the icon works as expected, selecting an icon is what is broken

**Comment by Av1zi** [comment]
this only breaks the app if you change the icon from the app, if you will try to open modrinth files and change it from there it will work as intended

**Comment by Geometrically** [comment]
fixed
