### ISSUE TITLE
"Error Fetching URL" when attempting to install a mod through the app

### ISSUE THREAD

**Issue by purgat0rian** [modrinth/code#2133]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Theseus v0.71

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

When attempting to install any mod through the Modrinth app/launcher, I'm able to click on the install button and choose which instance to install it to, however after clicking the install button it pauses for a moment, fails to install the mod, and shows me the following error:

`An error occurred`
`Error fetching URL: error sending request for url
(https://cdn.modrinth.com/data/... (link cuts off due to dialogue box size)`

I managed to get an example screenshot, using an installation attempt of Xaero's Minimap.

![image](https://github.com/user-attachments/assets/f53c0a13-fce9-4458-971e-96b47a4d23e8)

### Steps to reproduce

1. Open Modrinth App
2. Have a mod-compatible instance ready, or create a fresh instance with the mod
3. Find any mod within the library
4. Click on install

### Expected behavior

Mod installs to an instance as normal

### Additional context

It may be an issue with the network settings on my computer, although I already gave the modrinth app (.exe file) full access to the firewall.

I also have my modrinth .exe within a user-specific folder, while the AppData is in its usual .com.modrinth.theseus folder outside any users.

The user I have the modrinth program file in is also not an administrator.

**Comment by Thinkseal** [comment]
<img width="766" alt="Screenshot 2024-08-04 at 11 06 36 PM" src="https://github.com/user-attachments/assets/87b1a1ca-e796-4b6d-a2e0-a4679bf3b066">
