### ISSUE TITLE
Can't Zoom / Scale GUI

### ISSUE THREAD

**Issue by Minenash** [modrinth/code#214]
### Describe the bug

Despite the GUI being a web view, you can't zoom in/out

### Steps to reproduce

1. Be in app
2. Try to zoom out with Ctrl+Scroll Wheel or +/-
3. See it does nothing

### Expected behavior

To zoom

### Additional context

You can kinda use Custom CSS to fix it, but there's no custom css yet

**Comment by y1935837** [comment]
any updates?

**Comment by Norbiros** [comment]
This feature was added to Tauri in `2.0.0-beta.15`, but we are still using v1...

**Comment by ToBinio** [comment]
Tauri 2.0 is still in beta. there is no stable 2.0 release yet
so theseus is still 1.x since it's the latest stable release...
