### ISSUE TITLE
[Gamebreaking] Unable to Save or Load Structure NBT files

### ISSUE THREAD

**Issue by 123ghaksd** [modrinth/code#2145]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### Describe the bug

For some reason when only using the Modrinth app, structure blocks refuse to work properly. The generated file that should exist within a Minecraft save folder refuses to generate. When attempting to recreating the file structure manually, still the files cannot be read by the structure block.

This has been an ongoing issue for almost a year and affects what I would assume is all players using the modrinth app.

### Steps to reproduce

To reproduce simple try to save or load a structure via structure block in-game.

**Comment by Norbiros** [comment]
https://github.com/modrinth/code/issues/682, this problem will be fixed in `0.8.0`. You can download latest beta from Modrinth Labs' Discord server.
