### ISSUE TITLE
Modrinth AppImage is missing a dependency, thus missing the point of AppImage

### ISSUE THREAD

**Issue by grepwood** [modrinth/code#2151]
I've downloaded `https://launcher-files.modrinth.com/versions/0.7.1/linux/modrinth-app_0.7.1_amd64.AppImage` and it has this much to say:
```
modrinth-app: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory
```

Look, I don't want to make a fuss, but this is 2nd time this decade that I run into the same issue with random AppImage files. What's the point of making these pseudo static linked monoliths if they're going to suffer the same pitfalls of running random dynamically linked executables on Linux? Would it literally kill the package maintainer to statically link everything like people used to 20 years ago, without these elaborate Rube Goldberg solutions that take a mile long hike around the problem and solution and hope to arrive at the same conclusion?

**Comment by Norbiros** [comment]
This issue was fixed few weeks ago https://github.com/AppImageCommunity/pkg2appimage/pull/555. We updated Tauri's linuxdeploy releases, so newly bundled appimages work correctly. To see this fix in the Modrinth app just wait for new version/beta.

**Comment by grepwood** [comment]
Thank you sir
