### ISSUE TITLE
Fix UI size in flatpak version

### ISSUE THREAD

**Issue by warmap1** [modrinth/code#2160]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Theseus v0.7.1

### Describe the bug

UI size is TOO small, I barely can see anything, I have poor eyesight already, I dont want to ruin it more.
![image](https://github.com/user-attachments/assets/cdd8abf7-5c90-446a-9227-85dec6fb08da)

### Steps to reproduce

1. ```flatpak install flathub com.modrinth.ModrinthApp```
2. Launch Modrinth App (like ```flatpak run com.modrinth.ModrinthApp```)
3. Done

### Expected behavior

Not needed, probably

### System details

Distro: ArchLinux
DE: KDE Plasma 6
WM: KWin
Screen Resolution: standard sized 1920x1080p (HD) laptop screen

I wonder how it will look on 4K monitor

**Comment by Kalstro** [comment]
*example of interface size it should be
![image](https://github.com/user-attachments/assets/eb7494eb-d757-4fee-8cb4-96fc99655994)

**Comment by ToBinio** [comment]
since the flatpak isn't supported officially you will have a better change of getting this resolved when you report it here - https://github.com/flathub/com.modrinth.ModrinthApp
Thanks!

**Comment by Kalstro** [comment]
Okay, thanks!
