### ISSUE TITLE
Mod installation fails with error

### ISSUE THREAD

**Issue by Infgator** [modrinth/code#2163]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.7.1

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

I can't install most mods for 1.21.1 Neoforge private modpack. Launcher throws `Invalid input: Unable to infer project type for input file` error. Some mods are installing just fine. For example, Applied Energistics 2 installs, but Railcraft Reborn doesn't.

**Comment by Thinkseal** [comment]
You need to use the bata for the next update to fix this currently
