### ISSUE TITLE
NeoForge 1.21 skipped

### ISSUE THREAD

**Issue by DRD2k8** [modrinth/code#2168]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [ ] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.7.1

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

So, since 1.21 came out, NeoForge was still at 1.20.6, and when 1.21.1 came out, NeoForge went to 1.21.1, but NeoForge 1.21 was skipped!

### Steps to reproduce

1. Install Modrinth
2. Open the app
3. Create a new instance
4. Select NeoForge

### Expected behavior

1.21 shows up

### Additional context

I tried NeoForge 1.21.1 with Sinytra Connector 1.21 but it crashed for no reason! There wasn't much changes for Minecraft 1.21.1 since Minecraft 1.21.

**Comment by Norbiros** [comment]
Problem will be fixed in `0.8.0`. I can download latest beta from discord server
