### ISSUE TITLE
Project Follow/Save/Report buttons not working

### ISSUE THREAD

**Issue by srnyx** [modrinth/code#2172]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Chrome (including Arc, Brave, Opera, Vivaldi)

### Describe the bug

When I click the Report button for a project, it just takes me to https://modrinth.com/auth/sign-in which instantly redirects to https://modrinth.com/dashboard without any actual steps to report the project. It also says I have no active reports when I go to https://modrinth.com/dashboard/reports

I've tried logging out and back in on Modrinth, but it didn't work

Console just says this:
![image](https://github.com/user-attachments/assets/dca59074-08c8-498c-b41e-06e4aaa6c6ed)

### Steps to reproduce

1. Go to a project
2. Click the red Report button
3. It'll take you to your dashboard without reporting the project

### Expected behavior

I've never actually reported a project before (when it was working), so I'm not exactly sure what *should* happen, but I definitely don't think it should just take me to the dashboard

**Comment by srnyx** [comment]
Wait this is actually happening with more than just Report, it's happening with Follow and Save as well
Not just on one project, it's on every project I try, no matter the type

**Comment by Viotomix** [comment]
Can confirm, it's happening for me as well.
I'm on Firefox 129.0
