### ISSUE TITLE
Launcher causes Fabric Loader to crash on 24w33a

### ISSUE THREAD

**Issue by modmuss50** [modrinth/code#2175]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.7.1

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

Minecraft 24w33a now depends on its own version of ASM alongside fabric loader. Unlike the vanilla launcher and MultiMC the Modrinth launcher is including 2 copies of ASM on the classpath causing Fabric loader to bail out early. The Modrinth launcher produces no log output, either displayed in the UI or the launcher log file making this very hard to debug without the correct tools/knowledge of the problem.

Looking at the command line arguments passed to Java using [Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) I see the following entries:

```
com.modrinth.theseus\meta\libraries\org\ow2\asm\asm-analysis\9.6\asm-analysis-9.6.jar
com.modrinth.theseus\meta\libraries\org\ow2\asm\asm-commons\9.6\asm-commons-9.6.jar
com.modrinth.theseus\meta\libraries\org\ow2\asm\asm-tree\9.6\asm-tree-9.6.jar
com.modrinth.theseus\meta\libraries\org\ow2\asm\asm-util\9.6\asm-util-9.6.jar
com.modrinth.theseus\meta\libraries\org\ow2\asm\asm\9.3\asm-9.3.jar
com.modrinth.theseus\meta\libraries\org\ow2\asm\asm\9.6\asm-9.6.jar
```

as you can see ASM is there twice, the expected behaviour would be for the launcher to always use the version provided in the Fabric profile [json](https://meta.fabricmc.net/v2/versions/loader/24w33a/0.16.2/profile/json) replacing or upgrading anything provided by minecraft.

Please reach out to me if you need any more information.

### Steps to reproduce

Create a 24w33a profile with Fabric loader 0.16.2.

### Expected behavior

The game runs

### Additional context

https://github.com/FabricMC/fabric-loader/pull/965

**Comment by Felix14-v2** [comment]
Seems to be working in 0.8.0
![image-10](https://github.com/user-attachments/assets/60ae0b67-5df1-410c-92fe-dbdd484c6fb6)

**Comment by K0NN4** [comment]
It worked for me on 0.16.0

**Comment by modmuss50** [comment]
I can still reproduce this on the latest version, using loader 0.16.0 is useless as it does not contian the check for duplicated ASM. Please test with Loader 0.16.2.

**Comment by Geometrically** [comment]
Fixed on latest
