### ISSUE TITLE
Can't create forge profile for 1.20.3/1.20.4

### ISSUE THREAD

**Issue by engineer-in-a-box** [modrinth/code#2176]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.7.1

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

When I attempt to create a forge profile for 1.20.3 or 1.20.4 I get the following error:
![image](https://github.com/user-attachments/assets/0e904176-b7b0-4e07-b9fb-8e326c9d0808)

### Steps to reproduce

1. Click on create profile
2. Select forge loader
3. Select game version 1.20.3 or 1.20.4
4. Create profile

**Comment by Geometrically** [comment]
Fixed in latest version
