### ISSUE TITLE
Button Icon in Project Settings Manage Members Page is off-centered (Offset Upwards).

### ISSUE THREAD

**Issue by rotgruengelb** [modrinth/code#2179]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

The Icon in the Button, in Projects Settings, used to expand/view a member's settings in the Manage members page, is offset upwards.
![grafik](https://github.com/user-attachments/assets/f55a3f94-d099-4c77-8a00-04ec6e2a89e6)
![grafik](https://github.com/user-attachments/assets/32529f82-4438-4e10-8b08-5ec80dd0b6b2)

### Steps to reproduce

1. Open a Project's settings.
2. Navigate to "Members"
3. See Broken Expand Button.

### Expected behavior

Centered Icon.

**Comment by rotgruengelb** [comment]
Sorry, wording the title of this is/was a real challenge for me. 
Please Edit/Change.

**Comment by MagnusHJensen** [comment]
Opened a PR for this: #2177
