### ISSUE TITLE
Neoforge Mods Added to resourcepack folder

### ISSUE THREAD

**Issue by Bit-Flare** [modrinth/code#2181]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Theseus v0.7.1

### What operating systems are you seeing the problem on?

Windows 11

### Describe the bug

When adding many mods (but not all) to a 1.21.1 neoforged instance they are place in the resourcepack folder rather than the mod folder. There is no obvious factor for which mods are impacted.

![image](https://github.com/user-attachments/assets/f39fd906-0691-40b4-a8e6-fc19abe89157)

Known impacted mods:
- AppleSkin
- FerriteCore
- ImmediatelyFast
- ModernFix
- Mouse Tweaks

### Steps to reproduce

1. Create new 1.21.1 Neoforge instance (stable)
2. Add affected mods
3. Check folder resourcepack folder for instance

### Expected behavior

Mods saved to mods folder.

### Additional context

This seems to be similar to this closed issue: https://github.com/modrinth/code/issues/1215

**Comment by Geometrically** [comment]
Fixed in latest version
