### ISSUE TITLE
New Modrinth Update caused my Custom Modpack to launch incorrectly

### ISSUE THREAD

**Issue by TheNamesJames** [modrinth/code#2186]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.1

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

Modrinth asked me to update, so I did. Upon completion I tried to launch my custom modpack that I have been playing flawlessly for months, only to find that Minecraft had launched in Vanilla. Tried to restart both the app and my computer but it still did this. Then I uninstalled Modrinth and reinstalled it, and now the modpack is launching in Forge and whatnot, but closes without a crash log during launchup during the "Loading Bootstraps" phase. Not sure what to do here

### Steps to reproduce

To reproduce the problem I would launch a custom modpack with the new Modrinth version. That's all I did

### Expected behavior

I expected the modpack to launch as usual, fully functional via forge with the mods installed and functioning, as it had hours before I updated the app.

**Comment by imheavi** [comment]
You need to click "Edit mod loader/game versions" in your modpack settings, then simply reselect the Forge version you were using. This bug only seems to appear with Forge instances.

**Comment by TheNamesJames** [comment]
thank you
