### ISSUE TITLE
New Modrinth update lacks some Minecraft versions

### ISSUE THREAD

**Issue by Leiriad** [modrinth/code#2188]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.1

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

I tried to launch my custom neoforge modpack after updating and I have this issue:
![2024-08-21 14_44_34-Modrinth App](https://github.com/user-attachments/assets/c0bccd26-561e-4ab5-8941-8350cb39902d)
Errors says the 1.20.1.jar does not exist. When checking, meta/versions/1.20.1 folder only contains 1.20.1.json. 

### Expected behavior

Modded Minecraft launching

**Comment by Norbiros** [comment]
Try opening instance's Options and repairing it.

**Comment by Leiriad** [comment]
It worked thank you
