### ISSUE TITLE
Padding Bug

### ISSUE THREAD

**Issue by prodbyeagle** [modrinth/code#2192]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Modrinth App v0.8.1

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

The Padding for the Ad Banner isnt here on the browse page

![image](https://github.com/user-attachments/assets/809d47c2-b28a-4913-95ae-592494c280e0)

![image](https://github.com/user-attachments/assets/fa004752-47ae-43ac-a879-edaaefb9ccbf)

**Comment by Khazoda** [comment]
This issue is also present when the banner is removed with Modrinth+

![image](https://github.com/user-attachments/assets/e15e8814-4a30-42a3-9761-89035b515a55)

**Comment by Geometrically** [comment]
Fixed in latest beta
