### ISSUE TITLE
Version number shows above Version title

### ISSUE THREAD

**Issue by KingContaria** [modrinth/code#2198]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

In the reworked versions tab, the Version number (3.0.0+1.20.6) shows above the Version title (3.0.0 - 1.20.5-1.21.1).
I put the minecraft target version that my mod is compiled against into the version number (same as in my fabric.mods.json), but I update the version title when it works fine on newer versions. That way users can see that the version works without me having to make a new release or changing the version number which would then no longer be the same as the actual version number in the mod itself.
![grafik](https://github.com/user-attachments/assets/5f056a98-d36e-43fa-b487-9b684e02218a)

### Steps to reproduce

1. Go to https://modrinth.com/mod/fastquit/versions
2. Check the latest version and see that 3.0.0+1.20.6 is shown at the top eventhough 3.0.0 - 1.20.5-1.21.1 is set as the title

### Expected behavior

Version title should show above the version number.

**Comment by Minenash** [comment]
This isn't a bug. Their rational is that the vast majority of the title is duplicate information to what's right next to it. And now that there isn't a featured version section (which also has the same info, but was smaller), these's less emphasis on the title. 

There's an argument to be made that the version number shown should be customizable (as it can also show duplicate information, but that would be a separate gh issue
