### ISSUE TITLE
Files in instances completely vanish from the file system (folders are left intact), and yet, they're still accessible by Minecraft??

### ISSUE THREAD

**Issue by MCAlexisYT** [modrinth/code#2211]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.1

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

The title is literally what the issue is.

### Expected behavior

The files should appear in file explorer and be accessible by other programs, duh.

### Additional context

[Reddit post with additional context](https://www.reddit.com/r/Minecraft/comments/1exvx75/minecraft_world_data_vanishes_and_yet_the_game/)

**Comment by Geometrically** [comment]
Not a bug, the Modrinth App directory is updated, so your content is accessible now at %APPDATA%/ModrinthApp
