### ISSUE TITLE
Option for the old UI

### ISSUE THREAD

**Issue by BeagleNF404** [modrinth/code#2219]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [X] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

Website

### Is your suggested feature related to a problem? Please describe.

Redesigns are often great. Some may love them, while others don’t. I’m part of the group that doesn’t like it. The old design felt more readable, usable, and overall just more appealing (at least to me).

### Describe the solution you'd like

Consider adding an option (similar to what Wikipedia does) to switch back to the old UI. You could even allow users to mix and match by separating the main page and the header, so they can choose which version they prefer for each.

![image](https://github.com/user-attachments/assets/2c5c3854-acd3-4414-9d8c-160976d54321)

**Comment by LyoGyo** [comment]
I very much agree with this

**Comment by Prospector** [comment]
Unfortunately, it's not possible for us to maintain multiple frontend options for Modrinth. We'll be continuing to enhance the new UI design over the next few weeks which should hopefully resolve any issues you have with it.

**Comment by cute-catgirl** [comment]
I understand that maintaining multiple versions would be too much effort, but would it be possible to have it as a "legacy" option, clearly marked as unsupported?

**Comment by Norbiros** [comment]
> I understand that maintaining multiple versions would be too much effort, but would it be possible to have it as a "legacy" option, clearly marked as unsupported?

We modify a lot of our codebase for new UI. Supporting both versions means modifying almost everything to support 2 styles. I think that it's better to keep updating new UI than spending time maintaining old one...
