### ISSUE TITLE
Resizing the app window doesn't save after app restart

### ISSUE THREAD

**Issue by ItsPasi** [modrinth/code#2223]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.1

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

Setting the app to a custom window size is not saved after restarting the app. It will always load with the same default size.

### Steps to reproduce

1. Open the app
2. Change the size of the app window
3. Close the app
4. Size has changed

### Expected behavior

It should save the size of the window it has been set to

**Comment by IntellGaming** [comment]
Having the same issue here on v0.8.2 of the app on Windows.

**Comment by Felix14-v2** [comment]
Modrinth App v0.8.0 is not affected

**Comment by imheavi** [comment]
Also having this issue, but the window appears in weird locations on my monitor, and sometimes doesn't appear at all.

**Comment by ItsPasi** [comment]
I just googled this issue and found a workaround for now. For anyone who is annoyed, just put the app to a size you like and then press CTRL while clicking the close button on the taskbar. This should save the size. Haven't tested if it saves after PC restart though.
![grafik](https://github.com/user-attachments/assets/1bb2b83a-c911-4d3d-aefd-076cbb2fe68a)

**Comment by ItsPasi** [comment]
Fixed in newest app version
