### ISSUE TITLE
Youtube embeds don't work

### ISSUE THREAD

**Issue by CodeF53** [modrinth/code#223]
### Describe the bug

`iframe`s, like youtube embeds, don't render properly.

Here is [A mod with a youtube `iframe`](https://modrinth.com/mod/maxvar-reap) open in theseus and firefox side by side
![left window showing theseus not rendering the video, right window showing firefox rendering the video](https://github.com/modrinth/theseus/assets/37855219/ad17c057-bd6c-4e2b-8931-97477c4bc1fb)

### Steps to reproduce

1. Create an instance > `Add content`

2. Search "MaxVar reap" > click on it

3. Observe

### Expected behavior

Render the iframe

**Comment by thesuzerain** [comment]
Seems to be fixed now with newest update.

**Comment by Banzobotic** [comment]
@thesuzerain 
This bug is present for me in v0.5.2
