### ISSUE TITLE
"Upgrade to Modrinth+" navbar button is present for Modrinth+ subscribers 

### ISSUE THREAD

**Issue by Khazoda** [modrinth/code#2230]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Microsoft Edge

### Describe the bug

With the partial navbar revert it seems the conditional rendering of the "Upgrade to Modrinth+" was lost.
It's still there when logged into an account that is subscribed to Modrinth+.

![image](https://github.com/user-attachments/assets/97271f3c-b2bd-41bd-a034-2c9a1df754af)

### Steps to reproduce

1. Sign in to the Modrinth site with an account that has Modrinth+
2. Click "More" in the navbar

### Expected behavior

The "Upgrade to Modrinth+" button shouldn't be visible

**Comment by Prospector** [comment]
Fixed, thanks for reporting! Might take a few minutes to propagate
