### ISSUE TITLE
Padding is missing when the ad banner dissapears

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [modrinth/code#2235]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

8.1

### What operating systems are you seeing the problem on?

Linux

### Describe the bug

If you bough modrinth+ the ad banner dissapears which leaves behind nothing and lets the ui thingy hit the top bar
![image](https://github.com/user-attachments/assets/ca3d2302-8cf9-4bb2-82ea-cbff79849641)

### Steps to reproduce

1. buy modrinth plus 
2. open the app
3. click on browse or add content to an instance

### Expected behavior

padding above the stuff

**Comment by Khazoda** [comment]
I believe this is a duplicate of https://github.com/modrinth/code/issues/2192

**Comment by Schweeeeeeeeeeeeeeee** [comment]
oh yeah sorry
