### ISSUE TITLE
get support button does nothing

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [modrinth/code#2236]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

8.1

### What operating systems are you seeing the problem on?

MacOS, Linux

### Describe the bug

get support button does nothing in the app no popup no opening soimthing in my browser

### Steps to reproduce

1. open the app
2. click on get support

### Expected behavior

does something or doesent exist

**Comment by Schweeeeeeeeeeeeeeee** [comment]
also the get support button when pressing add account twice (does nothing for me)

**Comment by Norbiros** [comment]
Duplicate of https://github.com/modrinth/code/issues/520

**Comment by Schweeeeeeeeeeeeeeee** [comment]
okayy sorry
