### ISSUE TITLE
folder button doesent open the folder

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [modrinth/code#2238]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

8.1

### What operating systems are you seeing the problem on?

Linux

### Describe the bug

the folder button in an instance does nothing

### Steps to reproduce

open instance click folder

### Expected behavior

Open the instance folder in my filde manager

### Additional context

idk if its an appimage problem but i dont think so because rpcs3 can open folders

**Comment by Norbiros** [comment]
Duplicate of https://github.com/modrinth/code/issues/520

**Comment by Schweeeeeeeeeeeeeeee** [comment]
sorryyy
