### ISSUE TITLE
User profile view ignores Left alignment settings

### ISSUE THREAD

**Issue by Ember-ruby** [modrinth/code#2242]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

![Screenshot_22_1839181](https://github.com/user-attachments/assets/da8cb931-0e8b-4704-8529-9c85f9f85255)
![Screenshot_22_1838581](https://github.com/user-attachments/assets/3c77cd81-78cb-4b79-b323-0575a93b2959)

**Comment by Minenash** [comment]
Tbf, the options say project/search, not user. But yeah, probably should be included with project

**Comment by Erb3** [comment]
No longer applicable, the sidebar has been respectfully imploded. The only thing on the right is the ad, and I think that would look odd on the left.

![Image](https://github.com/user-attachments/assets/b14d17ee-f95f-4922-963b-8f7684a7395c)

**Comment by Prospector** [comment]
there's also an option for this now
