### ISSUE TITLE
Move the Mod Filters back to the top

### ISSUE THREAD

**Issue by HorrorJay** [modrinth/code#2245]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [x] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

Website

### Is your suggested feature related to a problem? Please describe.

The filters were on the top of the page previously, which made it easy to quickly select a mod loader and version and then download the version you were looking for. With the new ui you now need to scroll down (which admittedly isnt a big problem) but it makes it slower and more annoying.

### Describe the solution you'd like

Bringing the filters back to the top of the versions page would help a lot, as well as making the button to select versions into a dropdown and making the buttons a bit bigger then what they currently are.

### Additional context

This isnt a big issue but would help with site usability a bit.

**Comment by Minenash** [comment]
I'm assuming this is for the versions tabs rather than search. If you don't want to scroll down, the new download button is basically the same as the old top filters

**Comment by HorrorJay** [comment]
completely missed this somehow, exactly what i wanted!
