### ISSUE TITLE
Window Bug

### ISSUE THREAD

**Issue by prodbyeagle** [modrinth/code#2250]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Modrinth App v0.8.2

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

https://github.com/user-attachments/assets/f9b13377-a2d8-464f-b53a-7ba47ca44fae

### Steps to reproduce

Open App
make it fullscreen
restart app and then i should be offscreen a little bit

### Expected behavior

window to stay in its position

**Comment by Creper189592** [comment]
AAAAAAAAAAAAAAAAAAAAA THIS  VERSION IS BUGGED
