### ISSUE TITLE
Page title sticks after visiting project version

### ISSUE THREAD

**Issue by Ikethepro18** [modrinth/code#2262]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Chrome (including Arc, Brave, Opera, Vivaldi)

### Describe the bug

If you visit a specific version on a project, say [this](https://modrinth.com/mod/fabric-api/version/0.102.3+1.21.2) version of Fabric API, and then return to the project's description/about using the navigation bar, the webpage title will stay as though you were visiting the project version. This only happens when going to the about section and going to gallery or changelog works fine, but when returning back to the about page the title will return. This is fixed by restarting the page

### Steps to reproduce

1. Visit a version page for a project
2. Navigate to the project's about page
3. The page's title remains as though the version page is open

### Expected behavior

The page title should return to the appropriate name ({project) - Minecraft {projectType})

**Comment by Minenash** [comment]
Forgot to make this issue myself. Interestingly, this happened before the recent design changes

**Comment by Ikethepro18** [comment]
Curious, I should've thought this was caused by it. I wonder how long it's been an issue

**Comment by Minenash** [comment]
Also, apparently it's a duplicate, #1447
