### ISSUE TITLE
Folders not being exported in the config folder

### ISSUE THREAD

**Issue by omo50** [modrinth/code#2264]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.2

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

Before 0.8.2, i could export my modpack fine without having to manually include an options.txt folder. However, as soon as i updated, i can no longer include **any** folders in my modpack export, causing issues

### Steps to reproduce

Make a modpack with YOSBR and include an options.txt in it
Export modpack
Import modpack

### Expected behavior

folders should be able to be included in exports

**Comment by imheavi** [comment]
Have you tried selecting the YOSBR folder in the modpack export screen?

**Comment by omo50** [comment]
> Have you tried selecting the YOSBR folder in the modpack export screen?

the folder simply doesnt show up in the menu, ive tested pretty throughly and i cannot seem to find a way to export a folder in the config folder

**Comment by ThatKnownStranger** [comment]
Just adding on that I am also experiencing this issue. I make sure the folder I wish to export is checked, but when I import the newly created modpack, the folder is not there. I didn't have this issue before.

The folder in question is "defaultoptions", which is used for a similar mod as YOSBR to provide default options.
![Screenshot 2024-08-27 104007](https://github.com/user-attachments/assets/7173a75c-d74d-45b7-938c-98dc59ab6350)

**Comment by Norbiros** [comment]
Duplicate of  #2271. It was fixed in #2273

**Comment by omo50** [comment]
fixed in #2273
