### ISSUE TITLE
Default minecraft settings

### ISSUE THREAD

**Issue by CodeF53** [modrinth/code#227]
### Is your suggested enhancement related to a problem? Please describe.

Every time I make a new minecraft instance I:
  1. change GUI scale to 3
  2. drop FOV and Distortion Effects to 25%
  3. increase Max Framerate to Unlimited
  4. decrease Darkness Pulsing
  5. enable monochrome logo
  6. turn directional audio and subtitles on
  7. decrease mouse sensitivity to 50%
  8. swap sneak and sprint keybinds
  9. unbind hotbar activator keys
  10. unbind social interactions screen

This gets tedious and takes a lot of time to remember everything every time I make a new instance

### Describe the solution you'd like

Add default minecraft settings that get applied to every new instance I create, saving me like 15 minutes every time I make a new instance.

**Comment by Minenash** [comment]
Closing in favor of #299
