### ISSUE TITLE
I/O error: Access is denied. (os error  5) when duplicating a profile

### ISSUE THREAD

**Issue by Thurinum** [modrinth/code#2270]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Modrinth App v0.8.2

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

Upon duplicating a profile:

![image](https://github.com/user-attachments/assets/fe803a64-a190-4d16-954a-dfdc80084ba1)

Profile duplication fails with the following error:

![image](https://github.com/user-attachments/assets/8eb77152-bf1a-4a11-a95e-8b22bacacdbf)

The incomplete new profile remains on disk, and in the GUI as "Installing", until deleted:

![image](https://github.com/user-attachments/assets/d813ae17-c841-4152-8ea6-59edac5cd869)

**After investigating, I found out problematic directories are always empty. Placing dummy files inside those directories resolves the issue:**

![image](https://github.com/user-attachments/assets/a2005c8b-2b38-422a-ae3d-a4dd3cc89d3b)

Doing this for all empty directories in the profile (which is tedious) allowed me to duplicate it from the GUI correctly. Note that the "defaultconfig" and "datapacks" folders are recreated (empty) by modrinth app every time I open the app, so deleting them wouldn't work.

### Steps to reproduce

See above

### Expected behavior

The profile should duplicate properly without errors.

Also, such errors should be handled more gracefully, with the corrupted profile being cleaned up automatically and the GUI updating accordingly.

**Comment by Geometrically** [comment]
Fixed in latest beta. See discord to download!
