### ISSUE TITLE
Exports not sharing sub folders 

### ISSUE THREAD

**Issue by Mrpressed** [modrinth/code#2271]
### Please confirm the following.

* [x] I checked the [existing issues](https://github.com/modrinth/code/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) for duplicate problems
* [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
* [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Modrinth App v0.8.2

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

When exporting a modpack, Modrinth App either does not see subfolders or does not export them despite being picked.

### Steps to reproduce

1. Open Modrinth App
2. Create a new instance
3. Add any content to instance to make it possible to export
4. Go to instance folder
5. Create a folder `folder`
6. Inside `folder` create a text file `a.txt` and folder `subfolder`
7. In `subfolder` create a text file `b.txt`
8. Export modpack
9. Open modpack file and look into `overrides/folder`

### Expected behavior

Modrinth App would export `subfolder` and `b.txt` that was inside it.

***Edited with added details***

**Comment by imheavi** [comment]
A workaround I found was to rename the exported .mrpack to .zip, copy and paste the subfolders into the .zip, and then rename it back to .mrpack.

**Comment by Mrpressed** [comment]
> A workaround I found was to rename the exported .mrpack to .zip, copy and paste the subfolders into the .zip, and then rename it back to .mrpack.

What about official packs on the site I was planning on updating mine today

**Comment by Mrpressed** [comment]
Update the issue is from the export creator rather than importer

**Comment by Mrpressed** [comment]
https://github.com/modrinth/code/blob/main/apps/app-frontend/src/components/ui/ExportModal.vue

Line 35-100 is the issue.

**Comment by Minenash** [comment]
Fixed via #2273
