### ISSUE TITLE
50% or 90% goes to creators?

### ISSUE THREAD

**Issue by james090500** [modrinth/code#2290]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Microsoft Edge

### Describe the bug

![image](https://github.com/user-attachments/assets/267fb5a5-10f7-47ad-8581-54663db35a41)

Modrinth says 90%, modrinth plus says 50%... which is it?

### Steps to reproduce

1. Go to modrinth, look at ad.

**Comment by Prospector** [comment]
90% of ad revenue. 50% of Modrinth+ subscription.
