### ISSUE TITLE
Supported versions cannot be retroactively changed anymore

### ISSUE THREAD

**Issue by AnOpenSauceDev** [modrinth/code#2293]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

I was quickly going to update the metadata of the latest release for my mod (Faster Random) to list support for 1.21.1, but the "Game Versions" field has no way to add versions for some reason.

![image](https://github.com/user-attachments/assets/63b36015-b342-4a59-9e41-a0140f615b0e)
(No idea why ads don't show up for me, I've disabled my blocker)

This bug appears when trying this on all of my mods.

### Steps to reproduce

Edit a mod version, and look at "Game versions". The version dropdown won't be there.

### Expected behavior

A dropdown with versions, like the above "Loaders" field.

### Additional context

This bug is from the new UI, as I had no trouble editing versions before this.

**Comment by Minenash** [comment]
Try clearing your browser cache

**Comment by AnOpenSauceDev** [comment]
The issue is still persisting, and I don't really think that cache would be a problem here, especially because I've signed in with the same problem on other devices.

**Comment by Prospector** [comment]
I can't reproduce this on any of my projects or your project. Could you open up the debug console in your browser and let me know if there are any errors in there?

**Comment by AnOpenSauceDev** [comment]
Odd, for me it just came back today. There are no errors in the console, and it's working as intended. I'm not sure what fixed this in the first place as I've done nothing.

**Comment by AnOpenSauceDev** [comment]
This is incredibly strange. Versions show up and can be changed on Faster Random, but not on my other mod Methane. (Window size does not affect the existence of the dropdown)

![image](https://github.com/user-attachments/assets/34fd762b-7cc2-4786-b999-a574d646ce3a)

**Comment by Minenash** [comment]
Were you able to look at console on the page that it did happen?

**Comment by AnOpenSauceDev** [comment]
I am getting a: "this.customLabel is not a function" error, and both projects now cannot have their versions changed anymore.

What I have noticed just now is that as the page loads, the version dropdown is there, but it vanishes after the page is loaded.

**Comment by dandelionstep** [comment]
Having the exact same issue in both Firefox & Safari -- also seeing "TypeError: this.customLabel is not a function".
