### ISSUE TITLE
All files dissapear after update

### ISSUE THREAD

**Issue by AcoYTMC** [modrinth/code#2294]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.2

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

When updating from version v0.7.1 to v0.8.2, every single files in the modrinth directory that wasn't a folder, was deleted, leaving me unable to launch any of my existing instances, or use any of my datapacks

### Steps to reproduce

Launch the app after restarting the computer, update from v0.7.1 to v0.8.2, check instance files (not folders, those stay), encounter the issue of no files

### Expected behavior

I expected to be able to relaunch my minecraft instance, and continue working on my datapack

### Additional context

If it matters, my instances all dissapeared around a month ago, so I used the profiles folder, as the home for the folders (profiles, meta, caches, launcher_logs, etc.), (AppData\Roaming\com.modrinth.theseus\profiles\profiles\MYINSTANCE) and everything except the folders in the in the meta folder dissapeared too

**Comment by AcoYTMC** [comment]
Upon changing the directory back to AppData\Roaming\com.modrinth.theseus\profiles It starts to delete all files from instances already there, and before that wouldn't let me create a new profile

**Comment by Geometrically** [comment]
This is not a bug. Your instances weren't deleted. They are available at %APPDATA%/ModrinthApp
