### ISSUE TITLE
Mod incompatibilities should include the versions

### ISSUE THREAD

**Issue by FxMorin** [modrinth/code#2300]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [X] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

Website

### Is your suggested feature related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/c13b78ff-ab0e-46e2-8843-79a35e17ecd2)
Users believe that mods are incompatible with Sodium, however its only incompatible with <0.5.0

### Describe the solution you'd like

I would like you to display the range that its incompatible

### Additional context

[more culling](https://modrinth.com/mod/moreculling/version/0.27.0)

**Comment by FxMorin** [comment]
https://modrinth.com/mod/moreculling/version/0.27.0

**Comment by Prospector** [comment]
It is already possible to set the versions a mod is incompatible with, though not exactly ranges.

**Comment by FxMorin** [comment]
Yes im aware. However the website doesn't show this to the user. Making it seem as if the mod is just incompatible with the other mod. Instead of just incompatible with lower versions

**Comment by Prospector** [comment]
It does though? ![Screenshot_20240826-073730.png](https://github.com/user-attachments/assets/56fa931a-5d5b-4825-93cb-088b23acfc30)

**Comment by FxMorin** [comment]
On the website? Cause it looks like the image I provided for me

**Comment by Prospector** [comment]
Then it is a project incompatibility rather than a version incompatibly. The creator of the project has to set this, we have no way of determining what versions it is incompatible with unless the uploader sets the metadata

**Comment by Minenash** [comment]
According to the api response, this is a project-level incompatibility. I've opened an issue for it in their repo [MoreCulling#283](https://github.com/FxMorin/MoreCulling/issues/283)

**Comment by FxMorin** [comment]
Where do you change a project-level incompatibility?
