### ISSUE TITLE
Launcher not listing latest modpack update

### ISSUE THREAD

**Issue by Khazoda** [modrinth/code#2305]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.2

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

I updated my modpack an hour ago, and all is fine on the website - the pack can be viewed and downloaded, but the launcher doesn't show the version at all, and I can't update my instance to the new version either.

__Website (Working)__
![image](https://github.com/user-attachments/assets/8b635c54-0abb-4163-816c-d162e8e5e5c4)
__Launcher (Not Working)__
![image](https://github.com/user-attachments/assets/2b8ff3d4-472d-4700-a47e-627890d719a8)
__Change Modpack Version Modal in Launcher (Not Working)__
![image](https://github.com/user-attachments/assets/c42c460e-c5db-4320-bea5-a433d84e89c1)

### Steps to reproduce

1. Open Launcher
2. Navigate to 'June's Minecraft+' modpack
3. View recent versions

### Expected behavior

Most recently updated version should be shown, and be able to be updated to from linked instances

**Comment by Khazoda** [comment]
Also to add - Prism launcher recognizes the new version just fine, so something strange is going on with the Modrinth Launcher it seems.

I made a thread on the Discord server about this problem [here](https://discord.com/channels/734077874708938864/1277721421635911701)

**Comment by MiguVT** [comment]
Its App cache issue, try purge cache as a temporal fix.

**Comment by Khazoda** [comment]
you're a star, thank you that fixed it!

**Comment by OshDubh** [comment]
This issue should probably be kept open, since purging the cache isn't exactly how it *should* be haha.

**Comment by MiguVT** [comment]
> This issue should probably be kept open, since purging the

The second part are true, but the first, purging the cache is other issue, we should open a new issue, there is more than one bug that the fix is purge the cache.
For example, there was a bug that export ignores subfolders, it was fixed but this need to purge cache for works.
