### ISSUE TITLE
Wrong sidebar alignment

### ISSUE THREAD

**Issue by MbtMarco** [modrinth/code#2308]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Safari

### Describe the bug

<img width="1294" alt="Screenshot 2024-08-27 alle 11 45 40" src="https://github.com/user-attachments/assets/236989ff-b842-46b3-ad5e-6492d76d36a2">

**Comment by Minenash** [comment]
This is not a bug and is intentional. I'll change the tag to enhancement

**Comment by Prospector** [comment]
This is intended, the sidebar now is page-wide and is not dependent on the tab selected

**Comment by IntMarco** [comment]
It doesn't seem right in anyway though.
