### ISSUE TITLE
Markdown renderer ignores style="image-rendering:pixelated;"

### ISSUE THREAD

**Issue by CodeF53** [modrinth/code#231]
### Describe the bug

Often for minecraft resource packs, you want to show really small, pixel art images.

Thats what `style="image-rendering:pixelated;"` is for, and it works great on the website. Not so much on Theseus.

### Steps to reproduce

1. Go to "Add content" > Resource packs
2. Search for GUI Scale 3 Font
3. Look at it's description, scroll down

![blurry pixel art](https://github.com/modrinth/theseus/assets/37855219/2df42abc-65e7-4d9b-aa7a-30d722f57713)

### Expected behavior

screenshot of same markdown on modrinth.com
![clean pixel art](https://github.com/modrinth/theseus/assets/37855219/e0454290-db12-40a9-a5fd-26a4d6ffa481)

**Comment by thesuzerain** [comment]
Seems to be fixed with omorphia#76
