### ISSUE TITLE
New "addon" project tag

### ISSUE THREAD

**Issue by QarthO** [modrinth/code#2310]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [X] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

Website/Frontend (app too eventually)

### Is your suggested feature related to a problem? Please describe.

Would love to see an "addon" category tag for projects. Simple as that.

**Comment by SpacEagle17** [comment]
I would actually love that as my project, Euphoria Patches is an add-on to Complementary Shaders and is distributed through a mod

**Comment by Minenash** [comment]
Request new categories in the [megathread (discussions#105)](https://github.com/orgs/modrinth/discussions/105)
