### ISSUE TITLE
New update make ingame screenshots completely invisible

### ISSUE THREAD

**Issue by KuroeC** [modrinth/code#2315]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.2

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

Took screenshots ingame but impossible to find at AppData/Roaming/com.modrinth.theseus/profiles/(profile name)/screenshots. They seem to disappear completely.
Tried to se via the console (cmd.exe) by going in the directory but it says that the volume in C is not named
![Screenshot from the windows cmd.exe](https://github.com/user-attachments/assets/1db39d5b-df79-4d8c-855d-7a2e6f9f51b3)
(It is in French though because I am too)

### Steps to reproduce

1.Update the latest version of modrinth
2.Launch pre-existing profile that was made BEFORE the update
3.Take a screenshot ingame
4.Go to you screenshot folder

### Expected behavior

Expected without the issue : A list of all screenshots done within the profile before and after the update.

### Additional context

The profile name is "Default but better 1.21" I didn't care to name it another way because i thought file and folder names were converted without spaces or dots (I don't know if it changes anything honestly).

By clicking on the screenshot link in the chat (ingame) I can open the folder via XnView and every single screenshot is there, none of them is missing.

**Comment by Felix14-v2** [comment]
Since 0.8.0 Modrinth uses `%AppData%/ModrinthApp` directory for the game data to prevent some incompatibilities with Minecraft itself.

**Comment by KuroeC** [comment]
I can confirm they are there, should I thus remove the old folder ?
