### ISSUE TITLE
App generates broken .window-state file preventing itself from launching again

### ISSUE THREAD

**Issue by bangetto** [modrinth/code#2319]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.3 Beta 2

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

After upgrading from v0.8.2 to the latest beta the app doesn't starts up

### Steps to reproduce

1. Have v0.8.2 
2. upgrade to the beta using the discord attachement 
3. launch
4. not launch?

### Expected behavior

well, it should start up

### Additional context

I might installed the beta twice if in the betas the version number is not changed

**Comment by Somrat10369** [comment]
Same here

**Comment by bangetto** [comment]
I found out that there are logs so, maybe it helps?
[session_20240828_125100.log](https://github.com/user-attachments/files/16783476/session_20240828_125100.log)
```
2024-08-28T12:51:00.318498300+03:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2024-08-28T12:51:06.436392100+03:00  INFO init_watcher: theseus::state::fs_watcher: Initting watcher
```

**Comment by Felix14-v2** [comment]
Try deleting a broken `.window-state` file (may be hidden by default in your explorer) inside your `%AppData%/ModrinthApp` directory. On my system the app creates the broken one after each launch.

**Comment by Felix14-v2** [comment]
> renaming the thread to request the removal of the broken `.window-state` files instead

Modrinth generates the broken file after each launch (at least on my system), so the problem is deeper.

**Comment by Felix14-v2** [comment]
Moreover, if you replace that file with a folder named `.window-state` to prevent the creation of a new file, the launcher will refuse to close.

**Comment by Felix14-v2** [comment]
Could you try Modrinth App 0.8.5? I can't reproduce the issue in this version, so it seems to be fixed.

**Comment by bangetto** [comment]
yeah seems to be fixed
