### ISSUE TITLE
Page numbers in Profile > Content open tauri.localhost link in default browser

### ISSUE THREAD

**Issue by cedro-gasque** [modrinth/code#2329]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.3

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

Clicking these opens a tab in my browser with the URL `https://tauri.localhost/instance/{profile name}/?page={page number}`
![image](https://github.com/user-attachments/assets/ed4fced6-5a95-4e9e-a72b-8748334aded2)

### Expected behavior

The desktop app should not randomly open internal links in a different browser.

### Additional context

I have not tried to reinstall. This happened only after updating to 0.8.3. I did restart the app, and it happened both in Administrator Mode and not. I also cleared the cache.

**Comment by Geometrically** [comment]
Please update your Modrinth App from the latest version from the website, it should work!
