### ISSUE TITLE
Off-platform ResourcePacks don't go in their tab

### ISSUE THREAD

**Issue by CodeF53** [modrinth/code#234]
### Describe the bug

Resource packs not from modrinth don't show up in the resource packs tab.

### Steps to reproduce

1. create a new instance
2. open it's folder and put a resource pack inside
3. observe how the resource pack is displayed inside of "All", and a new "Other" tab has appeared
4. add a resource pack using the Add content button
5. observe how the off-platform resource pack doesn't exist inside the new "resource packs" tab

![image](https://github.com/modrinth/theseus/assets/37855219/9ce2dc85-9c60-48dc-b901-2aae6fa7c4aa)

![image](https://github.com/modrinth/theseus/assets/37855219/673c00cc-e7c6-402d-91cf-155d6dea46b4)

### Expected behavior

All resourcepacks, regardless of origin, are displayed in the resourcepacks tab

**Comment by CodeF53** [comment]
Fixed in 0.3

![image](https://github.com/modrinth/theseus/assets/37855219/74e3b034-6d75-4e23-b9d1-85d048b5becb)

**Comment by triphora** [comment]
Is it fixed? You're testing under nonequivalent circumstances, all of your resource packs are available on Modrinth

**Comment by CodeF53** [comment]
I forgot Fresh Animations got added to modrinth, so I thought it was still offplatform

**Comment by CodeF53** [comment]
![image](https://github.com/modrinth/theseus/assets/37855219/4a396af9-1eef-411f-a548-dc62492815a9)
