### ISSUE TITLE
Modrinth+ ads shown even for paying users

### ISSUE THREAD

**Issue by adaliszk** [modrinth/code#2346]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.5

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

As a Modrinth+ user, I am promised not to see any ad blocks. Despite that, the app shows ads for the Modrinth+ subscription.

### Steps to reproduce

- Open any mod, modpack, shader, or resource pack.
- Open any instance.

### Expected behavior

Ads, even for the Modrinth+, are hidden as promised.

**Comment by Felix14-v2** [comment]
Are you sure you are logged in your Modrinth account in the App itself?

**Comment by adaliszk** [comment]
Yes, I have logged in with the same discord user on both the website and the app;
- on the website it does work, no ads are shown
- in the app, it does not work, ads for modrinth+ are shown

**Comment by Geometrically** [comment]
Make sure to relaunch the app. Try logging out and logging back in as well.

**Comment by adaliszk** [comment]
Okay, I cleared the cache and re-logged it, and now it works. Sorry for the needless ticket.

**Comment by Felix14-v2** [comment]
> Sorry for the needless ticket

If the cache become broken, then there's a problem with it that's still needs investigation
