### ISSUE TITLE
M+ link opens three times

### ISSUE THREAD

**Issue by w26ad** [modrinth/code#2349]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.5

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

M+ link opens three times instead of one when clicked on banner.

### Steps to reproduce

1. Click M+ ad banner in the app
2. See that link opens in your browser three times

### Expected behavior

It opens only once

**Comment by Felix14-v2** [comment]
Clickng to the ad section is enough, this will open a link three times.

https://github.com/user-attachments/assets/13093692-cda3-4560-8b82-807c7c922084

**Comment by Felix14-v2** [comment]
@Minenash , could you reopen this?
