### ISSUE TITLE
Ads appear above gallery images

### ISSUE THREAD

**Issue by polywally24** [modrinth/code#2357]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.5

### Describe the bug

Ads show up above gallery images on project pages

https://github.com/user-attachments/assets/ec023733-5df2-49fd-8a6d-64ec3e9335f5

### Steps to reproduce

1. Go to the project listings
2. Find a project with larger gallery images (smaller images don't go over the ads section)
3. You should see the ads overlaying the images

### Expected behavior

I expected the ads section not to clip over the images because it blocks the view where information could be put

**Comment by Felix14-v2** [comment]
Duplicates https://github.com/modrinth/code/issues/2257
