### ISSUE TITLE
Excessive RAM usage when having the launcher open

### ISSUE THREAD

**Issue by LeinadUchiha** [modrinth/code#2366]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.5

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

when having a profile open in the launcher where the advertising implemented in the latest updates is displayed, the RAM usage is increased every time the advertising is changed, this is automatically and just by having the launcher open, it has come to consume more than 2gb of ram by having it open for only 1 hour and it does not stop increasing the longer the launcher is open, in the image I sent it is consuming 500mb just by opening it but it continues to increase as the minutes go by.

![image](https://github.com/user-attachments/assets/0e526a75-f845-4534-b568-472616e924fe)

2 minutes later it is already consuming another 20mb more

![image](https://github.com/user-attachments/assets/a122a720-44f6-4ee5-8b68-bdff23b84407)

### Steps to reproduce

Just have the launcher open in a profile where the advertising is

### Expected behavior

Before the update where new advertising influenced this did not happen
![image](https://github.com/user-attachments/assets/5978656c-ec51-4d57-bbc3-71ba6b90abcc)

### Additional context

It is annoying to have excessive RAM consumption just because you want to use your launcher
![image](https://github.com/user-attachments/assets/f4735012-f9f5-4184-96a7-0274b532f73f)

**Comment by Norbiros** [comment]
Possibly connected to https://discord.com/channels/1129467000381526156/1268039496125907017

**Comment by oliverjhn** [comment]
I have this as well.
