### ISSUE TITLE
Gallery image gets shrunk when uploaded

### ISSUE THREAD

**Issue by Lykrast** [modrinth/code#2373]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

I'm uploading minecraft screenshots in my mod gallery (in this case https://modrinth.com/mod/glassential/gallery) but all the images seem to get shrunk to thumbnail size, even after multiple attempts of uploading.

![image](https://github.com/user-attachments/assets/26439a3d-3d14-49f0-8a18-69c1211243c9)

Link to the image itself https://cdn.modrinth.com/data/kVa5y52B/images/3941ef4faae59a6748dbe55a208a9b0ae1e60296_350.webp

After going through my mods it seems they all have that issue somehow (like https://modrinth.com/mod/meet-your-fight/gallery or https://modrinth.com/mod/book-wyrms/gallery). Those were 1920x1017 png minecraft screenshots.

It seems some mods may have a similar issue (although I don't know what the authors tried to upload), like maybe this one https://modrinth.com/mod/every-compat/gallery ? But some mods gallery are fine, like this one https://modrinth.com/mod/macaws-quark/gallery where everything is the proper size.

### Steps to reproduce

1. Upload big image to gallery.
2. It's small.

**Comment by Geometrically** [comment]
Fixed
