### ISSUE TITLE
Taskbar shortcut opens older version of app

### ISSUE THREAD

**Issue by Owehttamy** [modrinth/code#2375]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.5 AND(?) v0.8.2

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

This doesn't appear to be that big of a problem—I don't see this causing any issues currently, but I'm throwing this out here because it seems unusual:
I have had a taskbar shortcut for Modrinth on Windows, but when opened, it's still in v0.8.2. Thankfully, it has the popup notifying the existence of v0.8.5. When I request it install the newer version, Modrinth appears to recognize that v0.8.5 already is installed and opens it, dropping a new shortcut in the desktop and whatnot as well, but I'm wondering if there's an issue with remnants of v0.8.2 remaining on user devices.
At the very least, it appears that there may be an oversight regarding how Modrinth handled upgrading to version 0.8.5, leaving old files behind when it migrated the application's location from the Program Files directory to the user's local AppData directory.
![ModrinthShortcuts](https://github.com/user-attachments/assets/cc0fce2b-f3ee-4625-b03a-569eb94f3fd1)

### Steps to reproduce

1. Upgrade Modrinth on a Windows 11 device from v0.8.2 to v0.8.5.
2. Navigate to `C:\Program Files\Modrinth App` to determine if v0.8.2's files remain.

### Expected behavior

v0.8.2's files are removed when successfully upgrading to a newer version, as well as deprecating or upgrading outdated shortcuts.

**Comment by brawaru** [comment]
[This](https://github.com/modrinth/code/issues/2362) is [a](https://floss.social/@modrinth/113094214030485319) [known](https://discord.com/channels/734077874708938864/734084055225597973/1281736641953796288) [issue](https://support.modrinth.com/en/articles/9838590-the-app-repeatedly-asks-to-update) :P

**Comment by Owehttamy** [comment]
Whoopsie
