### ISSUE TITLE
Modrinth 0.8.7 auto-updating without requesting the users permission

### ISSUE THREAD

**Issue by wolvyreen** [modrinth/code#2387]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.5

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

When having 0.8.5 installed and opening the app, it immediately attempts to update to 0.8.7 without confirming with me that I actually want to update to 0.8.7.

I uninstalled everything and reinstalled 0.8.2 and when starting 0.8.2, it does ask permission first.

### Steps to reproduce

1. Have 0.8.5 installed
2. Start the app
3. you will see it auto-installs 0.8.7 without asking permission first

### Expected behavior

It should first ask me as a user if I want to update and give me the choice.

**Comment by imheavi** [comment]
It shows the UAC window, you can just say no.

**Comment by brawaru** [comment]
@imheavi it does not show UAC prompt on non-admin accounts, and declining UAC prompt will just do nothing, the app has already exited for update at this step.

**Comment by Felix14-v2** [comment]
> It shows the UAC window

It doesn't.

**Comment by imheavi** [comment]
Weird, it appeared for me. Maybe because I'm on an admin account.

**Comment by Geometrically** [comment]
Not a bug
