### ISSUE TITLE
libssl.so.1.1 is not a dependancy in the deb

### ISSUE THREAD

**Issue by BeastRein** [modrinth/code#239]
### Describe the bug

when installing the modrinth app using the deb file in debian or ubuntu, you have to seperately install libssl.so.1.1
you should add libssl1 as a dependancy for the deb file as to make the install process easier

and seeing as libssl1 is outdated and no longer in many repos, you should also consider updating to libssl3 which most linux distros support

### Steps to reproduce

install deb file
i have to manually install libssl1

### Expected behavior

if libssl was a dependancy i would not have to manually install it
however the deb does not specify that it needs libssl

**Comment by MeIsGaming** [comment]
On Kubuntu 23.04, installing libssl from official sources is as far as I see not possible. Also the symlinks aren't in /usr/lib/ anymore, but in /lib/x86_64-linux-gnu/.

Output from "ldconfig -p | grep ssl":

```        libxmlsec1-openssl.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libxmlsec1-openssl.so.1
        libssl3.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl3.so
        libssl.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so.3
        libssl.so.3 (libc6) => /lib/i386-linux-gnu/libssl.so.3
        libssl.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so
```

**Comment by Boxersteavee** [comment]
it is also not recommended to install libssl1.1 on ubuntu as it can cause some issues. Libssl3 is preinstalled with ubuntu (23.04)

**Comment by egut** [comment]
I tried really hard to find the definition of the deb-package build but I failed, I look through at least most the documentation and search via GitHub but nope, so I guess the definition isn't in a public repo or I can't search. 

After some fiddling I got Cargo to build the UI and I only have (correct) libssl3 installed so what I could see it worked fine when right libraries are installed and used. 

Anyway if someone can point to the deb package code (and maybe how to trigger it) I can have a look.

**Comment by Boxersteavee** [comment]
Interesting. Perhaps it has been fixed unintentionally at some point in the last 2 months or so.

**Comment by egut** [comment]
@Boxersteavee have you had time for "soon", yet? ;)

**Comment by Boxersteavee** [comment]
Ah, entirely forgot about this, no I don't. I will test it if I remember about this when I am in a position to be able to test it.
