### ISSUE TITLE
Ad overrides loading screen

### ISSUE THREAD

**Issue by w26ad** [modrinth/code#2390]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.7

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

![image](https://github.com/user-attachments/assets/c80854bf-caec-4b56-ba7c-af2978e85bac)

**Comment by Geometrically** [comment]
Fixed
