### ISSUE TITLE
Option to Disable Showing Library/Utility Mods

### ISSUE THREAD

**Issue by ShadowTech99001** [modrinth/code#2391]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [X] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### Is your suggested feature related to a problem? Please describe.

I always get so excited when I'm searching for mods and find some sort of mod called "Stardust" or something cool. Then, I click on it and it's just a library mod. Other times, my search is just flooded by these types of mods.

### Describe the solution you'd like

I propose the option to hide library mods. This would likely require a new subtag for client sided mods called "library."

### Describe alternatives you've considered

None

### Additional context

None

**Comment by Minenash** [comment]
You can use negative filters to achieve this
![Screenshot_20240911-141617](https://github.com/user-attachments/assets/b424e158-02f1-4668-85ca-fdbdc5dd813f)

**Comment by ShadowTech99001** [comment]
I didn't even know about this. Thank you!
