### ISSUE TITLE
Allow different versions of mods to be installed on different versions of Minecraft with a warning

### ISSUE THREAD

**Issue by VsevkaD** [modrinth/code#2393]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [X] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

App

### Is your suggested feature related to a problem? Please describe.

Sometimes the author of the mod does not say that a newer version of Minecraft supports their old mod, however It works fine. It would be great if in your launcher was the ability to force any version of the mod on any version of Minecraft with a warning. At the moment you have to download the mod from modrinth website and put it in a mod folder.

### Describe the solution you'd like

Need a checkbox that would allow you to forcibly install the mod on an “incompatible” version, or a warning “ this mod may not work properly on your version of Minecraft do it at your own risk”.

**Comment by lukasabbe** [comment]
If I understand you right. 
This is already a feature of the app. 
![image](https://github.com/user-attachments/assets/05f0b32f-8f76-435a-b78f-723fbd6beede)
just click them in the left corner and you can download any mod on Modrinth

**Comment by VsevkaD** [comment]
> If I understand you right. This is already a feature of the app. ![image](https://private-user-images.githubusercontent.com/67807954/366608082-05f0b32f-8f76-435a-b78f-723fbd6beede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwODQ5NjYsIm5iZiI6MTcyNjA4NDY2NiwicGF0aCI6Ii82NzgwNzk1NC8zNjY2MDgwODItMDVmMGIzMmYtOGY3Ni00MzVhLWI3OGYtNzIzZmJkNmJlZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE5NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZWU2MDkwNDU5YzlkNGZmNjkyMjc1NTNjOWVkNzg4MmNiYWQ4OGFjNDY4NzBhNzFjM2VmY2FhZGRmNTY5ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zMZ3Bnw4lGHeHV6X0Cs-iwKHQRXuWSZ-qrY2ySP9NFQ) just click them in the left corner and you can download any mod on Modrinth

Yeah I think that's what I need, but I can't find it, can you be more specific please?

**Comment by lukasabbe** [comment]
When you are in the add mods menu.

That box from that photo is in the left corner

**Comment by VsevkaD** [comment]
> When you are in the add mods menu.
> 
> That box from that photo is in the left corner

![image](https://github.com/user-attachments/assets/77570e6a-7bc6-4ddc-943e-d4c7920e653e)
On this tab?

**Comment by lukasabbe** [comment]
Or no, you need to be in a profile. See that u are under the search menu. Go to your profile and than press the add mods button

**Comment by VsevkaD** [comment]
> Oh that must be a bug, i have modrinth+ and for me that setting is under the ad space

Wait, i just found it after clicking: RMB on my instance -> add content, and then it appeared

**Comment by VsevkaD** [comment]
Yeah

> Or no, you need to be in a profile. See that u are under the search menu. Go to your profile and than press the add mods button

**Comment by VsevkaD** [comment]
Thank you.
