### ISSUE TITLE
Modrinth broken with Arc Browser

### ISSUE THREAD

**Issue by Specimen-420** [modrinth/code#2395]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Chrome (including Arc, Brave, Opera, Vivaldi)

### Describe the bug

Selecting any link or button on the website doesn't do anything.

### Steps to reproduce

1. Go to the modrinth website.
2. Interact with the website

### Expected behavior

for the button I pressed to work 😭

**Comment by Geometrically** [comment]
Clear your browser cache
