### ISSUE TITLE
What does pending mean?

### ISSUE THREAD

**Issue by imheavi** [modrinth/code#2403]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### Describe the bug

What does revenue pending mean? The link doesnt go anywhere, and I can't find any info online or on Modrinth.
![Screenshot 2024-09-13 195732](https://github.com/user-attachments/assets/e7ce3f2f-2087-4ac9-9d38-f4113a7217c9)

### Steps to reproduce

Go to Dashboard
Have "pending" revenue

### Expected behavior

The Pending text highlighted in blue should take me to a page explaining what that means.

**Comment by Felix14-v2** [comment]
https://modrinth.com/legal/cmp-info?utm_source=blog.modrinth.com&utm_medium=referral&utm_campaign=quintupling-creator-revenue-and-becoming-sustainable#pending

That's a new ad system change:
https://blog.modrinth.com/p/creator-revenue-update
> First, revenue is no longer entirely paid out the day they are earned. Previously, we used our own in-house advertisement deal which paid us in advance for the entire month, and we divided that among each day in the month, as the month progressed. With the switch to a more traditional ad network, we are paid on a NET 60 basis, which is fairly standard with ad networks. What this means is that some of your revenue may be pending until the ad network pays us out.

**Comment by imheavi** [comment]
Oh wow.
