### ISSUE TITLE
Ads capable of playing audio even when the application is minimized

### ISSUE THREAD

**Issue by budak7273** [modrinth/code#2414]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Modrinth App v0.8.7

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

Ads displayed in the Modrinth App are capable of playing audio, including when the app is minimized.

### Steps to reproduce

1. Open the Modrinth App
2. Go to any screen with an ad (for example, the detail view of a modpack)
3. Sit on the screen for a while, optionally with the application minimized
4. Get "lucky" and get an ad served with audio. For me it was some sort of sportsball ad.

### Expected behavior

Ads will be displayed and cycled, even when the application is minimized, but ads will _never_ play audio because of how intrusive that is.

### Additional context

Possible workaround: Mute the Modrinth application (appears as `Microsoft Edge WebView2` in the Windows volume mixer)

**Comment by budak7273** [comment]
It took 34 minutes for it to come up again. This is the 1 ad I have found consistently playing audio
![image](https://github.com/user-attachments/assets/7c834b83-c047-4b41-a2ea-364dff27fddc)

The ad UI indicates that it's supposed to be muted by default, but it is still playing sound through that. Interacting with the mute button again properly mutes it.

**Comment by DisdainofDeimos** [comment]
Thanks for the workaround! This has been driving me absolutely nuts. I can understand running ads but the constant sportsball max volume jumpscares have been driving me up the WALL. 

Modrinth you need to ban this ad (if it's abusing something in your system to bypass the mute) and fix your system ASAP!!! This is lowkey unacceptable levels of annoying. Still love you guys tho

**Comment by TheDarkPanther** [comment]
> It took 34 minutes for it to come up again. This is the 1 ad I have found consistently playing audio ![image](https://private-user-images.githubusercontent.com/25965766/367962144-7c834b83-c047-4b41-a2ea-364dff27fddc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODM2MTcsIm5iZiI6MTcyNzU4MzMxNywicGF0aCI6Ii8yNTk2NTc2Ni8zNjc5NjIxNDQtN2M4MzRiODMtYzA0Ny00YjQxLWEyZWEtMzY0ZGZmMjdmZGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA0MTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ODc0NjFlODI4OTI5NzcwODMwMTAxNjc0ZGQxZWU3MGUyMjIxYzFjN2FmNmRmY2E0ZTc4YmI5ZjlmODkyODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nWUcvPBquHGot8n5eahBh9Ml4GcZleQ1tyDSZJOXnJk)
> 
> The ad UI indicates that it's supposed to be muted by default, but it is still playing sound through that. Interacting with the mute button again properly mutes it.

Yea that is the ad that keeps it's audio on and I don't see it anywhere so i am very confused

**Comment by Tschipcraft** [comment]
May be fixed by #2471

**Comment by Geometrically** [comment]
Fixed
