### ISSUE TITLE
Nothing being clickable on the website

### ISSUE THREAD

**Issue by Monkeee-code** [modrinth/code#2418]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

So when i go to the website, buttons, links and even text are not clickable. the only way i can click/open links is with middle click on my mouse or with right click! The only time the left click works is after i open/refresh the page, i can click for like 3-5sec then it becomes unclickable.

### Steps to reproduce

1. Go to https://modrinth.com
2. wait 3 sec
3. try to click a button, text, search-bar, drop down menu...
4. Nothing else

### Expected behavior

I expect it to work so for example: when i click "versions" for a mod, it should open the versions tab, but it doesnt

### Edits

EDIT: some buttons in dashboard/profile screen work and buttons like "Mods, Data packs, etc..." also work, but only on the main menu (modrinth.com). Microsoft Edge browser works normally.

**Comment by rotgruengelb** [comment]
Can't confirm

**Comment by rotgruengelb** [comment]
Do you have any extensions installed?

**Comment by Monkeee-code** [comment]
> Do you have any extensions installed?

Yes, but nothing that connected to modritnh and adBlocker is disabled for modrinth. Rn im in school and i will detail a list of extensions when i come home!

**Comment by rotgruengelb** [comment]
@Monkeee-code Jup, this is a known problem. You can simply exclude modrinth in "i don't care about cookies”, no need to disable the whole extension.

**Comment by Monkeee-code** [comment]
> @Monkeee-code Jup, this is a known problem. You can simply exclude modrinth in "i don't care about cookies”, no need to disable the whole extension.

Yeah, im aweare.
