### ISSUE TITLE
Instance Folder Name not in sync with Instance Name

### ISSUE THREAD

**Issue by Tranzitron** [modrinth/code#2424]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Modrinth App v0.8.7

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

When duplicating an instance, the **_new_** instance will get the **_old_** instance name as its **_folder name_** and **_instance name_**. When renaming the new instance name, the folder name stays the same as the old instance name.
Exemple: Old instance (name="OldTest",folderName="OldTest"). When duplicating it, it creates a new instance (name="OldTest",folderName="OldTest (1)"). Obviously i want to rename it, so i rename the new instance name to "NewTest" in the modrinth app. The new instance is now partially updated (name="NewTest",folderName="OldTest (1)"). If i want to force the name change and manually go in file explorer and rename the folder of new instance to "NewTest". I need to relaunch the app and it then doesnt find the "NewTest" instance.

### Steps to reproduce

1. Create an instance (mark it as old)
2. Duplicate that instance
3. Rename the new instance
4. Realize the new instance folder name is the same as the old instance name
5. (Optionnally) Force the rename by renaming the folder manually
6. Modringth doesnt find the instance anymore

### Expected behavior

There are many fixes possible. I ordered them as my preference but they are equally as good

1. Renaming an instance in the launch syncs its folder name as the new name - Easy but might be invasive for a few power users
2. Require a name when duplicating an instance (prefill with old instance name?) - Very easy, intuitive, not invasive
3. Add a way to set instance folder location in that instance's settings - NOT user friendly, not invasive

### Additional context

This is a big deal for me because i make a new modpack instance every new version by duplicating the previous version's modpack instance. All the instances folder names are of the version just before it.
1.20.2 is actually 1.20.2
1.20.2 (1) is actually 1.20.4
1.20.4 is actually 1.21
Its not THAT big of a deal but it's just an annoyance and something that shouldn't be like it is.

**Comment by BumbleRumbler** [comment]
I had the same issue, I found a simple way around.

1.   Change the instance name to the name you want to give the folder
2.   Duplicate the instance, it will create and use a folder with the name you gave to the instance
3.   Delete the original instance

**Comment by Geometrically** [comment]
Not a bug
