### ISSUE TITLE
Ads being served from supposedly compromised domain

### ISSUE THREAD

**Issue by Fevix** [modrinth/code#2430]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.7

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

The ads appear to be using a compromised website. Every few minutes while Theseus is open, Malwarebytes will give me a notification about it blocking a connection to "hob9zeclb.puzztake.com" due to the website being compromised. 

### Steps to reproduce

1. Install Malwarebytes Premium with Real-Time Protection enabled
2. Install Theseus
3. Run Theseus and wait a few minutes for Malwarebytes to block a connection

### Expected behavior

Either the website is compromised and ads served from it need to be removed from rotation, or the website ISN'T compromised and someone needs to let Malwarebytes know so they can allow connections

**Comment by Geometrically** [comment]
Fixed
