### ISSUE TITLE
8.7.0 download are broken

### ISSUE THREAD

**Issue by 1ntel-kokos** [modrinth/code#2433]
###  Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

8.7.0

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

if you start downloading modrinth launcher on newest version, it will choose to go to the `Program Files` directory and it dont want download

### Steps to reproduce

just download the newest [modrinth app](https://modrinth.com/app)

### Expected behavior

the location of modrinth app directory should go to the `AppData` instead of `Program Files`

**Comment by Geometrically** [comment]
Not a bug
