### ISSUE TITLE
Flatpak fails to launch

### ISSUE THREAD

**Issue by hb0nd** [modrinth/code#2442]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.2

### What operating systems are you seeing the problem on?

Linux

### Describe the bug

App fails to launch. 
running `flatpak run org.modrinth.ModrinthApp returns:
```
Gtk-Message: 17:38:47.122: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:38:47.122: Failed to load module "pk-gtk-module"
Gtk-Message: 17:38:47.123: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:38:47.123: Failed to load module "pk-gtk-module"
```
then crashes.

**Comment by RedAuburn** [comment]
ah i didn't see #1186,
the first command in https://github.com/modrinth/code/issues/1186#issuecomment-2104911642 fixed it for me.
