### ISSUE TITLE
Not Opening File Viewer

### ISSUE THREAD

**Issue by hamb-clanker-donottrust** [modrinth/code#246]
### Describe the bug

Hello, I'm on **Fedora Workstation 38** and use the default **GNOME**. I have an issue where I can't access any files/folders through the modrinth launcher (i.e stuff like a modpack's folder.)

### Steps to reproduce

-Have a non-configured installation of Fedora Workstation 38
-Install the appimage and use a program called gearlever to install it (found on flathub)
-Launch the modrinth app
-Right Click on an installed instance
-select 'open folder'

### Expected behavior

I expected it to open the folder through the default **Files** _(that is the only one installed and the one set to default)_ file manager on fedora workstation 38, but instead it did nothing.

**Comment by Geometrically** [comment]
duplicate
