### ISSUE TITLE
Versions 1.8.2 - 1.18.2 wont load on linux

### ISSUE THREAD

**Issue by Dylanstas** [modrinth/code#2463]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

version 0.8.2

### Describe the bug

I just cant load Minecraft versions 1.8.2 - 1.18.2, i've tried forge on 1.8.9, vanilla on 1.8.x and up to 1.18.2 and it just wont load, sometimes i get the window for like a second and then it vanishes and never boots again, i've also tried different java versions with 1.18.2, tried the default (jvm 8) tried jvm 17 and jvm 21 and none of them worked, anything below 1.8.2 or above 1.18.2 will work fine, and i have tried the repair button, did nothing. I have used Minecraft 1.8.9 on lunar client and it worked fine

### Steps to reproduce

1. Add a instance for 1.8.9 vanilla or forge
2. launch it
3. watch it not boot

### Expected behavior

game launches

### Additional context

I use Linux Mint 22 x86_64
Desktop Env: Plasma 5.27.11
Window Man: KWIn
GPU: Nvidia GeForce RTX 4060
CPU Intel Core i5 12th gen

**Comment by Dylanstas** [comment]
and no modpacks wont load

**Comment by OzoneGameDev** [comment]
I can confirm this also happens for me.

Modrinth app version 0.8.7, flatpak
Fedora Linux 40 GNOME

Tried versions 1.8.9 and 1.12.2, none boot 
Tried changing assigned memory, used Java version, nothing worked.

**Comment by Geometrically** [comment]
Update to the latest Modrinth App version and repair your profiles

**Comment by Dylanstas** [comment]
just did, aint working, i have only tested 1.8.9, when i updated, the app stopped working, then again and it worked, but 1.8.9 didn't :(
