### ISSUE TITLE
All links on the modrinth website dont work

### ISSUE THREAD

**Issue by Vendropen** [modrinth/code#2468]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

I go to the modrinth website and all links simply dont work

### Steps to reproduce

Go to modrinth
Click a link
It dont work

### Expected behavior

The selected link to open

### Additional context

Used to work on firefox but now it only works on chrome*

**Comment by Geometrically** [comment]
Not a bug, clear your browser cache
