### ISSUE TITLE
Modrinth Flatpak OS Error 30

### ISSUE THREAD

**Issue by Flatfire** [modrinth/code#2479]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.7

### What operating systems are you seeing the problem on?

Linux

Specifically Fedora 40 running in Wayland with KDE Plasma 6.1.5
Kernel v6.10.11-200

### Describe the bug

Upon opening the flatpak version of Modrinth, I'm greeted with this:
![image](https://github.com/user-attachments/assets/3f532dcd-aced-46ac-86ec-fe6566ca520e)

Strangely, all was working just fine until a restart. I'm perplexed as to what changed. I've used Flatseal in an attempt to provide broad access for test purposes, but it looks like the permissions issue is occurring within the container itself. 

The logs offer little in the way of information:
```2024-10-01T09:23:09.692334780-04:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2024-10-01T09:23:09.996822890-04:00  INFO init_watcher: theseus::state::fs_watcher: Initting watcher
2024-10-01T09:23:10.044466073-04:00  INFO initialize_state: theseus_gui: Update found: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("launcher-files.modrinth.com")), port: None, path: "/versions/0.8.8/linux/Modrinth%20App_0.8.8_amd64.AppImage.tar.gz", query: None, fragment: None }
```
The only thing I could gleam from this is that it could be attempting to extract the updated Modrinth version within the Flatpak and is failing to do so.

I'd love for this to work, as the AppImage version also just doesn't seem to launch at all.

### Steps to reproduce

Open Flatpak > Profit?

### Expected behavior

It should continue to load the Theseus GUI.

**Comment by cfpwastaken** [comment]
This might be under the same issue. I am also using flatpak and after starting the app just now I am only getting "Error initializing modrinth app": "Invalid cross-device link (os error 18)"

**Comment by kason-i** [comment]
same issue here, was using AppImage yesterday, now it is not launcher so I tried switching to flatpak, getting the exact same error.
`Read-only file system (os error 30) at path "/app/bin/tauri_current_app8IX2Mw"`

**Comment by Flatfire** [comment]
> This might be under the same issue. I am also using flatpak and after starting the app just now I am only getting "Error initializing modrinth app": "Invalid cross-device link (os error 18)"

I received this after I did a bit of fiddling with the flatpak, but wasn't able to reproduce that specific one again. I believe it's related to a freedesktop dependency.

**Comment by Flatfire** [comment]
Adding some additional context: This definitely appears to be a 0.8.8 bug. Modrinth auto-updates from earlier AppImages and doesn't work as a result. It's clearly trying to do the same from within the 0.8.7 flatpak, so it's not strictly a Flatpak problem, just a byproduct. I suspect that even once the Flatpak updates to 0.8.8, it won't work as expected.

**Comment by John-Development** [comment]
> Invalid cross-device link (os error 18)

Having the same issue in the 0.8.7 flatpack version. Last AppImage update killed the app and I tried to install the flatpack with no success

**Comment by John-Development** [comment]
> I rolled back using the flatpak command line, this helped

Which commit did you rollback to?

**Comment by Flatfire** [comment]
> > I rolled back using the flatpak command line, this helped
> 
> Which commit did you rollback to?
> 
> EDIT: Just the previous one seem to work
> 
> `sudo flatpak update --commit=2c272ac8480cc6dc635451bae84636949472326662b8d3dd33a532b20d0df719 com.modrinth.ModrinthApp`

This helps when running existing instances, but I appear to be unable to download modpacks in this state :/

**Comment by Geometrically** [comment]
Could anyone try using the builds here:
https://github.com/modrinth/code/actions/runs/11138841090

And see if they work?

Direct link: https://nightly.link/modrinth/code/actions/runs/11138841090/ubuntu-22.04.zip


If so LMK and I'll update the official binary.

**Comment by fuelflo** [comment]
I've got the same problem with 0.9.2. I start the App then modrinth tries to update itself but fails with:

> Read-only file system (os error 30) at path "/app/bin/tauri_current_appUSc9fV"
