### ISSUE TITLE
App version 0.8.8 will not launch

### ISSUE THREAD

**Issue by tbohart** [modrinth/code#2480]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.8

### What operating systems are you seeing the problem on?

Linux

### Describe the bug

After an update to 0.8.8, the app does not launch.

I am using the appimage on Ubuntu 24.04.1, and the following is printed to the terminal upon running the appimage:

`Error: Error executing 'Modrinth': No such file or directory`

The 0.8.7 appimage runs only to automatically update to 0.8.8, then crash the same way. It then crashes that way immediately when run again.

The .deb also does not launch, but I could not verify the terminal output.

### Steps to reproduce

1. Download 0.8.8 appimage
2. Mark as executable
3. Run in terminal

### Expected behavior

App launches (displays any kind of GUI, allows use of app)

**Comment by Fivvee0** [comment]
I have that issue too.

**Comment by RetroDogo** [comment]
same dude!

**Comment by pokahs** [comment]
Also just got this, though was running the .deb when I first encountered it :/

**Comment by kaidenart** [comment]
experiencing this on windows 11

**Comment by JensenJ** [comment]
Also having this issue. Tried .deb and AppImage. None of them work on version 0.8.8.

**Comment by koloja** [comment]
having the same issue on windows 11 but with the error message
`Error while applying migrations: migration 20240930001852 was previously applied but is missing in the resolved migrations`

**Comment by Type-julian012** [comment]
![image](https://github.com/user-attachments/assets/f587c8d8-6c73-45bb-ab08-7053731d4af3)

**Comment by LandonbRichards** [comment]
![FUCK THIS](https://github.com/user-attachments/assets/5de663af-52a0-49b6-89d1-84657030e6b6)
Has anyone found a fix for this yet?? Ive seen multiple people with this exact issue today.

**Comment by koloja** [comment]
> ![FUCK THIS](https://private-user-images.githubusercontent.com/120593183/372677415-5de663af-52a0-49b6-89d1-84657030e6b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MjQ5NDQsIm5iZiI6MTcyNzgyNDY0NCwicGF0aCI6Ii8xMjA1OTMxODMvMzcyNjc3NDE1LTVkZTY2M2FmLTUyYTAtNDliNi04OWQxLTg0NjU3MDMwZTZiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQyMzE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjE0Zjg3NTI4YmNhMTgxYzhiYTMwZGZjZWI1ZjdlNWJiYjE5Y2Y1YjgxZTU0YjA4ZjI2MjE1NmY1YzFmZDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.v61Kflhppxw7NOCcyTMcml5R_V5TPIQAQS1WxEJi_hI) Has anyone found a fix for this yet?? Ive seen multiple people with this exact issue today.

on windows 11 launching from the exe works for me

**Comment by LandonbRichards** [comment]
Where are you doing that? I followed the shortcut pressing open file location until im at appdata < Local < Modrinth app and then try opening thesues_gui. which I thought was the .exe. But when opening that I get the same error. Thanks for the reply btw

**Comment by spusuf** [comment]
Same on Arch Linux.

**Comment by Flatfire** [comment]
Might be worth merging this and my own thread #2479 as they're the same problem it appears.

**Comment by LandonbRichards** [comment]
I FIXED IT. lol. I copied my worlds on to my desktop so I wouldnt lose anything and completly uninstalled the launcher and reinstalled it. I noticed after downloading the app again the setup file version went from 0.8.5 to 0.8.8. Not sure if its a version issue but this fixed it for me.

**Comment by kason-i** [comment]
> Has anyone found a fix for this on linux yet?

This is working to fix the flatpak:
https://github.com/modrinth/code/issues/2479#issuecomment-2386557920

**Comment by tbohart** [comment]
I found for those using the .deb, you can manually run it from /usr/bin/Modrinth\ App. You can also make a .desktop file in ~/.local/share/applications to be able to run it without using the terminal every time. This is working for me currently.

**Comment by mpustovoi** [comment]
Same on Windows 10

**Comment by Masu-Baumgartner** [comment]
A temporary fix for the linux users using the .AppImage version of modrinth is to downgrade to the previous version and block the auto updating by modifying the */etc/hosts* file.

A link to the previous release:
https://launcher-files.modrinth.com/versions/0.8.7/linux/Modrinth%20App_0.8.7_amd64.AppImage

Line to add at the end of the */etc/hosts* (requires root, sample command: `nano /etc/hosts`)
`127.0.0.1 launcher-files.modrinth.com`

**Dont forget to undo this line in the hosts file after they fixed the issue as the launcher is not able to update until you remove this which can make you miss some important updates**

**Comment by pokahs** [comment]
> Line to add at the end of the /etc/hosts (requires root, sample command: nano /etc/hosts)
127.0.0.1 launcher-files.modrinth.com

Note this also got the .deb package working for me :p

**Comment by Geometrically** [comment]
Could anyone try using the builds here:
https://github.com/modrinth/code/actions/runs/11138841090

And see if they work?

Direct link: https://nightly.link/modrinth/code/actions/runs/11138841090/ubuntu-22.04.zip


If so LMK and I'll update the official binary.

**Comment by Masu-Baumgartner** [comment]
Hey hey, the nightly build is working fine :3

**Comment by pokahs** [comment]
> Could anyone try using the builds here:
https://github.com/modrinth/code/actions/runs/11138841090

tried this, both AppImage and Deb are working. updated to the deb provided :p

**Comment by AncientMRG** [comment]
> I found for those using the .deb, you can manually run it from /usr/bin/Modrinth\ App. You can also make a .desktop file in ~/.local/share/applications to be able to run it without using the terminal every time. This is working for me currently.

I can manually run it, but the icon is never generated and can´t get it to run with the desktop file... how did you do it (total newbie here)

**Comment by tbohart** [comment]
The desktop file can be named anything you want (I just used `modrinth.desktop`)
It is placed in `~/.local/share/applications`.

It should contain the following text:
```
[Desktop Entry]
Exec='/usr/bin/Modrinth App'
Icon=Modrinth App
Name=Modrinth App
Terminal=false
Type=Application
MimeType=application/zip+mrpack;x-scheme-handler/modrinth

```

You can then reload the desktop files with this command:
```
update-desktop-database ~/.local/share/applications/
```

This is based on an existing .desktop file I found in the appimage.

If the icon does not load, you may need to put a filed named `Modrinth App.png` in `~/.local/share/icons/hicolor/128x128/apps`

I believe this site has further documentation if you are interested in .desktop files: [https://specifications.freedesktop.org/desktop-entry-spec/latest/index.html#introduction](https://specifications.freedesktop.org/desktop-entry-spec/latest/index.html#introduction)

**Comment by pokahs** [comment]
If you're using the deb package (and now updated), and now the desktop file suddenly doesn't work, I would assume the desktop file somehow broke. I would check if your modrinth desktop file (which might be in /usr/share/applications/)'s Exec line is running the exact same thing as you would run in your terminal to launch modrinth. I think the name of the app changed from modrinth-app to Modrinth App in some places, so you might want to look for this. Though overall, would just recommend to update to the newest deb Geometrically provided if you haven't.

**Comment by AncientMRG** [comment]
> The desktop file can be named anything you want (I just used `modrinth.desktop`) It is placed in `~/.local/share/applications`.
> 
> It should contain the following text:
> 
> ```
> [Desktop Entry]
> Exec='/usr/bin/Modrinth App'
> Icon=Modrinth App
> Name=Modrinth App
> Terminal=false
> Type=Application
> MimeType=application/zip+mrpack;x-scheme-handler/modrinth
> ```
> 
> You can then reload the desktop files with this command:
> 
> ```
> update-desktop-database ~/.local/share/applications/
> ```
> 
> This is based on an existing .desktop file I found in the appimage.
> 
> If the icon does not load, you may need to put a filed named `Modrinth App.png` in `~/.local/share/icons/hicolor/128x128/apps`
> 
> I believe this site has further documentation if you are interested in .desktop files: https://specifications.freedesktop.org/desktop-entry-spec/latest/index.html#introduction

Got it to work with your help.  0.8.8 deb pack install works, the .desktop file doesn´t so this worked around it.  Just added a category entry to add it to "Game".  Thanks for your help!

**Comment by noxidsoft** [comment]
On Ubuntu 24.04 LTS I was missing a library. This was a fresh OS install just yesterday, so it makes sense I hadn't picked this one up yet.

`sudo apt install libfuse2t64`

Now the latest AppImage file from Modrinth is working after permissions set correctly. https://modrinth.com/app

Credit: https://itsfoss.com/cant-run-appimage-ubuntu/
