### ISSUE TITLE
Modrith app is not working

### ISSUE THREAD

**Issue by FRANEKbinbanek** [modrinth/code#2487]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [ ] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Latest release on flathub (I can't see what version it is exactly)

### What operating systems are you seeing the problem on?

Linux

### Describe the bug

App is updating and then it shows an error. After clicking "Debug Information" it says "InvalidSignature"
![Zrzut ekranu_20241003_130215](https://github.com/user-attachments/assets/8412b671-90ab-433d-b685-641a3f5ae3f4)

### Steps to reproduce

1. Turn on the app
2. Watch

### Additional context

I tried re-installing it, but it's still showing me the same error message

**Comment by TxMat** [comment]
same error on flatpak as of now

**Comment by iam-nekk** [comment]
Same on Pop OS 22.04. Latest version on the Pop store is 0.8.7, which matches the version on flathub from 10 sept

**Comment by kason-i** [comment]
getting the same "InvalidSignature" on flatpak
I'm on Fedora 40

**Comment by Geometrically** [comment]
This should be fixed now!
