### ISSUE TITLE
For me notification history is not working

### ISSUE THREAD

**Issue by lukasabbe** [modrinth/code#2493]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Chrome (including Arc, Brave, Opera, Vivaldi)

### Describe the bug

It just says "Loading notifications..." forever 
![image](https://github.com/user-attachments/assets/9923d869-8c52-4483-b05e-43975703ce38)

### Steps to reproduce

I have no clue how to get this 

### Expected behavior

To show me the notifications history

### Additional context

![image](https://github.com/user-attachments/assets/8ce0dc8c-4c52-4ca0-9986-5f0065b1c97e)
Error in console

**Comment by denisJaved** [comment]
I think so organization got deleted (because api returns 404). Second error probably caused by first one because it tries to get `types` of null

**Comment by lukasabbe** [comment]
No, the organization thing is on all mods that don't have an organization attached. So that has nothing to do with the error under.
I guess that reports are not handled correctly here. I had a resolved report not that long ago. But I don't know if that's true

**Comment by lukasabbe** [comment]
This is solved now!
