### ISSUE TITLE
Adding files by dragging, not adding

### ISSUE THREAD

**Issue by Minenash** [modrinth/code#2495]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.8

### What operating systems are you seeing the problem on?

Linux

### Describe the bug

When dragging a mod jar into the content area of the app, the cursor changes to the + state, but when letting go, the mod isn't added. At first I thought this might be because of it being locked and just not providing an error message, but it also happens when it's unlocked and unpaired

### Steps to reproduce

1. Open unlocked and unpaired modpack profile
2. Try adding a mod by dragging it
3. See that nothing happens

**Comment by imheavi** [comment]
Functionality might not be implemented for that. Also, on Edge (which the app uses for displaying itself), when you drag a file into the browser window, it displays the file in the Downloads dropdown. Perhaps it's attempting to do that?

**Comment by Norbiros** [comment]
It was probably caused by migration to Tauri v2. We are still subscribing to `file-drop` event but it's now called `drag-drop`
