### ISSUE TITLE
Mods, Cards will not show up in instances

### ISSUE THREAD

**Issue by Qsta981** [modrinth/code#2509]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.8

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

Whenever I load Modrinth now, the mod cards are gone, and when I open an instance page, the mods tab is nonexistent.

### Steps to reproduce

1. Open Modrinth

I have no idea how or why this is happening.

### Expected behavior

Cards should show images and mods tab should show mods

### Additional context

![Image](https://github.com/user-attachments/assets/0f044256-e903-4458-b07a-ed264dc61199)
![Image](https://github.com/user-attachments/assets/fd66848b-57c0-41d7-94f8-2723438562a7)

**Comment by denisJaved** [comment]
I think so it is path related issue, because instance icon aren't loading.

But to confirm, Can you launch any of instances?

**Comment by Qsta981** [comment]
Sorry it took so long to respond. No, I can not launch the instances. Also, whenever I try changing the directory, it shows in the app but the library tab does not change. I do believe it is a path-related issue.

**Comment by denisJaved** [comment]
There are a least 3 path-related issues: #2444

**Comment by denisJaved** [comment]
Did you uninstall second modrinth? (modrinth shows app twice in control panel, so a lot of people deleting one but it's bad idea)

**Comment by Qsta981** [comment]
I just realized my entire Modrinth folder got wiped. I don't know why I did not check that in the first place.
