### ISSUE TITLE
Arch Linux (flatpak) | Can't launch under Hyprland

### ISSUE THREAD

**Issue by fbp172924** [modrinth/code#2516]
# CLOSED - Issue with community made packages. Just use the AppImage.
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Latest as of 2024/10/16 (0.8.8)

### What operating systems are you seeing the problem on?

Linux

### Describe the bug

When i try to launch i get error: 
```
[ben@benarch ~]$ flatpak run com.modrinth.ModrinthApp -v

(modrinth-app-wrapped:2): Gdk-WARNING **: 15:46:22.567: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
```
I've tried every troubleshooting step for xdg-desktop-portal and related under the sun and I still can't get it to launch

### Steps to reproduce

1. Install Modrinth through Flatpak on Hyprland
2. Try to launch it
3. Bug

### Expected behavior

Launches and works

**Comment by RokeJulianLockhart** [comment]
@fbp172924, you've accidentally converted most of the Markdown into a `<pre>` by indenting it.

**Comment by fbp172924** [comment]
thanks @RokeJulianLockhart

**Comment by fbp172924** [comment]
i will try nix and see if that works

**Comment by fbp172924** [comment]
Marking as closed. I got it working.
I downloaded the appImage, and since something with libFUSE is broken on my system, I extracted the Modrinth app installer and then went inside the /usr/bin folder and extracted the Modrinth app binary from that. Works fine now. Something was up with the flatpak stuff.
