### ISSUE TITLE
Export Packs directly through desktop app

### ISSUE THREAD

**Issue by Th4tM0nk3y** [modrinth/code#253]
### Is your suggested enhancement related to a problem? Please describe.

Having to use outside apps or websites to convert a pack to the right format for use on Modrinth is quite laborious, especially when the pack was created directly in the desktop app. Ideally you could export a pack directly in the launcher for quick turnarounds.

### Describe the solution you'd like

Add a button to the right-click menu on the main screen or the pack page in the launcher to allow exporting the modpack in the correct format, just like Moddermore and co have a feature.

### Describe alternatives you've considered

Add the feature to the website exclusively, though that would slow turnarounds down as well

**Comment by Caliel666** [comment]
it's already in the works #135

**Comment by thesuzerain** [comment]
Completed, will be in the next release.
