### ISSUE TITLE
Modrinth can't install 1.20.1 Forge versions above 47.2.17

### ISSUE THREAD

**Issue by TomUjvari** [modrinth/code#2541]
### Describe the bug

It seems more recent versions of Forge 1.20.1 aren't available in the Modrinth app. Some mods like Epic Fight require at least 47.3.0 so it just can't be played on Modrinth.

### Steps to reproduce

1. Create a new instance
2. Select Minecraft version 1.20.1
3. Select Forge, click "show advanced", then "other" loader versions
![Screenshot 2024-08-11 173126](https://github.com/user-attachments/assets/f4cfe1be-d968-469d-ad1f-76a5971b1848)

### Expected behavior

All Forge versions should be available.

### Additional context

Not sure if this counts as a bug but it's very bothersome.

**Comment by MelrikBirchJr** [comment]
this is happening for forge 47.4.22
1.20.1
