### ISSUE TITLE
Iris Shader configs show up in instance resources

### ISSUE THREAD

**Issue by CodeF53** [modrinth/code#255]
### Describe the bug

Iris saves shader configs in the same folder that shader packs are stored in `packname.txt`.

This results in shader configs showing up in an instance's resources.
![image](https://github.com/modrinth/theseus/assets/37855219/da917f04-1908-4aca-8768-5d86345ab1dd)

### Steps to reproduce

1. create an instance
2. click open folder
3. navigate to shaderpacks and create a .txt file there
4. look at the instance's projects, and observe the .txt file

### Expected behavior

If the launcher is going to look at files in `/shaderpacks/`, it should check if they are actually a shaderpack.

This could be a simple as checking if the file is a `.zip`.

### Additional context

![image](https://github.com/modrinth/theseus/assets/37855219/32ebeada-39a5-49bc-af45-5f58dae4f2e0)

**Comment by cootshk** [comment]
Do they show up in the "other" tab?

**Comment by CodeF53** [comment]
yes
![image](https://github.com/modrinth/theseus/assets/37855219/ff443477-59e9-4fb5-a34b-940927a9a0bd)

**Comment by CodeF53** [comment]
![image](https://github.com/modrinth/theseus/assets/37855219/4ea2be6d-f4e8-46fc-b80f-3f7af1a56481)
fixed?
