### ISSUE TITLE
Building.md or automatic releases

### ISSUE THREAD

**Issue by pyscripter99** [modrinth/code#284]
### Is your suggested enhancement related to a problem? Please describe.

  It is currently unclear about how to setup and run this minecraft launcher.

### Describe the solution you'd like

Add a BUILDING.md to the different "projects", or release the build artefacts of your github actions

### Additional context

My current building instructions:
```bash

# Follow steps on: https://tauri.app/v1/guides/getting-started/prerequisites
git clone https://github.com/modrinth/theseus.git
cd theseus_gui # if the following steps don't work, do cd ../, then ru the step below again
npm i
npm install --save-dev @tauri-apps/cli
# Install pnpm: https://pnpm.io/installation
npm install -g pnpm # on windows open command prompt as admin, and run without sudo
npm run tauri dev # test if it works
# Follow steps on: https://tauri.app/v1/guides/building/ for your platform
sudo npm install -g pnpm # on windows open cmd as admin and run without sudo
npm run tauri build
```

**Comment by qtchaos** [comment]
Building theseus is now in the [documentation](https://docs.modrinth.com/contributing#theseus-launcher).
