### ISSUE TITLE
The `<a href="">` to the `.RPM` package at `modrinth.com/app` is null.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [modrinth/code#2848]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

https://fedora.pkgs.org/40/fedora-updates-x86_64/firefox-131.0.3-1.fc40.x86_64.rpm.html

### Describe the bug

Downloading the `.RPM` from [`modrinth.com/app`](https://modrinth.com/app#:~:text=Download%20the%20DEB-,Download%20the%20RPM,-Third%2Dparty%20packages) is impossible, because it's not linked. Undermentioned is a prettified version of the source markup:

<blockQuote cite="https://modrinth.com/app#:~:text=Download%20the%20DEB-,Download%20the%20RPM,-Third%2Dparty%20packages">

```HTML
<a download="" data-v-e081f5d9="">
   <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" data-v-e081f5d9="">
      <path stroke-linecap="round" stroke-linejoin="round" d="M4 16v1a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3v-1m-4-4-4 4m0 0-4-4m4 4V4"></path>
   </svg>
   <span data-v-e081f5d9=""> Download the RPM </span>
</a>
```

</blockQuote>

Note the `download=""`.

### Steps to reproduce

1. Visit https://modrinth.com/app#:~:text=Download%20the%20DEB-,Download%20the%20RPM,-Third%2Dparty%20packages
1. Invoke the link to the `.RPM` package.

### Expected behavior

It should begin to download.

### Additional context

1. Remediating https://github.com/modrinth/code/issues/2847#issue-2601887527 would provide a workaround.
2. Originally reported at https://github.com/modrinth/code/issues/2515#issuecomment-2417901822.

**Comment by Minenash** [comment]
This has been fixed btw!
