### ISSUE TITLE
Inconsistent Project Visibility Information on 'Public' on Project Page

### ISSUE THREAD

**Issue by Rayanzay** [modrinth/code#2858]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Chrome (including Arc, Brave, Opera, Vivaldi)

### Describe the bug

On the project page when creating a project, the information under 'Public' is inconsistent when comparing to the other information.

In other words, there is a "Will be" missing before the details in Public:

![Image](https://github.com/user-attachments/assets/08bd5a1c-6219-4631-9f4a-f4190b1e18ab)

### Steps to reproduce

1. Attempt to create a project
2. Scroll down in the 'General' page until the 'Visibility' section is reached.
3. Under 'if approved by moderators,' the Public option is inconsistent with the rest.

### Expected behavior

Like every other option, there should be a "Will be" in front of all the details in Public:

Public:
![Image](https://github.com/user-attachments/assets/08bd5a1c-6219-4631-9f4a-f4190b1e18ab)

Archived:
![Image](https://github.com/user-attachments/assets/c4882631-33de-4b07-ba83-70a35253e8a0)

Unlisted:
![Image](https://github.com/user-attachments/assets/88ce1b95-3a5e-481f-a09a-87f0640ff347)

Private:
![Image](https://github.com/user-attachments/assets/bcb47201-b35f-419c-bbb8-a422604f322e)

**Comment by Prospector** [comment]
This is intended, Will be indicates what it will be after you save, without it indicates it's the current state.
