### ISSUE TITLE
Mobile sign in to modrinth server redirects exclusively to GitHub

### ISSUE THREAD

**Issue by ChromexUnderscore** [modrinth/code#2884]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Chrome (including Arc, Brave, Opera, Vivaldi)

### Describe the bug

On Chrome for Android, clicking any sign in option on the sign in page redirects exclusively to GitHub.

### Steps to reproduce

https://github.com/user-attachments/assets/1a144228-cce2-47f6-8b92-69ac26532fca

### Expected behavior

Modrinth redirects to the selected sign in option

### Additional context

Device: Google Pixel 6a
Android Version: 15
Android Security update: October 5, 2024
Google Chrome version 130.0.6723.86

**Comment by deany1014** [comment]
Your bug report is wrong, it happens when you try to log in from Modrinth servers page
https://modrinth.com/auth/sign-in?redirect=/servers%23plan
The same happens to pc and phone
