### ISSUE TITLE
Inconsistent sizes for benefits list on the billing & subscriptions page

### ISSUE THREAD

**Issue by RedstoneWizard08** [modrinth/code#2892]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Other (please specify)

### Describe the bug

Saw this on Kiwi Browser on Android, it's a fork of Chromium and I'd imagine it carries over to Chrome, it seems like a CSS issue.

### Steps to reproduce

1. Go to Modrinth on a mobile browser
2. Sign in
3. Go to settings
4. Go to billing & subscriptions

### Expected behavior

Uniformly sized icons.

### Additional context

![Image](https://github.com/user-attachments/assets/e8e1008d-4f22-4231-b5d0-f9ef6d95f522)

**Comment by Erb3** [comment]
duplicate of #2297

**Comment by RedstoneWizard08** [comment]
Ok, sorry, didn't see that one.
