### ISSUE TITLE
Disable Mod adding

### ISSUE THREAD

**Issue by Edeec0** [modrinth/code#291]
### Is your suggested enhancement related to a problem? Please describe.

Preventing Friends from adding cheats

### Describe the solution you'd like

I got really annoyed at my friends when i used to use the Curseforge app and the reason why is that they always added mods like X-ray or the player health indicator mod. so please make it so when you send modpacks you can turn on an option so my friends can't add any mods just by clicking add new content.
thank you

### Describe alternatives you've considered

none

### Additional context

Yeah i dont want my modpack to be changed lol

**Comment by Edeec0** [comment]
May i get answer pwease

**Comment by triphora** [comment]
Solution: get friends who don't cheat

**Comment by intergrav** [comment]
if it's a server, consider using this and including it in the modpack on both sides. those people likely don't know how to bypass it https://modrinth.com/mod/inertiaanticheat
