### ISSUE TITLE
Cant Delete Logs

### ISSUE THREAD

**Issue by Algiuxs** [modrinth/code#2949]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.9

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

When i try to delete the profile logs, i get an error.![Image](https://github.com/user-attachments/assets/71e9f9ef-e75c-4aaa-9c74-6641adcb1839)

### Steps to reproduce

1. login as non admin user
2. Install modrith app system wide
3.  Launch minecraft
4. exit minecraft
5. try to delete that instances logs
6. get the error
### Expected behavior

deletes the log file

**Comment by OwlSeries** [comment]
Looks like name is invalid does restarting app work?

**Comment by Algiuxs** [comment]
> Looks like name is invalid does restarting app work?

Same thing.

**Comment by bendy1234** [comment]
> Looks like name is invalid does restarting app work?

same problem here & the path is actually valid

**Comment by Felix14-v2** [comment]
Can confirm in 0.9.0 as well, that was an issue since the first Modrinth App release afaik.![Image](https://github.com/user-attachments/assets/7c8b4e31-41e5-4133-b41d-e68ac22fd70f)

I suspect the issue is that Modrinth can't handle spaces in usernames:
![Image](https://github.com/user-attachments/assets/c84cc303-b793-4f8a-86d4-1e4dc06c0cef)
![Image](https://github.com/user-attachments/assets/b518c679-cffc-4713-87ca-23b37cff5656)

**Comment by Felix14-v2** [comment]
Oh, you're right

**Comment by Algiuxs** [comment]
> I don't think that's the issue. I don't have any spaces in my username and instance name and it still failed.
> 
> The image from @Algiuxs is edited to hide their username. 

Yep, I edited the username and the mc skin head.

**Comment by Algiuxs** [comment]
> Oh, you're right

Btw, my real username doesn't have spaces, the first letter is capital.

**Comment by bendy1234** [comment]
> > Oh, you're right
> 
> Btw, my real username doesn't have spaces, the first letter is capital.

windows ignores capitalization so `c:/users` is the same as `C:/Users`

**Comment by Algiuxs** [comment]
> Can confirm in 0.9.0 as well, that was an issue since the first Modrinth App release afaik.![Image](https://github.com/user-attachments/assets/7c8b4e31-41e5-4133-b41d-e68ac22fd70f)
> 
> I suspect the issue is that Modrinth can't handle spaces in usernames:
> ![Image](https://github.com/user-attachments/assets/c84cc303-b793-4f8a-86d4-1e4dc06c0cef)
> ![Image](https://github.com/user-attachments/assets/b518c679-cffc-4713-87ca-23b37cff5656)
> 

Quick question, where did you download 0.9.0?

**Comment by bendy1234** [comment]
ahh i found problem

the [function called to delete the log](https://github.com/modrinth/code/blob/main/packages/app-lib/src/api/logs.rs#L277) calles [remove_dir_all](https://github.com/modrinth/code/blob/main/packages/app-lib/src/util/io.rs#L76) which expects a directory and not a single file
