### ISSUE TITLE
App UI fails to load

### ISSUE THREAD

**Issue by TsoyaDeer** [modrinth/code#2967]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.8.2 Flatpak, 0.8.8 .appimage and .deb and 0.8.9 .appimage

### What operating systems are you seeing the problem on?

Linux

### Describe the bug

I have had this issue with multiple different versions of the Modrtinh App. I am currently running Linux Mint 23 Cinnamon.
Any attempt to launch the app fails to load the UI, but the UI elements can still be used. The app window refuses to be resized, and maximising the window does nothing to help the issue. Runninng the .deb file produces the terminal output seen below. I have seen this issue in #2289, #2363 and it may be similar to #2485. I have tried the solutions provided and none of them have worked. I can momentarily parts of the UI by trying to move the window, where it is highlighted.

![Image](https://github.com/user-attachments/assets/8ca41b57-0521-414e-bffa-9eb45f738e30)
![Image](https://github.com/user-attachments/assets/8e6a9b86-6b2b-40dd-9028-4bb8b681552f)

### Steps to reproduce

1: Launch Modrinth using .appimage, Flatpak or via terminal
2: The app opens
3: The UI fails to load, error

### Expected behavior

The UI would load.

### Additional context

I've seen that using version 0.8.5 has worked for some people, but I can't find a way to downgrade to that version.

**Comment by brawaru** [comment]
Duplicate of #1186. The workaround is to use `WEBKIT_DISABLE_DMABUF_RENDERER=1` environment variable.

This might be fixed with 555 NVIDIA driver update.

**Comment by TsoyaDeer** [comment]
Attempting to set the env variable now. Hopefully it works.

**Comment by TsoyaDeer** [comment]
The fix has worked, thanks for the help!

**Comment by ldeninski** [comment]
For me the issue was the accessibility toolkit d-bus. https://github.com/modrinth/code/issues/2289#issuecomment-2573184290
