### ISSUE TITLE
Can't login to Modrinth Account because of Cloudflare protection..

### ISSUE THREAD

**Issue by Kristijan1001** [modrinth/code#2977]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.9

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

This has been a bug for months, i reported it months ago and it did get fixed in AstralRinth App but i can't seem to find the issue anymore.

Problem is upon entering account and password you can't sign in, you get the following error:

An error occurred Error: Failed to login with error Captcha Error. Try resubmitting the form.

Resumbiting the form does not work, everything has been tried from uninstall to restart it doesnt work. 

### Steps to reproduce

Open App and try to login.

### Expected behavior

To actually get logged in.

**Comment by JOLMStruly** [comment]
Can confirm. I cannot login to modrinth due to captcha error

**Comment by MaxNovember** [comment]
Same here, cant believe this shit is not fixed already.

**Comment by Geometrically** [comment]
This is will be fixed in the next launcher update!

**Comment by Geometrically** [comment]
in the meantime you can sign in with OAuth (discord, github, etc)
