### ISSUE TITLE
Modpacks tab missing and content not loading

### ISSUE THREAD

**Issue by IamKoeda** [modrinth/code#300]
### Describe the bug

When trying to browse the different tabs "Modpacks, Mods, Data Packs, Shaders, Resource Packs" they will never load.
After clicking "Add content" a new list of tabs appear, and thease work fine. But the "Modpacks" tab is missing.

### Steps to reproduce

https://github.com/modrinth/theseus/assets/105707865/9f52b95b-eee9-470a-8a0c-250bd75aa535

**Content not loading**
1. Go to home
2. Click "Browse"
3. Click the different tabs "Modpacks, Mods, Data Packs, Shaders, Resource Packs"
Now you should see that the content that should appear, never loads in.

**Modpacks tab missing**
1. Go to "Library"
2. Select an instance
3. Click "Add content"
Now the content from the tabs should work. But the "Modpacks" tab is missing from the tabs navigation menu.

### Expected behavior

**Content not loading**
The content should load in, but seems to not do so. But when going to "Add content" it will now load.

**Modpacks tab missing**
There should be a "Modpacks" tab both after going to "Add content" and before going to it.

**Comment by Parcivalc** [comment]
Same problem here, but you can bypass it by clicking on _popular mods_. However, this doesn't fix the problem.

https://github.com/modrinth/theseus/assets/138236732/51463c45-17e7-4325-9dd0-82ca6a274a79

**Comment by bajspunk** [comment]
Im getting the same problem. Tried reinstalling and deleting com.modrinth.theseus folder in %appdata%

**Comment by ludverse** [comment]
Same on Linux with AppImage
