### ISSUE TITLE
404 Gateway error on third party login

### ISSUE THREAD

**Issue by Rory-Miley** [modrinth/code#3012]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Safari, Chrome (including Arc, Brave, Opera, Vivaldi)

### Describe the bug

404 bad gateway when trying to login using third-party sign in: Github, Google, Microsoft. My guess is the issue happened after alteration to: https://github.com/modrinth/code/blob/main/apps/frontend/src/pages/auth/authorize.vue

### Steps to reproduce

1. Go to login
2. Click a third party login (Google, Github, Microsoft)
3. get 404 gateway error message

### Expected behavior

Open a third party window to login to your account

**Comment by Erb3** [comment]
Your issue is likely caused by Modrinth currently experiencing downtime. https://status.modrinth.com

**Comment by CuddlyCornet645** [comment]
This is an issue on every browser (Server side), not only Safari, Chrome (including Arc, Brave, Opera, Vivaldi) so you cant just donlaod Firefox and expect it to work!

**Comment by Rory-Miley** [comment]
Issue appears to be fixed.
