### ISSUE TITLE
Modrinth App will not launch

### ISSUE THREAD

**Issue by Evansch0** [modrinth/code#3036]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Newest version downloaded from the site.

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

I am currently running the newest build posted to the modrinth website. i fully uninstalled and reinstalled a few times. i used revo uninstaller to remove any trace files as well. I am unable to start the program what-so-ever currently it hangs with 6.1-6.3 mb of ram used.  But as of right now it currently doesnt even try to launch. This became an issue about a week ago. i am unsure if an update had happened. I am using 2x E5-2690 v4's with 128 gb ddr4 ecc.

### Steps to reproduce

1. install from website
2. doesnt launch

### Expected behavior

Program launches and runs as expected

**Comment by Geometrically** [comment]
This ix fixed in the latest commit

**Comment by Evansch0** [comment]
This is still not fixed on windows 11

**Comment by izmystic** [comment]
It's not in an update yet, just fixed in the latest commit

**Comment by Evansch0** [comment]
i downloaded the compiled version from the recent run and tested.
