### ISSUE TITLE
Latest (from source) release build app hangs on startup (Linux)

### ISSUE THREAD

**Issue by monomere** [modrinth/code#3038]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.9.0?

### What operating systems are you seeing the problem on?

Linux

### Describe the bug

The application hangs on launch (no logs, no window, hangs almost immediately). `pnpm tauri dev` works like expected!

### Steps to reproduce

1. Checkout commit b7f514c6cc1c51a364c850b262c46dea8e2109ab (current HEAD)
2. `cd apps/app && pnpm i && pnpm build`
3. `cd ../.. && target/release/ModrinthApp`

### Additional context

Arch linux, recently updated. Launching with `lldb` and `^C`-ing stops at `poll` in glib, it seems like there's some async issue :(

Not a "fresh" install, I've launched the app previous. Might be related to #3036, but I dunno.

**Comment by Geometrically** [comment]
This ix fixed in the latest commit
