### ISSUE TITLE
Suggestion to Add Server Creation and Hosting Feature

### ISSUE THREAD

**Issue by DipCrai** [modrinth/code#3048]
### Please confirm the following.

- [ ] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [ ] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

App

### Describe the solution you'd like

Hello, Modrinth Team!

My name is DipCrai, and I am an active user of your website. Recently, while browsing your homepage, I came up with an idea that I would like to suggest.

It would be great if you could add a feature in the Modrinth launcher that allows users to create and host Minecraft servers directly on their own computers. A key feature would be the ability to choose the server core, game version, and add plugins to the created server.

Such a feature would simplify the process of launching servers for both beginners and experienced players. It would also allow users to set up their servers according to their preferences without leaving the launcher, while integrating the ability to interact with your catalog of mods and plugins.

I would appreciate it if you could consider this idea or at least provide feedback on it.

Thank you for your attention and for the great work you do!

Best regards,
DipCrai

**Comment by glitchy-sk8k9** [comment]
feather moment
