### ISSUE TITLE
Cannot log into the Modrinth windows desktop app with new account, captcha error

### ISSUE THREAD

**Issue by dfgshdsfh** [modrinth/code#3053]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Modrinth App v0.8.9

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

I am unable to log into my new modrinth account through the windows desktop app.
 
 - I created my first modrinth account through the website. I used a fastmail masked email just for modrinth, like I do with every website, I mention this because rarely some websites hate this.
 - I verified the email address, and successfully logged into the website.
 - Shortly (a few minutes) after I downloaded the windows desktop app, and attempted to sign in the credentials I had generated. 
 - The cloudflare captcha area automatically resolved to "Success!" on it's own without my interaction. There was no puzzle that appeared.
 - When I clicked "Login", I received the following error:
>"An error occurred
>Error: Failed to login with error Captcha Error. Try resubmitting the form."

![Image](https://github.com/user-attachments/assets/6fbc1f98-8020-463b-a3ec-ec37493398cc)

 - Closing and restarting the app did not resolve the error.
 - Logging into the website works fine
 - I triple checked I was using the correct credentials, trying both username and email.
 - After the initial capture error, clicking "Login" again causes the cloudflare captcha box to make a spin/waiting animation for a second, which then turns back into a checkmark with "Success!"
 - 45 minutes later the error persists.

Other issues noticed, but don't seem relevant to the above problem:
1. After getting the above error, clicking "Close" does nothing, though the overlay can still be dismissed by clicking in the blurred out areas surrounding it.
2. After leaving the sign overlay once, trying to sign in again results in the captcha area remaining blank
![Image](https://github.com/user-attachments/assets/123569d6-d19d-41fa-83af-fc9f631fcf1f)

OS edition: Windows 11 Pro
Version: 23H2
OS build: 22631.4602
Experience: Windows Feature Experience Pack 1000.22700.1055.0

**Comment by dfgshdsfh** [comment]
After more searching, I found this: https://github.com/modrinth/code/issues/1163#issuecomment-2494137663

Is this still relevant? Has logging into the app really been broken for months?

**Comment by QarthO** [comment]
I had this issue, and it only happened when I was on a specific vpn ip. cycling my vpn's ip fix it. my guess is cloudflare blacklisted the ip? idk tbh. but no issue since

**Comment by Geometrically** [comment]
Fixed

**Comment by dfgshdsfh** [comment]
Can confirm, fixed as of the Modrinth App 0.9.0 update. Thank you!
