### ISSUE TITLE
Allow reverting to the old UI

### ISSUE THREAD

**Issue by AltoidDev** [modrinth/code#3070]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [x] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

App

### Is your suggested feature related to a problem? Please describe.

We should be able to revert to the old UI. Not only does the new UI completely change the location of most functions, in most cases making them significantly harder to find, but this was clearly done just to force ads down our throats. If this change really was just to "streamline" the UI, then there would be no reason to stop us from going back to the previous version.

### Describe the solution you'd like

Add an option in the app's settings that allows users to revert to the old UI from before Modrinth+ was released.

### Additional context

![Image](https://github.com/user-attachments/assets/d4bd2736-1e98-4006-9194-193dd0978443)

**Comment by KonerDev** [comment]
Yes please, this new UI looks terrible. I always preferred the Modrinth app over other launchers because of its excellent design, but since the latest update I'm really dissatisfied.

**Comment by Geometrically** [comment]
Not planned, if you have UI feedback feel free to join our discord
