### ISSUE TITLE
Don't display ads in Home screen of the app

### ISSUE THREAD

**Issue by Andre601** [modrinth/code#3086]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [x] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### Is your suggested feature related to a problem? Please describe.

Maybe privacy reasons (not wanting to be "tracked" via the ad network)?

### Describe the solution you'd like

Simply don't have ads displayed on the Home screen of the app (The one depicting your instances).

### Describe alternatives you've considered

Not using the launcher or making a fork that removes the ads. Both aren't ideal.

### Additional context

It makes no real sense for an app to display ads at the home screen. It's fine for when browsing projects to add, but for a home screen, it just feels wrong.
Imagine Jetbrains blatantly displaying ads on the sitre while you're working on a project. It wouldn't be right, and so is this design decision.
I understand that you want to be sustainable, but this just goes too far honestly.

**Comment by mesren** [comment]
Modrinth uses ads to create an income for what they do, as everything isn't free. To the average user, Modrinth is free. But, the developers pay for their work using monetization.

**Comment by Andre601** [comment]
See my point at the end:

> I understand that you want to be sustainable, but this just goes too far honestly.

I know they need money to sustain themself. But having ads display in a place where you wouldn't expect them is not great, especially if it is from a notoriosly bad ad-company (Adsense which the ad-provider Modrinth uses relies on) that loves to collect your data on everything...
There are limits for where ads should be, and one such limit (at least for me) is to have them shown in the very first place you see when opening the app.

**Comment by Geometrically** [comment]
You can disable the sidebar which disables ads in the home screen & library pages
