### ISSUE TITLE
Update Modpack (not just mods)

### ISSUE THREAD

**Issue by DovydasTEDS** [modrinth/code#328]
### Is your suggested enhancement related to a problem? Please describe.

I want to be able to update my modpack instead of deleting it and installing it again for the latest version.

### Describe the solution you'd like

An update button?

### Additional context

Most launchers have this, such as prism (click on the modpack, settings, modrinth, update pack)

**Comment by Madis0** [comment]
The button seems to exist now as of 0.4.0, if your modpack is outdated.
