### ISSUE TITLE
Can't Download Modpack

### ISSUE THREAD

**Issue by yunus-cakir** [modrinth/code#332]
### Describe the bug

I can't download modpack from modrinth.
I made it with prism launcher and it works perfectly but modrinth

![image](https://github.com/modrinth/theseus/assets/83448525/4177948d-99ca-4c21-b70a-0d31c9db75ca)

**Comment by ElectricplaysGaming** [comment]
Same error here.

**Comment by CodexAdrian** [comment]
Fixed in #350
