### ISSUE TITLE
When making a modpack X won't work

### ISSUE THREAD

**Issue by Missile-maker** [modrinth/code#333]
### Describe the bug

When I was making a modpack I was searching for mods and the X button on the left of the mod's search bar isn't deleting the text . I am guessing it is also happening to other search bars

### Steps to reproduce

1. Make A Modpack
2. Search for a mod
3. Leave name in search bar
4. Click X on the left side of search bar

### Expected behavior

I was expecting the text to delete when I clicked the X

**Comment by CodexAdrian** [comment]
Fixed in #350
