### ISSUE TITLE
Can't Create 1.12.2 Forge Instances

### ISSUE THREAD

**Issue by gungamer0012** [modrinth/code#337]
### Describe the bug

I can't make my own 1.12.2 forge packs. I just end up getting an error....
![image](https://github.com/modrinth/theseus/assets/97538923/1eb6adcb-7bf9-4d75-8539-df89caa51e41)

### Steps to reproduce

Create a new instance for 1.12.2 Forge and name it what ever you want.

### Expected behavior

I'm supposed to just make a new instance and create my own modpack for 1.12.2 Forge.

**Comment by Geometrically** [comment]
duplicate
