### ISSUE TITLE
MacOs Big Sur version 11.7.7

### ISSUE THREAD

**Issue by WolfIsFluffy** [modrinth/code#338]
### Describe the bug

This may not be a real bug but if you launch modrinth on macOS Big Sur version 11.7.7 you will get this message "Check with the developer to make sure Modrinth App works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS." 

### Steps to reproduce

1. Run Modrinth App ver. 0.2.2 (MacOs)
2. then you get the error.

### Expected behavior

Failure to launch the app and you will get this pop up "Check with the developer to make sure Modrinth App works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS."
<img width="262" alt="Screen Shot 2023-07-16 at 12 26 41 PM" src="https://github.com/modrinth/theseus/assets/116476089/b3178a47-af75-4fa3-a4ed-be7d4c8731df">

**Comment by Geometrically** [comment]
duplicate
