### ISSUE TITLE
Mod combination warnings on install

### ISSUE THREAD

**Issue by otDan** [modrinth/code#340]
### Is your suggested enhancement related to a problem? Please describe.

There is a lot of times where you are just making a pack, where there are known mod combinations and versions that do not let minecraft boot. 

### Describe the solution you'd like

There could be a way to gather data on which mod combinations do not boot when combined, this way you can warn someone when installing a mod with something like "this mod combination has usually not booted or encountered issues". I know it's something nieche since most people would be playing the packs and not creating them, but I think it would improve modpack creation a lot. 

### Describe alternatives you've considered

Looking at reported issues on mod github pages, but that takes time, especially with more complex modpacks.

**Comment by CodexAdrian** [comment]
This is not something the Modrinth app will do

**Comment by CodexAdrian** [comment]
This is not something the Modrinth app will do
