### ISSUE TITLE
Bukkit, BungeeCord and Spigot icons are broken in Modrinth app mod search for modpack

### ISSUE THREAD

**Issue by NikSneMC** [modrinth/code#352]
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/88781618/49226cac-acdb-453f-be43-7c8915568faa)

### Steps to reproduce

1. Select any modpack that you have
2. Open "Mods" tab
3. Press "Add content" button
4. Find any project that have Bukkit, BungeeCord or Spigot version (example - Packet Auth)

**Comment by thesuzerain** [comment]
Thanks for the report!
Does this happen consistently- is it still happening? 

If so, can you please send me a copy of your tags.json file, which is either in:
-windows =>  C:\Users\{username}\AppData\Roaming\com.modrinth.theseus\caches\metadata
- mac => /Users/{username}/Library/Application Support/com.modrinth.theseus/caches/metadata
- linux => /.config/com.modrinth.theseus/caches/metadata

(I am particularly interested in the bukkit/bungeecord/spigot snippets of it)

**Comment by Geometrically** [comment]
duplicate

**Comment by NikSneMC** [comment]
> Thanks for the report! Does this happen consistently- is it still happening?
> 
> If so, can you please send me a copy of your tags.json file, which is either in: -windows => C:\Users{username}\AppData\Roaming\com.modrinth.theseus\caches\metadata
> 
> * mac => /Users/{username}/Library/Application Support/com.modrinth.theseus/caches/metadata
> * linux => /.config/com.modrinth.theseus/caches/metadata
> 
> (I am particularly interested in the bukkit/bungeecord/spigot snippets of it)

[tags.json.txt](https://github.com/modrinth/theseus/files/12706141/tags.json.txt)

GitHub doesn't allow sending of .json files, so I've added .txt

(Yeah, this error has been fixed, but now it's there again)
