### ISSUE TITLE
Fabric on Quilt

### ISSUE THREAD

**Issue by Edeec0** [modrinth/code#358]
### Is your suggested enhancement related to a problem? Please describe.

right now you can only install Quilt specified mods from the launcher if you have Quilt as your modloader.

### Describe the solution you'd like

Add an (show fabric mods) and that will pop up some warning and then you press accept.

### Describe alternatives you've considered

Just have fabric mods there already

### Additional context

i wanna use Lambda better grass and effective and those mods are only on quilt so it would make my life 86% easier otherwise il just continue using fabric modloader

**Comment by Fnige** [comment]
![image](https://github.com/modrinth/theseus/assets/35159947/41c0fcdc-8444-44b5-a83c-981ca0596788)

**Comment by Edeec0** [comment]
oh thanks
