### ISSUE TITLE
Can´t use instances(on windows)

### ISSUE THREAD

**Issue by Unbkannter** [modrinth/code#368]

**Comment by thesuzerain** [comment]
We need a little more information than this. Please resubmit the issue and where it asks for reproduction steps, etc, please fill those out.
More information that would be good to have
- your computer version
- what the details of the instance you're trying to load is
- what is actually happening: are you getting an error (and if so ,what error?)? Are they crashing (and if so, what is the crash log)? Is nothing responding? 

Thanks!
