### ISSUE TITLE
The "You already have this modpack installed" dialog doesn't close when clicking "Install"

### ISSUE THREAD

**Issue by ghost** [modrinth/code#390]
### Describe the bug

When you have the modpack already installed and are trying to install another instance of it, the app will warn you; if you choose to install anyway, the warning won't go away until you "X" it.

### Steps to reproduce

1. Create an instance of a modpack
2. Try to create an instance of the same modpack again
3. Click "install"

### Expected behavior

The dialog goes away the moment you press "install"

### Additional context

Would be nice to have a "never ask again" checkbox either/both in this dialog and in the settings for this warning.

**Comment by thesuzerain** [comment]
Should be fixed with 0.4
