### ISSUE TITLE
Exaroton ads are still shown

### ISSUE THREAD

**Issue by osfanbuff63** [modrinth/code#391]
### Describe the bug

In the Modrinth App, Exaroton ads are still shown despite Modrinth having a new ad deal now.

### Steps to reproduce

1. Open the Modrinth App and click on the search button.
2. See that the ad shown is for Exaroton, not Matrix, the new ad partner.

### Expected behavior

For Matrix ads to be shown instead of Exaroton.

**Comment by Geometrically** [comment]
not a bug
