### ISSUE TITLE
Update Mod Button Not Changing When Update is Complete

### ISSUE THREAD

**Issue by goldnnnn** [modrinth/code#394]
### Describe the bug

When I try to update a mod it goes to the modrinth logo and it doesn't change back and I have to restart the modrinth app with task manager for the button to update

### Steps to reproduce

1. open modrinth app
2. find outdated mod
3. click the icon to update it
4. wait as long as you want (it wont change)
6. restart modrinth app
7. look at outdated mod (it may or may not of updated)

### Expected behavior

I think its meant to change to the normal icon

### Additional context

![image](https://github.com/modrinth/theseus/assets/81842072/43176f87-e68d-4bd5-9e6b-e2e446ec5291)
this is what happens, it wont change back

**Comment by MeeniMc** [comment]
This also crashes the launcher as discussed in duplicate issue #398

**Comment by thesuzerain** [comment]
Fixed with #381 for next update
