### ISSUE TITLE
Forge 1.12.2 instance not starting

### ISSUE THREAD

**Issue by KPaXz** [modrinth/code#402]
### Describe the bug

created a simple forge instance of 1.12.2 and pressed play. the play button changes breifly then switches back to the play button. no forge 1.12.2 instance starts

### Steps to reproduce

1. create a forge 1.12.2 instance
2. press play
3. press play again
4. see that 1.12.2 wont start

### Expected behavior

i would expect forge 1.12.2 to start running but it doesnt

### Additional context

It seems any forge instances below 1.16.5 wont work

**Comment by Geometrically** [comment]
fixed
