### ISSUE TITLE
For Linux users, distribute the app as a Flatppak on Flathub, instead of just Debs and/or AppImages.

### ISSUE THREAD

**Issue by MagmaSlime123** [modrinth/code#423]
### Is your suggested enhancement related to a problem? Please describe.

Linux has WAY too many ways of packaging apps. Flatpaks are one of the few big universal package types that would be best suited for the app to be distributed as.

### Describe the solution you'd like

Distribute the app via Flathub using Flatpaks. Prism distributes on both COPR and Flathub, and probably other places as well. (If you don't know what COPR is, ask @devin_real)

### Describe alternatives you've considered

N/A?

### Additional context

N/A.

**Comment by TheoCGaming** [comment]
there could also be an AUR version of the launcher similar to how Mojang and Prism do it.

**Comment by getchoo** [comment]
a current universal solution is available [here](https://github.com/getchoo/nix-exprs/blob/main/pkgs/theseus.nix) using nix as a kind of workaround. i plan on upstreaming it into nixpkgs itself once a stable release is made so it's easier to access

i'll look into flatpak as well soon

**Comment by MagmaBro123** [comment]
I doubt Nix packages are useable on other non-NixOS distros. This is why I recommended Flatpaks, as they usually respect more tings like user themes.

**Comment by MagmaBro123** [comment]
> a current universal solution is available [here](https://github.com/getchoo/nix-exprs/blob/main/pkgs/theseus.nix) using nix as a kind of workaround. i plan on upstreaming it into nixpkgs itself once a stable release is made so it's easier to access
> 
> i'll look into flatpak as well soon

I doubt Nix packages are useable on other non-NixOS distros. This is why I recommended Flatpaks, as they usually respect more tings like user themes.

**Comment by Fnige** [comment]
> I doubt Nix packages are useable on non-NixOS distros.

[Actually you can use nix on non-nixos distros](https://nixos.org/download#)

**Comment by getchoo** [comment]
> I doubt Nix packages are useable on non-NixOS distros. 

they are

> This is why I recommended Flatpaks, as they usually respect more things like user themes and such, unlike Snaps (ew, gross), Debs, and AppImages.

nix packages do respect themes, along with debs...though i don't think any themes will really work given that theseus isn't really a regular gtk app, and more similar to electron than anything

> Also, they're isolated from the rest of your system, containerized. I prefer both universal-ity and security.

nix is also containerized similar to flatpak, meaning it can vendor any version of dependencies if required. for security i assume you're talking about the built in sandboxing, which the current nix package does lack but can have - though i'd argue right now this is pretty ok since none of the other options have it either

> Having a single Flatpak on Flathub is better then 50 packages on 50 different places, imo.

100%, universal packages are the way to go, especially for upstream suppor. it is important to remember nix is also one of these solutions though - it even works on mac :p

**Comment by MagmaBro123** [comment]
> > I doubt Nix packages are useable on non-NixOS distros.
> 
> they are
> 
> > This is why I recommended Flatpaks, as they usually respect more things like user themes and such, unlike Snaps (ew, gross), Debs, and AppImages.
> 
> nix packages do respect themes, along with debs...though i don't think any themes will really work given that theseus isn't really a regular gtk app, and more similar to electron than anything
> 
> > Also, they're isolated from the rest of your system, containerized. I prefer both universal-ity and security.
> 
> nix is also containerized similar to flatpak, meaning it can vendor any version of dependencies if required. for security i assume you're talking about the built in sandboxing, which the current nix package does lack but can have - though i'd argue right now this is pretty ok since none of the other options have it either
> 
> > Having a single Flatpak on Flathub is better then 50 packages on 50 different places, imo.
> 
> 100%, universal packages are the way to go, especially for upstream suppor. it is important to remember nix is also one of these solutions though - it even works on mac :p

I plan on moving to Fedora Gnome at some point next year, so I've been trying to get into the basics of Linux stuff. Didn't know Nix was that universal, huh. Most people, including Devin, hate Snaps, afaict (as far as I can tell).

**Comment by intergrav** [comment]
You may want to close this as it's currently being discussed in more detail in https://github.com/modrinth/theseus/issues/497, up to you though

**Comment by mirai-toto** [comment]
I know it has been a year since this issue was closed, but I am curious to know why Flatpak is not officially supported. Is it due to a technical issue or a lack of resources?
