### ISSUE TITLE
can't launch any instances in v0.3.1

### ISSUE THREAD

**Issue by JustLetterV** [modrinth/code#426]
### Describe the bug

When I'm trying to launch instance it doesn't launch and I just receive serialization error. Repairing instance doesn't help either.
![](https://github.com/modrinth/theseus/assets/75657829/0971240e-99da-4e05-8250-c1eeec12706b)
![](https://github.com/modrinth/theseus/assets/75657829/543b91e8-dc04-44e6-a408-640f5d462d17)

### Steps to reproduce

1. Update app version to 0.3.1
2. Try to launch instance (doesn't matter when created)
3. get error like shown in image above

### Additional context
os: windows 11
app version: 0.3.1

**Comment by thesuzerain** [comment]
Can you try logging out then logging back in again (with your minecraft account in the top left)? Authentication changed slightly in this patch
