### ISSUE TITLE
[Introduction] Space where logo should be is a black box

### ISSUE THREAD

**Issue by Minenash** [modrinth/code#427]
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/12193049/6ea1e096-9b2e-4132-95e9-703b05bede10)

### Steps to reproduce

1. Start app after updaing

### Expected behavior

The logo to be there

### Additional context

- Windows 10
- Updated from alpha 3.0

**Comment by Stoutscientist** [comment]
Something I did notice is that it will appear after hitting get started, see attached video

https://github.com/modrinth/theseus/assets/90054049/c53a4020-2a67-4141-9e92-1ddfe6684e5d

**Comment by wlad26** [comment]
Can confirm, happens even for clean install and latest version ( v0.6.3 )
![explorer_izYkofc6L7](https://github.com/modrinth/theseus/assets/65756919/e0dc8377-d650-4bbe-bf78-a3538bd46bbd)

**Comment by wlad26** [comment]
Also Google Login and Prism Launcher icons have same issue:
![WindowsSandboxClient_fKxhTVcM5l](https://github.com/modrinth/theseus/assets/65756919/1f4c4c77-1505-4719-b225-72fafab11600)
![WindowsSandboxClient_4K8xjoKN5i](https://github.com/modrinth/theseus/assets/65756919/31373a3a-5daf-458d-9132-06ca7e3ebc61)

**Comment by Minenash** [comment]
On-boarding is no longer a part of the app
