### ISSUE TITLE
[Onboarding] Move exit button to inside the tutorial card

### ISSUE THREAD

**Issue by Minenash** [modrinth/code#431]
### Is your suggested enhancement related to a problem? Please describe.

The exit button being above the new instance button is very unintuitive. I know step 1 mentions it, but it still took the second read, and honestly being the first step in the "learn how to use" and without it pointing functionality out, I feel like a lot of people won't read it and therefor not see it.

It also doesn't help that there's no tooltips for sidebar (when compact at least), so if you missed the statement in step 1, It's not obvious what it does

### Describe the solution you'd like

Move the exit action to inside the card where all the other tutorial actions are

**Comment by thesuzerain** [comment]
This should be fixed as of the latest update!
