### ISSUE TITLE
Extremely High CPU, Disk, and Memory Usage when importing instances

### ISSUE THREAD

**Issue by Logboy2000** [modrinth/code#442]
### Describe the bug

I imported 2 instances from Prism Launcher but the importing of instances doesnt limit usage so it makes my computer unusable

### Steps to reproduce

1. Import a somewhat large instance into the launcher

### Expected behavior

limit the usage of the program so i doesn't break your computer

### Additional context

![image](https://github.com/modrinth/theseus/assets/72185335/74752d96-b292-40f1-8e49-8bad9744537f)

**Comment by Logboy2000** [comment]
UPDATE:
The app crashed after about thirty minutes of this and now refuses to open leaving me on this screen indefinitely
![image](https://github.com/modrinth/theseus/assets/72185335/d8f37367-9ed6-43d6-bec7-ea93af08c02a)

**Comment by thesuzerain** [comment]
Are these forge instances by any chance?
The crash after is strange and worrying... if you delete the profiles that you were importing from com.modrinth.theseus/profiles does it allow it to open?
