### ISSUE TITLE
Add an option to skip the intro animation

### ISSUE THREAD

**Issue by Adamiok** [modrinth/code#443]
### Is your suggested enhancement related to a problem? Please describe.

When I am trying to start minecraft using modrinth, but I have to watch the intro animation.

### Describe the solution you'd like

Add an option in the settings (off be default) to skip the intro animation.

**Comment by triphora** [comment]
It only plays on first open, so there is not much need to do this.

**Comment by Felix14-v2** [comment]
> It only plays on first open, so there is not much need to do this.

Wait, it plays not on each launch? I've seen it at least three times.

**Comment by Geometrically** [comment]
that's a bug and we're fixing it
