### ISSUE TITLE
.mrpack icons do not load properly

### ISSUE THREAD

**Issue by thesuzerain** [modrinth/code#455]
### Describe the bug

When installing a pack via .mrpack, even if an icon is included ,the profile will show to have no icon.

### Steps to reproduce

1. Export a pack with an icon to a .mrpack
2. Import it back in

### Expected behavior

If an icon.png is included in a .mrpack's overrides, and no other icon is forthcoming, we expect it to be used. Perhaps some other methods too?

### Additional context

https://github.com/modrinth/theseus/issues/439#issuecomment-1665592895

**Comment by triphora** [comment]
There is no way to add icons in the mrpack specification. See modrinth/.github#44
