### ISSUE TITLE
Add a "Skip Tutorial" button on first launch of application

### ISSUE THREAD

**Issue by TheSenate39** [modrinth/code#471]
### Is your suggested enhancement related to a problem? Please describe.

Updating the app acts like the app is a brand-new program on your machine (at least for Win. 10), and will force you to comply with the 9-step tutorial before proceeding.

### Describe the solution you'd like

In addition to the "Back" and "Next" options, a "Skip Tutorial" button added somewhere in the tutorial information block.

**Comment by srnyx** [comment]
I think this exists already? When I started the tutorial, none of the buttons were working and I couldn't even complete the tutorial. The only button that worked as like an exit-looking button (arrow with a door). When I clicked it, the tutorial ended and I could use the app like normal.

**Comment by TheSenate39** [comment]
@srnyx Didn't see that on my end; I'll look for it when next applicable.

**Comment by CodexAdrian** [comment]
Already exists but will move it to a more prominent spot
