### ISSUE TITLE
Additional Files are not Installed

### ISSUE THREAD

**Issue by yurisuika** [modrinth/code#478]
### Describe the bug

Under each release, Modrinth offers the ability to upload additional files.

In Theseus, these additional files are displayed on the mod page upon search, each with the "Install" button. However, upon using that function, it simply installs the main file. As such, these additional files cannot be installed.

This is as of version 4.0.0.

### Steps to reproduce

1. Search for mod.
2. Go to mod version.
3. Click "Install" button on additional file.
4. Main file is installed, additional file is not.

### Expected behavior

Additional file is installed.

**Comment by triphora** [comment]
Intentional. Additional files are meant to be for things that very few people will actually download, like sources jars. This behavior is the same as how every other launcher handles them.
