### ISSUE TITLE
Last step on tutorial should have back button

### ISSUE THREAD

**Issue by JustLetterV** [modrinth/code#484]
### Is your suggested enhancement related to a problem? Please describe.

Yes, users can't go back in tutorial if they are on the last tutorial step.

### Describe the solution you'd like

The last step "Enter the Modrinth App" would have back button like all other steps in the tutorial.

### Additional context

Last step in tutorial doesn't have back button:
![](https://github.com/modrinth/theseus/assets/75657829/1ea12f0b-4c44-4c10-913b-53b2c063d7a1)
Other steps have back button:
![](https://github.com/modrinth/theseus/assets/75657829/90b73e54-953e-47de-8f5d-6331546ea7e4)

**Comment by Minenash** [comment]
On-boarding has been removed
