### ISSUE TITLE
Background blur and darkening doesn't apply to window controls

### ISSUE THREAD

**Issue by JustLetterV** [modrinth/code#487]
### Describe the bug

Title
![](https://github.com/modrinth/theseus/assets/75657829/545d3a71-0332-4ab3-b528-017fdf98d7bb)

### Steps to reproduce

1. Go to instance settings
2. Click the "Edit versions" button
3. Look at the top right corner (:

### Expected behavior

Window controls should (probably?) be darkened and blurred when everything else is.

### Additional context

Windows 11
Modrinth app v0.4.0

**Comment by Minenash** [comment]
Not a bug
