### ISSUE TITLE
Modrinth cannot be opened because of a problem (MacOS Big Sur 11.7)

### ISSUE THREAD

**Issue by maxeatbug** [modrinth/code#496]
### Describe the bug

The modrinth app has had this issue in every version since alpha, I will attach a log below 

Process:               Modrinth App [2894]
Path:                  /Applications/Modrinth App.app/Contents/MacOS/Modrinth App
Identifier:            com.modrinth.theseus
Version:               0.5.0 (20230806.010717)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Modrinth App [2894]
User ID:               502

Date/Time:             2023-08-05 23:06:48.892 -0500
OS Version:            macOS 11.7.8 (20G1351)
Report Version:        12
Anonymous UUID:        C93D1509-5189-0194-F8CE-CB184468550F

Sleep/Wake UUID:       B9498393-460C-4876-8F73-38FBC9857247

Time Awake Since Boot: 22000 seconds
Time Since Wake:       260 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Applications/Modrinth App.app/Contents/MacOS/Modrinth App
  Reason: no suitable image found.  Did find:
	/usr/local/opt/xz/lib/liblzma.5.dylib: code signature in (/usr/local/opt/xz/lib/liblzma.5.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

Binary Images:
       0x105065000 -        0x105bccfff +com.modrinth.theseus (0.5.0 - 20230806.010717) <027E5946-C1C6-38F1-94E4-3DBB64FBA79E> /Applications/Modrinth App.app/Contents/MacOS/Modrinth App
       0x114e53000 -        0x114eeefff  dyld (852.2) <4FF2ABFD-E712-356A-9458-F9914B67D65C> /usr/lib/dyld
    0x7fff206bb000 -     0x7fff206f4fff  libobjc.A.dylib (824.1) <A0961DED-3477-3856-A6BC-CFE2475CB2F4> /usr/lib/libobjc.A.dylib
    0x7fff2089b000 -     0x7fff20d38fff  com.apple.CoreFoundation (6.9 - 1778.105) <B4B8042A-9415-3F26-91AC-735C968B0D95> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff21360000 -     0x7fff213ddfff  com.apple.SystemConfiguration (1.20 - 1.20) <D59BEA1F-BD5D-383A-8977-64F5B72F16C4> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff2164c000 -     0x7fff219aafff  com.apple.Foundation (6.9 - 1778.105) <4F4709DD-C198-3AA1-86A0-71D2F2FDD65D> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff303a2000 -     0x7fff303a2fff  com.apple.CoreServices (1122.45 - 1122.45) <C3145415-E2CC-355B-9400-047C46FF1044> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices

Model: MacBookPro11,3, BootROM 478.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.5 GHz, 16 GB, SMC 2.19f12
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Graphics: kHW_NVidiaGeForceGTX750MItem, NVIDIA GeForce GT 750M, spdisplays_pcie_device, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.11)
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

### Steps to reproduce

Open the App (macOS 11.7 Big Sur, Mid-2014 MacBook Pro)

### Expected behavior

The application to open.

**Comment by Geometrically** [comment]
Fixed in 0.8.0
