### ISSUE TITLE
[UI] add tooltips to vertical navbar

### ISSUE THREAD

**Issue by deniz-blue** [modrinth/code#507]
### Is your suggested enhancement related to a problem? Please describe.

This is just a minor QoL change but i think it could help with accessibility

### Describe the solution you'd like

Add tooltips with the page name on hover, like this:

![image](https://github.com/modrinth/theseus/assets/43997085/3d8abd11-025e-4bdc-84e5-17bc1e2e1b12)

### Describe alternatives you've considered

html native tooltip (`<a title="" />` etc)

**Comment by thesuzerain** [comment]
these should exist as of the latest update

![image](https://github.com/modrinth/theseus/assets/10837000/c8aefabe-8958-4137-8f1a-a4777467ad58)

**Comment by TheAlan404** [comment]
why is it on top of the buttons..?
