### ISSUE TITLE
[UI] search page: move search filters... to filters panel?

### ISSUE THREAD

**Issue by TheAlan404** [modrinth/code#511]
### Describe the solution you'd like

i mean it makes sense and it also tidies the search bar and makes it larger but idk if this is a great idea

![image](https://github.com/modrinth/theseus/assets/43997085/f6b41c8f-ae72-4617-a5f1-fe40809c87aa)

**Comment by Poopooracoocoo** [comment]
![image](https://github.com/modrinth/theseus/assets/51363864/7a6f8c44-b5ce-4376-8962-7fd5753fc547)


But they're not search filters. One is a sorting option and the other is a view option
