### ISSUE TITLE
The buttons are not in the right size in some places, and sometimes the text goes outside of the buttons.

### ISSUE THREAD

**Issue by PowerRubik** [modrinth/code#514]
### Describe the bug

<img width="173" alt="Screenshot 2023-08-06 at 13 39 06" src="https://github.com/modrinth/theseus/assets/126591243/aa1acc6e-c458-41eb-b337-f57c81dedb6c">
<img width="202" alt="Screenshot 2023-08-06 at 13 39 03" src="https://github.com/modrinth/theseus/assets/126591243/06321902-963a-4769-b17f-07f30a15616d">
<img width="256" alt="Screenshot 2023-08-06 at 13 38 58" src="https://github.com/modrinth/theseus/assets/126591243/a5d3c367-8b6d-4c25-ad21-14f52dd1c4f7">
<img width="222" alt="Screenshot 2023-08-06 at 13 38 25" src="https://github.com/modrinth/theseus/assets/126591243/e84dc36b-9726-4c1d-ac97-515fc13c2c7b">
<img width="344" alt="Screenshot 2023-08-06 at 13 38 11" src="https://github.com/modrinth/theseus/assets/126591243/f00e9117-0643-4d5e-9adc-7608b6886437">
<img width="398" alt="Screenshot 2023-08-06 at 13 37 47" src="https://github.com/modrinth/theseus/assets/126591243/faac3541-e659-40b9-83ce-f1f4ba7158e0">
<img width="712" alt="Screenshot 2023-08-06 at 13 37 19" src="https://github.com/modrinth/theseus/assets/126591243/df3153f5-eb98-4f13-a525-2bfc48e5056e">

### Additional context

**Comment by thesuzerain** [comment]
Can you please add a little more information about your system? 
Mac, Windows, what version of those, what browser you use, etc

**Comment by Minenash** [comment]
There no longer is onboarding
