### ISSUE TITLE
First startup sound is very loud

### ISSUE THREAD

**Issue by jadeposting** [modrinth/code#515]
### Describe the solution you'd like

Lower the volume of the first startup sound

**Comment by CyanideX** [comment]
Having a startup sound is a very poor design choice. Remember they days when websites had music playing? 😝

**Comment by szernex** [comment]
Please remove this completely. Absolutely unprofessional. It's bad enough that many games still blare some crappy sounds at full volume when you first start them, don't need this in a Minecraft Launcher.

**Comment by Minenash** [comment]
Was removed
