### ISSUE TITLE
[AppImage] Most buttons related to the web browser, file manager and copying don't work.

### ISSUE THREAD

**Issue by callyral** [modrinth/code#520]
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/125226346/f6f5b1dc-488b-4ee5-ad92-0da0472374c4)
_Buttons that do not do anything have been circled._

![image](https://github.com/modrinth/theseus/assets/125226346/9a43e2c0-9fbe-41a3-9b9d-a17842380dc2)
_None of the buttons in this image work._

![image](https://github.com/modrinth/theseus/assets/125226346/89b06fd9-aa25-4702-a68f-7cdc579277ee)
_The circled button doesn't open the file manager at the instance folder._

By "doesn't work" I mean that I'm able to click the button but nothing happens.

### For the first image:
1. Go to a modpack page, I used Cobblemon as an example.
2. Left-click the "Site" button: it doesn't work.
3. Right-click either button and a context menu pops up.
4. The "Open in Modrinth" context menu button doesn't work.
### For the second image:
1. Go to an installed instance with mods.
2. Left-click the folder icon in the mod list, it doesn't work.
3. None of the context menu options do anything.
### For the third image:
1. Go to any installed instance.
2. Click the folder button ("Open instance folder").
3. It doesn't open the instance folder.

### Expected behavior

For the buttons do as described in the interface, such as opening the web browser at the mod's page, or copying a file path.

### Additional context

I am on Artix Linux on KDE Plasma Wayland. I am using the AppImage.

Unlike the Modrinth App, other programs (including AppImages) are able to open the web browser, file manager or copy to the clipboard and the `xdg-open` command works on my system.

I'm also sorry if I didn't describe the issue very well, I'm not used to bug reporting and English is not my first language.

**Comment by callyral** [comment]
I also had the same issue described in #479 which seems to be related

**Comment by terzag** [comment]
Same for me on Xubuntu (Xfce) 23.04 with the AppImage.

**Comment by callyral** [comment]
Adding onto this, it appears to be an issue with the AppImage.

I'm on Artix (Arch-based) so I had to extract the .deb file (`ar x modrinth_file.deb`), upon acquiring the binary (`modrinth-app`) and running it, all those worked. 

The instance folders opened correctly and so did the web browser when necessary, the file picker (when selecting 'from file' in instance creation) also looked normal, unlike in the AppImage (#480)

**Comment by mxruben** [comment]
Happens for me on Windows 11 as well

**Comment by Boxersteavee** [comment]
also doesn't work for OAuth options on the login page, and the button next to the text for microsoft.com/link (popup with code shows, button for opening link doesn't work). Ubuntu 23.04

**Comment by FairyTail2000** [comment]
Fot those interested in the actual issue: kde-open5: symbol lookup error: /usr/lib/libproxy/libpxbackend-1.0.so: undefined symbol: g_strv_builder_unref

My system is:
Manjaro
x86_64
KDE 5
App version: v0.6.3

That's what is printed onto the console on my system. If you run the AppImage file on the console, you will be able to see this error after pressing the "Open Folder" Button for your Minecraft instance.

This error indicates a version mismatch between my own installed libpxbackend-1.0.so

It may be useful to include this library in the Appimage @thesuzerain

**Comment by DerpyPlayz18** [comment]
The app also crashes when clicking on add from file in the mods list of a pack
![image](https://github.com/modrinth/theseus/assets/80034339/f01d074f-d3be-4162-9944-a7fdc535e995)

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Fix?

**Comment by Bernasss12** [comment]
```
os: Linux 
distro: Arch Linux x86_64 
kernel: 6.8.2-arch2-1 
de: Plasma 6.0.3 
wm: KWin 
cpu: AMD Ryzen 5 5600X (12) @ 3.700GHz 
gpu: NVIDIA GeForce RTX 4080 
memory: 21342MiB / 32016MiB 
```

I just want to add that apparently linking isn't working from within the game when launched from the app.

Some examples I tested were by clicking the chat link that comes up upon taking a screenshot, the `Open Pack Folder` button in the resource pack screen and also clicking `Open in Browser` button on the `Give Feedback` screen.

Clicking `Copy to clipboard` on this last mentioned screen does seem to work.

**Comment by Yixuan2020** [comment]
```
distro: Fedora39
Kernel: 6.8.7-200.fc39.x86_64 
CPU: 12th Gen Intel i3-12100F (8) @ 4.300GHz 
DE: Plasma 5.27.11
WM: KWin
Filemanager: dolphin
```
`theseus v0.7.1`
everything clickable that opens another app is not working
![image](https://github.com/modrinth/theseus/assets/119166388/0a151a8d-71bc-4869-b992-7a012de72829)
clicking on "share" in logs makes everything white and get stuck,has to be killed via system Monitor

**Comment by Mentalgen** [comment]
For others on Arch, I was able to get the links to work by using a round-about solution. I used debtap on the .deb, and installed using pacman. It seems that installing this way makes everything work as intended

**Comment by Norbiros** [comment]
It's probably an upstream issue https://github.com/tauri-apps/tauri/issues/10617

**Comment by AW1534** [comment]
@Geometrically Can this issue be reopened? It seems to be incorrectly closed, as it still doesn't work for me. also, the tauri issue that @Norbiros previously mentioned is still open.

**Comment by AW1534** [comment]
I am again requesting this is reopened. I'm still having issues with this.
