### ISSUE TITLE
MacOS Microphone Permission Needed

### ISSUE THREAD

**Issue by DABishai** [modrinth/code#527]
### Is your suggested enhancement related to a problem? Please describe.

The simple voice chat mod and other mods which require a microphone currently do not work on mac.

### Describe the solution you'd like

If the launcher itself requests access for the microphone permissions on Mac, these mods can be actually functional. This feature has already been implemented in Prism launcher. 

### Additional context

Microphone Permission Documentation:
https://developer.apple.com/documentation/bundleresources/information_property_list/nsmicrophoneusagedescription?language=objc

Thread Discussing Microphone Permissions on Prisim:
https://github.com/PrismLauncher/PrismLauncher/issues/1327

Thread Discussing Microphone Permissions on Simple Voice Chat:
https://github.com/henkelmax/simple-voice-chat/issues/24

**Comment by 0PandaDEV** [comment]
I have the same problem, please fix this prism launcher also managed to do it
