### ISSUE TITLE
Microsoft login using codes

### ISSUE THREAD

**Issue by Ryhon0** [modrinth/code#540]
### Is your suggested enhancement related to a problem? Please describe.

Right now users have to log in to their Microsoft accounts in a window created by the launcher, which may make it more difficult than logging in from a web browser where the user may already be logged in or have a saved password and login to their Microsoft account. This issue is amplified on devices like the Steam Deck, where multi tasking is harder than on desktop.

### Describe the solution you'd like

Microsoft provides a way to authorize an application using a device code flow. The launcher would open a website in the default web browser or ask the user to open it on another device. The website asks the user to enter the code from the application. After entering the code the user would authorize the application as normal.
This allows the user to log in using saved passwords or log in using an external device.

Here's the Microsoft documentation: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code
And a C# implementation I wrote for my launcher (Also GPL3):
https://github.com/Ryhon0/MCelium/blob/main/UI/MSAPopup/MSAPopup.cs#L35
https://github.com/Ryhon0/MCelium/blob/main/Classes/API/MSA.cs#L9

### Describe alternatives you've considered

The launcher would open a regular authorization page and the callback URL would communicate with the launcher using a custom protocol URL or a local server

**Comment by thesuzerain** [comment]
The latest version (0.5.3) should use the device flow now! Thanks for the suggestion
