### ISSUE TITLE
Log file names have the file extension switched with the date

### ISSUE THREAD

**Issue by Narnianknight** [modrinth/code#547]
### Describe the bug

The log files found in `launcher_logs` are named with the format `theseus.log.YYYY-MM-DD`.

### Steps to reproduce

1. Do whatever creates a log file (login stuff?)
2. Look at the file names in the `launcher_logs` directory

### Expected behavior

Log file names should be in the format `theseus.YYYY-MM-DD.log`. It makes more sense to have a uniform file extension.

**Comment by thesuzerain** [comment]
There isn't really all that nice of a way to do it like this, considering we are currently using the tracing_appender crate for this. The rolling appender appends the date to the end of the file only. I may reopen this in the future, though.
