### ISSUE TITLE
Homebrew cask for easy install on mac/linux

### ISSUE THREAD

**Issue by boldandbrad** [modrinth/code#560]
### Is your suggested enhancement related to a problem? Please describe.

No.

### Describe the solution you'd like

I'd like a [homebrew](https://brew.sh) cask created for the Theseus that would install the appropriate Modrinth app and cli version on macOS. Many other minecraft launchers and utilities are available as casks already.

This would allow someone to programmatically or automatically install Modrinth apps via scripts or command line.

### Describe alternatives you've considered

- Manual install from modrinth.com/app

### Additional context

Would make modrinth apps easier to install for users.

**Comment by getchoo** [comment]
this might be a better fit for #497

**Comment by triphora** [comment]
Closing in favor of #497
