### ISSUE TITLE
Button to remove mods from a instance 

### ISSUE THREAD

**Issue by MIfoodie** [modrinth/code#565]
### Is your suggested enhancement related to a problem? Please describe.

We can add mods easily, but I think its a problem if we can't remove them as easily.

### Describe the solution you'd like

![image](https://github.com/modrinth/theseus/assets/94649676/3434ec17-f95a-4ead-babc-366cb9c4c9d4)

A delete button or something simular here

**Comment by CodexAdrian** [comment]
You need to unlink the modpack in the options before you can edit it
