### ISSUE TITLE
Java Virtual Machine Launcher Forge

### ISSUE THREAD

**Issue by LysanderTron** [modrinth/code#568]
### Describe the bug

Works:
1.20.1
1.18.2

Doesnt:
1.12.2
1.16.5

![Untitled](https://github.com/modrinth/theseus/assets/68231960/b500d316-7cc1-456f-85c0-a25cf0ec204d)

### Steps to reproduce

1. New instance
2. Forge instance
3. Launch

### Expected behavior

To open minecraft.

**Comment by thesuzerain** [comment]
Check the instance logs. You may need to increase the amount of memory allocated to the java instance- the log of you trying to run it will say something to that effect. If they do not, can you post them here?

You can change the java settings globally in the settings or per-instance in the instance options.

I had a similar thing on my machine for forge 1.12.2 but increasing from 256->1024mb in the global settings fixed it.

**Comment by LysanderTron** [comment]
The issue was I had the memory allocated too high

**Comment by LysanderTron** [comment]
This is causing some older modpacks to be unplayable as the maximum amount of memory that can be allocated is capped at 1024mb 
[latest.log](https://github.com/modrinth/theseus/files/12336570/latest.log)
![brokey](https://github.com/modrinth/theseus/assets/68231960/7ede2055-7d1e-4299-b11c-634a69fbb44b)

The error also changes at higher allocated memory
![brokey2](https://github.com/modrinth/theseus/assets/68231960/d0393e7e-50ea-46ff-90f7-c19ce53a697f)

**Comment by thesuzerain** [comment]
Are you referring to this value? In that case the maximum value is the amount of that launcher is able to access, not hard capped at 1024 (see my example below)

![image](https://github.com/modrinth/theseus/assets/10837000/4b514713-d9d3-43e7-9d1a-949dbd7da720)

You might need to allow your computer to allow more memory to the system/JRE.

Which modpacks in particular are you haivng trouble with? I can try on mine
