### ISSUE TITLE
When trying to relog in with my Microsoft account I get a error.

### ISSUE THREAD

**Issue by MIfoodie** [modrinth/code#573]
### Describe the bug

When trying to relog in with My Microsoft account even though I log in yesterday, I get this error.

Minecraft authentication Hydra error: In Bearer token flow: Response didn't contain valid bearer token. body: { "path" : "/launcher/login" }

### Steps to reproduce

1. Click on your profile icon. 
2. Click "log in"
3. Attempt to log in.

### Expected behavior

I would be able to log in and play the game.

**Comment by Ryhon0** [comment]
Can reproduce

**Comment by Ryhon0** [comment]
Removing the account and relaunching the program and immediately logging in seems to work around this issue. It might take multiple launches

**Comment by NONPLAYT** [comment]
same issue

**Comment by zhotheone** [comment]
for everyone who is expecting this problem, try to reboot your system and try again, worked for me (win10 22H2)

**Comment by NONPLAYT** [comment]
> for everyone who is expecting this problem, try to reboot your system and try again, worked for me (win10 22H2)

Yes, I did that too - it worked. but restarting the system every time this error pops up is nonsense. better fix

**Comment by asanull** [comment]
one OS reboot and roughly 5 relaunches fixed it in my case, very strange bug.

**Comment by pargivaht** [comment]
i had to login with my modrinth acc for it to fix, very strange. also i tried restarting too and relaunching a lot, maybe that did something too idk

**Comment by TheAlan404** [comment]
duplicate of #517

**Comment by NONPLAYT** [comment]
fixed in new release

**Comment by MIfoodie** [comment]
Fixed!
