### ISSUE TITLE
New error when trying to log in with Minecraft account.

### ISSUE THREAD

**Issue by tye-exe** [modrinth/code#590]
### Describe the bug

It is the same bug as within [this](https://github.com/modrinth/theseus/issues/293) report, however there is a different error message.
[Linked here.](https://github.com/modrinth/theseus/assets/131195812/b5e3b06f-541c-4c54-950f-428ce0285c71)

### Steps to reproduce

Try to log on.

### Expected behavior

Should be able to log on successfully.

**Comment by StormDragon-64** [comment]
I get a very similar error that wasn't occurring until today. Before this it said there was an error with my account, so I tried removing the account and re-adding it, which then caused this error. The error still occurs after restarting the app.
![image](https://github.com/modrinth/theseus/assets/80718549/f18fc34c-d845-4344-bd88-d7d27daa80fb)

**Comment by Mapty231** [comment]
This bug was fixed as of update 0.5.1
