### ISSUE TITLE
Exporting modpacks on Windows makes paths use backslash

### ISSUE THREAD

**Issue by ugudango** [modrinth/code#595]
### Describe the bug

When importing a .mrpack that was exported on Windows, Modrinth downloads the files by following the DOS-style convention. On Windows that means that there is no issue. On Linux/UNIX systems, however, it means that the files will be copied as-is to the root of the folder, being named like this:

```
mods\mymod1.jar
mods\mymod2.jar
```

This can be solved with a multi-file rename, though.

I'm not sure if this is an issue with the .mrpack format. Maybe a single path naming convention would be better? (followed by formatting paths by OS individually)

I'm not familiar with the codebase, but given some directions (i.e. which functions to look at) I could provide a PR, since this seems simple enough.

### Steps to reproduce

1. Export a .mrpack on Windows
2. Import a .mrpack on Linux

### Expected behavior

The mods should be downloaded in the `/mods/*` folder.

### Additional context

Actual behavior:

The mods are downloaded in the root folder, named as `mods\{modname}.jar`.

**Comment by QarthO** [comment]
Confirmed this is also an issue when installing modpacks on MacOS, not just linux.
