### ISSUE TITLE
Add Button in Settings to import instances from other Launchers

### ISSUE THREAD

**Issue by EvilsSouls** [modrinth/code#619]
### Is your suggested enhancement related to a problem? Please describe.

There already exists an importing tool, to import instances from other Launchers to Modrinth. However, if you, like me, just set the Modrinth App up, but didn't want to use it just yet, then you wouldn't be able to access the menu again to import your instances from other launchers.

### Describe the solution you'd like

The obvious solution would be to have a button in the settings to bring back the menu, so that you can import your instances as much as to your heart's content.

**Comment by Geometrically** [comment]
you can do this when you create a new instance already.

**Comment by Felix14-v2** [comment]
But you can't do this from the official launcher...

**Comment by Geometrically** [comment]
this issue isn't about importing from the official MC launcher

**Comment by wicivo** [comment]
But still, it can't be done
