### ISSUE TITLE
Search Filter for version support ignores launcher filter

### ISSUE THREAD

**Issue by Carrotoplian** [modrinth/code#634]
### Describe the bug

When searching with a version and launcher selected, it will show mods, datapacks, or whatever that don't support the launcher selected in the selected version but do in some other versions.

### Steps to reproduce

1. Open search
2. Select any modloader
3. Select any version(s)
4. search and look for a mod/something that doesn't support your modloader in the version you selected.

If you want an example here's a example I found
Search with filters for Forge, 1.16.5, Optimization in modpacks
You will see the modpack "Extreme Optimization" and if you check it doesn't have support for 1.16.5 in forge

### Expected behavior

To show only modpacks/mods/whatever that support the modloader in the version you selected and not in general.

**Comment by triphora** [comment]
This has been fixed with the [Creator Update](https://blog.modrinth.com/p/creator-update).
