### ISSUE TITLE
Instance not showing if mod is for different loader or version 

### ISSUE THREAD

**Issue by LuuppiChan** [modrinth/code#644]
### Describe the bug

I have an instance for Quilt 1.20.1 and want to add a mod that is for 1.20 Fabric. When I click install the Quilt instance does not show up on the list.

### Steps to reproduce

1. Create an instance for Quilt 1.20.1
2. Find a mod that is not for Quilt 1.20.1 (I used Chat-Transform)
3. Click install.

### Expected behavior

The instance you created shouldn't show up on the list

### Additional context

For an experiment I created 4 instances. One for Quilt 1.20.1 and 1.20 and one for Fabric 1.20.1 and 1.20.
After this I pressed install again on the specific mod (In this experiment I used Chat-Transform). Only the instance for Fabric 1.20 showed up.

Here is an image where it does not show the instances for Fabric 1.20.1 or Quilt 1.20 or 1.20.1
![image_2023-08-20_184829888](https://github.com/modrinth/theseus/assets/92115554/aa22d177-9353-4dbe-a56c-188463971c04)

**Comment by triphora** [comment]
This is not a bug. Fabric mods are not all guaranteed to work on Quilt.
