### ISSUE TITLE
Skipping every login step results in blank screen.

### ISSUE THREAD

**Issue by qtchaos** [modrinth/code#654]
### Describe the bug

If you skip both the Minecraft login and Modrinth login screen on the initialization of the Modrinth App, it results in the following screen.

![image](https://github.com/modrinth/theseus/assets/72168435/20e2caa5-2a71-4178-a04d-e8e88fd1312c)

### Steps to reproduce

1. Click next on the Minecraft login
2. Click next on the Modrinth login

### Expected behavior

Should either not be able to skip Modrinth login or not show the blank screen.

**Comment by thesuzerain** [comment]
Cant reproduce this- it seems to be an error in showing your import screen for some reason.
If you open up the web console is there an error? (cmd+shift+i, or right click -> inspect -> console)

Alternatively can you post the relevant log in your config folder /modrinth_logs/ - might be an error there. Thanks!
