### ISSUE TITLE
enhancements: my first impressions

### ISSUE THREAD

**Issue by Vosjedev** [modrinth/code#657]
### Is your suggested enhancement related to a problem? Please describe.

I know this is a new app, and I know there are still things being added.

Here is a list of enchancements I would like/I am missing:
- an option to move window buttons (min,max,close) to the left, or hiding them (little bit anoying having them on the right if all other window buttons are on the left)
- seperate resource packs from mod from shaders in the instance page (because they are not the same thing)
- showing mods versions on the mod page in the browse tab, like on the site
- return to scroll position when browsing mods/modpacks/anything (at the moment it just resets to the top)

### Describe the solution you'd like

see list

### Additional context

os: linux

Thanks for looking into this, and I hope this will become the best launcher there is for modded players (and hopefully for non-modded players too ; ) )

**Comment by triphora** [comment]
Please create separate issues for separate suggestions

**Comment by triphora** [comment]
Closing per above.
