### ISSUE TITLE
Neoforge install doesn't work

### ISSUE THREAD

**Issue by WrennWhitlock** [modrinth/code#661]
### Describe the bug

![Screenshot 2023-08-22 213247](https://github.com/modrinth/theseus/assets/65571427/1ecdb02b-cb2d-443b-bafd-a4efd2dc357a)

invalid args `` `modloader` `` for command `` `profile_create` ``: unknown variant `` `neoforge` ``, expected one of  `` `vanilla` ``, `` `forge` ``, `` `fabric` ``, `` `quilt` ``

### Steps to reproduce

Add an instance with neoforge modloader.

### Expected behavior

Install Neoforge

**Comment by StormDragon-64** [comment]
While NeoForge is an option, the 'select versions' field has no options, so the launcher can't install NeoForge. I'm not sure why you can't choose any versions, but the NeoForge maven isn't down or anything so it should still be able to get access to the different NeoForge versions.

**Comment by thesuzerain** [comment]
I think this should be fixed as of the latest version- can you please reopen if it is not?
