### ISSUE TITLE
Unable to use vanilla Structure blocks

### ISSUE THREAD

**Issue by falseresync** [modrinth/code#682]
### Describe the bug

Unable to use vanilla Structure blocks: the structure files don't save, there's no error in the log, only a chat message. This affects both modded and vanilla instances

### Steps to reproduce

1. Create any instance
2. Use a structure block
3. See "Unable to save ..." message
4. See neither structure file, nor any log error

### Expected behavior

Able to to use vanilla Structure blocks:

**Comment by draklorx** [comment]
I just ran into this trying to save a structure. It appears that the folder is read only.

![image](https://github.com/modrinth/theseus/assets/13177686/a197a724-3363-42de-b2c4-03ae019843d1)

Unchecking read-only and clicking apply does not correct the issue. Nor does manually creating the generated or generated/minecraft folders and setting them to not be read only. After you open folder properties again, it's once again set to read only.

**Comment by jevexendo** [comment]
Are there any plans to address this issue? While I appreciate that there appears to be a relatively simple workaround, this is a rather confusing problem when you encounter it for the first time and it took me a while before I figured out that this was a launcher issue and not something I'd done wrong.

Based on the listed workaround, it sounds like changing the default install path to use `.modrinth` instead of `com.modrinth.theseus` would be enough to solve the issue going forward. With that said, I can understand if that might cause complications I'm unaware of, but either way an update on the status of this issue would be appreciated.

**Comment by Warhand** [comment]
I agree, I ran into this issue myself and likely would not have realized this was the issue without googling it. This is a relatively simple fix for a user with some technical experience but is likely to be completely impossible to fix for a casual user.

**Comment by kalethemonster** [comment]
i tried the fix above, but when trying to set modrinth's path to use .modrinth in the launcher itself, it kept reverting the change instantly.

**Comment by J0B10** [comment]
> Until there is a more intended solution, here is how to fix it:
> 
>     * Close Minecraft and Modrinth
> 
>     * Navigate to `%AppData%` in File Explorer
> 
>     * Backup Modrinth's app directory `com.modrinth.theseus`
> 
>     * Rename `com.modrinth.theseus` to `.modrinth`
> 
>     * Open Modrinth and skip the welcome screen and tutorial
> 
>     * Open Modrinth's settings and change to app directory to `%AppData%/.modrinth`
> 
>     * Launch your Minecraft instance again and click save in any structure block

For me this temporary solution by @Yetenol no longer worked. It seems like the current release of modrinth ([`v0.7.1`](https://github.com/modrinth/code/tree/v0.7.1)) is no longer able to relocate the app directory to a different directory inside`%appdata%`.

What did the trick for me is moving the app directory to **another drive**. I changed the path to `D:\ModrinthData`, and the launcher automatically copied over all files. Now exporting structures is again possible. 
If you don't have another builtin drive, using an usb stick could also do the trick.
