### ISSUE TITLE
NeoForge support looks to be not supported by the backend

### ISSUE THREAD

**Issue by MichaelHillcox** [modrinth/code#695]
### Describe the bug

Please see below 

![](https://c.mikey.pro/scr/gEMTDeQi.png)

![](https://c.mikey.pro/scr/v88hzPUB.png)

### Steps to reproduce

- Create instance
- Select NeoForge
- Advanced 
- Use Latest
- Create
- Get error shown above

### Expected behavior

Instance should have been created properly with the latest NeoForge version

### Additional context

Pretty sure this is the latest version, I could be wrong. 

`0.5.3` `(20230819.015534)`

**Comment by StormDragon-64** [comment]
This error has been apparently been fixed, but you still can't use neoforge because of #702
