### ISSUE TITLE
`modrinth_logs` have no reason to exist (and are uncompressed)

### ISSUE THREAD

**Issue by falseresync** [modrinth/code#698]
### Describe the bug

There has been a complaint in Discord that `modrinth_logs` take up a huge amount of space, because they're neither compressed, nor deleted (31gb vs 600mb of actual logs). Given that the stdout capture in Modrinth is not the greatest (see, for example, the [LWJGL] spam), is there even a reason for this folder an log duplication to exist?

### Expected behavior

Either:
- no log duplication at all
- `modrinth_logs` are deleted after each run

**Comment by thesuzerain** [comment]
No- we are removing them with the next patch
