### ISSUE TITLE
Add support for arm64 architecture for Minecraft instances using LWJGL < 3.3.0

### ISSUE THREAD

**Issue by vaporior** [modrinth/code#700]
### Is your suggested enhancement related to a problem? Please describe.

Trying to run a Minecraft instance that uses a version of LWJGL < 3.3.0 natively on Apple Silicon architecture (M1, M2, e.t.c..) is a big pain because those versions do not support arm64 architecture. Possibly also affects Microsoft Surface users, but I have not verified this.

### Describe the solution you'd like

For the most part, trying to force those instances to use LWJGL >= 3.3.0 seems to work fine (as in, the versions are _mostly_ backwards compatible), except for a few bugs, namely this one: [https://github.com/LWJGL/lwjgl3/issues/695](https://github.com/LWJGL/lwjgl3/issues/695)
Luckily, somebody has already patched LWJGL to fix this: [https://github.com/MinecraftMachina/lwjgl3](https://github.com/MinecraftMachina/lwjgl3)
This patch is already in PrismLauncher. It would be nice if the Modrinth App can also use this as the LWJGL replacement when it detects the user is trying to launch instances that use LWJGL < 3.3.0 on an arm64 device.

### Describe alternatives you've considered

I have attempted to compile LWJGL < 3.3.0 on my M1 machine, but it seems that on those versions the buildscript doesn't have an option to compile natives for arm64, only x64 and x86 architecture.

Running the instance on Rosetta is also not really an option for heavy modpacks as the performance hit would most likely make it unplayable.

Currently, I have a [python script](https://github.com/vaporior/mmachina-lwjgl-downloader) that downloads MinecraftMachina's patched LWJGL and exctracts its natives. Then I have to manually replace the LWJGL < 3.3.0 JARs in modrinth's libraries directory with the downloaded ones, and make sure they are the same name as the original to "mask" them as if they are the 3.2 JARs when they are in fact a patched 3.3 JAR. Then I also have to copy the natives over to modrinth's natives directory.

I plan on modifying my python script so that it can be used as prelaunch hook and skip having to manually replace the JARs, but it is hacky and will require those users to install python and add it to path. Would be much nicer if this was just baked into the launcher automatically!

**Comment by Geometrically** [comment]
it works fine for me. we patch these minecraft versions with newer versions of lwjgl. what's not working for you?

**Comment by vaporior** [comment]
> it works fine for me. we patch these minecraft versions with newer versions of lwjgl. what's not working for you?

To reproduce my problem exactly, make a new PrismLauncher profile with the Create: Above and Beyond forge modpack then import it into modrinth.

Perhaps because it's imported from Prism it directs it to the old LWJGL, hence these errors?

**Comment by vaporior** [comment]
As of the newest version of the launcher, my previous setup with manually replacing lwjgl broke and now the launcher seems to be able to launch the game without any intervention from me :)

Not entirely sure if I can close issues myself but just wanted to update.
