### ISSUE TITLE
.mrpack Incorrectly imports

### ISSUE THREAD

**Issue by 1MiloAC** [modrinth/code#701]
### Describe the bug

On MacOS importing a .mrpack file will incorrectly import the mods into the root directory of the pack and not the mods folder I have tried on a fresh install and have the same issue.

### Steps to reproduce

1. Select add instance
2. Select from file
3. Import a .mrpack that has been exported with just mods.
4. The pack will reach about 70% before instantly completing (referencing an internal error)
5. The pack will have incorrectly imported just a few mods, and in the file system of the instance there will be all of the mods in the root and not the mods folder
(This is on Sonoma)

### Expected behavior

Mods unpack correctly to the "Mods" folder

### Additional context

This is on the MacOS Sonoma beta but this issue should not happen regardless.

This also didnt happen originally, but on my 3rd or 4th install of a .mrpack

**Comment by thesuzerain** [comment]
That's very strange. What .mrpack are you uploading? Is it a custom one? Can you send me it or the details on it so I can replicate it please?

In addition, do you know what the error that popped up was? It should be logged to the launcher_logs folder within com.modrinth.theseus, if you send me the relevant log file there I can try and debug it. 

Thanks!

**Comment by MiloAC1** [comment]
@thesuzerain 

It is a custom pack, I cannot make sense of the logs, but I have attached the pack and logs below in a .zip!
[Archive.zip](https://github.com/modrinth/theseus/files/12491079/Archive.zip)

**Comment by MiloAC1** [comment]
After you import it the mods and shaders will just be dumped to the root of the modpack instance folder, instead of in their respective folders.

**Comment by thesuzerain** [comment]
Got it thanks! This is perfect. This is actually an unexpected outcome of a separate bug that will be fixed in the next update. :)

**Comment by MiloAC1** [comment]
Awesome thanks for the quick responses!!!!

**Comment by thesuzerain** [comment]
It was this one!
https://github.com/modrinth/theseus/issues/595
