### ISSUE TITLE
theseus won't boot no matter what

### ISSUE THREAD

**Issue by EmeraldTheBunny** [modrinth/code#709]
### Describe the bug

I try to start the app, and it just doesnt open no matter what.

The logs just say:
2023-09-02T05:27:08.136808300+02:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!

Then nothing more...

### Steps to reproduce

1. Open the app

### Expected behavior

Expected behavior: App opens

Actual behavior: App doesnt open

### Additional context
I am on
Windows 10 pro (Kirby OS)

**Comment by thesuzerain** [comment]
Does *anything* open? Like, does a loading screen appear that it hangs on? Or does nothing open at all?

**Comment by EmeraldTheBunny** [comment]
It just doesnt open at all!. but i found the problem already:
I dont have the edge WebView2 thingy installed, the problem is that i cant install it, so its just a problem on my part
