### ISSUE TITLE
Theseus does not properly download mod add-on files

### ISSUE THREAD

**Issue by BrandonItaly** [modrinth/code#712]
### Describe the bug

When trying to install a mod with add-on support, downloading any of the listed files only installs the primary file and causes all of the additional files to appear as installed. Only the primary file is actually installed.

### Steps to reproduce

1. Go to any mod with add-on files, like [Raised](https://modrinth.com/mod/raised/version/l1xjmRyA)
2. Try to install any of the add-ons
3. All of the files show as installed
4. Only the primary file is actually installed

### Expected behavior

The files should be able to be installed individually, instead of just the primary file.

### Additional context

This issue also occurs when importing a modpack that includes any add-on files. Only the primary file is installed.

**Comment by Prospector** [comment]
That project is misusing additional files, addons should be separate projects. Working as intended
