### ISSUE TITLE
Button to Clone Profile

### ISSUE THREAD

**Issue by JaegyuDev** [modrinth/code#718]
### Is your suggested enhancement related to a problem? Please describe.

Having to open the profiles folder and copy/paste contents to clone a profile can be tedious.

### Describe the solution you'd like

Having the option to clone the profile in right click menu in the Library page would be helpful.

### Describe alternatives you've considered

You could also have an option to do it within the Profile page, and within its settings, but both would feel more hidden.

**Comment by Poopooracoocoo** [comment]
#229

**Comment by thesuzerain** [comment]
Duplicate of #229
