### ISSUE TITLE
Install mods direct from website

### ISSUE THREAD

**Issue by ghost** [modrinth/code#753]
### Is your suggested enhancement related to a problem? Please describe.

The CurseForge app has this very good idea of installing mods from the website, directly onto the app. This would be helpful for installing unlisted projects, or projects that are accessed through link sharing (i.e. your friend sent you a modrinth link on discord or something), or projects that didn't pass moderation but developers still want to share big projects that are hosted on the website.

### Describe the solution you'd like

In my mind, it would work off of the brand new authentication that Modrinth now uses. When signed into both the app and the website, you could click a button on a project page on the website that might say something like "Install on the App". It would then fetch the instances from the app, and allow you to choose which one to install the project to, directly from the website. This would allow for some remote working from say, your phone, or when you're on a device that doesn't have Minecraft on it.

### Describe alternatives you've considered

Using a more CurseForge like approach, and just launching the app if detected. This would be hard to implement in my opinion.

**Comment by Jan-DT** [comment]
Adding to this, when you want to send the link of a private (url-only) modpack to friends, they can't really open the URL directly in the Modrinth app, and they can't really search for it as it is hidden from search. This means they can't really add the modpack directly to the launcher, and need to download the mrpack file instead. Adding some 'open in app' or 'install with app' button would make this way easier.

**Comment by brawaru** [comment]
A little trick for installing unlisted modpacks: you can open developer tools using `F12` or `Ctrl`+`⇧ Shift`+`I` and then type the following in the **Console** tab:
```js
app.__vue_app__.config.globalProperties.$router.push('/project/PROJECT_ID_OR_SLUG')
```

Replace `PROJECT_ID_OR_SLUG` with project ID or slug (URL alias; e.g., for `https://modrinth.com/mod/sodium` it's `sodium`).

This should navigate you to this project's page and allow you to install the modpack. The modpack will be linked and updatable.

Unfortunately, this doesn't work for private and unpublished accounts, even if you somehow manage to sign in to your Modrinth account.

**Comment by Minenash** [comment]
Added!
