### ISSUE TITLE
My Minecraft Account constantly gets disconnected

### ISSUE THREAD

**Issue by TheStormcrafter** [modrinth/code#781]
OS: Windows 11
Theseus-Version: newest (2023-09-27)

The Launcher constantly says: Error with <something with hydra> and I need to reconnect my Minecraft/Microsoft account.

**Comment by Minenash** [comment]
Does this still happen?

**Comment by Felix14-v2** [comment]
I can confirm that the offline mode is now working properly: api.mojang.com, `api.minecraftservices.com`, `launcher.mojang.com` and `launchermeta.mojang.com` are often unreachable in my region without VPN/Proxy, but I'm still able to launch Minecraft and play offline.
