### ISSUE TITLE
Sort by which mods have updates available by default.

### ISSUE THREAD

**Issue by CelestialAbyss** [modrinth/code#782]
### Is your suggested enhancement related to a problem? Please describe.

Apologies if this is a duplicate, but I have not seen any issues similar to this request.

Currently I have to go through multiple pages just to check which mods have updates available, and this is not exactly a great user or modpack developer experience...

It only makes sense if this behavior is implemented by default. ***Other*** launchers have this as a **basic** functionality, so why has the Modrinth app lacked it ever since launch? It just does not make sense.

### Describe the solution you'd like

Mods that have updates available **should** show up on either the *first page* or at the *top* of the mod list where they can be easily visible. 

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by evertn** [comment]
This. Probably one of the features Im missing the most tbh

**Comment by CelestialAbyss** [comment]
It is such a basic feature as well that other launchers have too. I don't even understand why it hasn't been added in early development either

**Comment by bangetto** [comment]
this needs to be added, especially with the paging system

**Comment by CelestialAbyss** [comment]
If I'm being honest, the Modrinth app paginated mod list should also have an option to be disabled as a whole and allow for an infinitely scrollable mod list like the other launchers. It is also a better way of displaying information rather than clicking then scrolling through *every* **single** page

**Comment by CelestialAbyss** [comment]
While it has now been implemented as a toggle switch, it still feels like an extra step along with having to go through multiple pages.

![Image](https://github.com/user-attachments/assets/6ad0d02d-e595-42ed-a886-0fa25a590674)
