### ISSUE TITLE
cant open any version under 1.12.2

### ISSUE THREAD

**Issue by Chimpkiller420** [modrinth/code#788]
### Describe the bug

trying to make a 1.12.2 modpack, opened it, it immedietly crashed, any fixes?

### Steps to reproduce

create an instance with any version under 1.13 and any mod loader,
try to run it.

### Expected behavior

it should run cleanly like normal

### System information

im using windows and the latest version (atleast when this is posted (10/4/23) )

### Additional context

and the weird part is there is absulotly no logs

**Comment by catdogmat** [comment]
What Java are you using, try Java 8.

**Comment by Chimpkiller420** [comment]
how

**Comment by Chimpkiller420** [comment]
NVM it works now thx!

**Comment by catdogmat** [comment]
> NVM it works now thx!

Awesome! Please close this issue now
