### ISSUE TITLE
Creating a instance starting or ending with spaces has errors

### ISSUE THREAD

**Issue by KallelGaNewk** [modrinth/code#808]
### Describe the bug

![2023 10 14_21 23 18 534_Modrinth_App](https://github.com/modrinth/theseus/assets/61438367/a88158a3-7bf0-48ae-8544-58a0022d363d)

### Steps to reproduce

1. Click on Browse
2. Click on Install on any project that is not a modpack
3. Create a new instance by placing a space at the beginning or end

### Expected behavior

Create an instance without the space

### System information

Windows 11 22H2, Theseus 0.5.4

**Comment by qtchaos** [comment]
Related: https://github.com/modrinth/theseus/issues/765

**Comment by triphora** [comment]
This now seems to be fixed.
