### ISSUE TITLE
Add support to non-modrinth .zip modpacks file.

### ISSUE THREAD

**Issue by Steame090** [modrinth/code#815]
### Is your suggested enhancement related to a problem? Please describe.

Add support to non-modrinth .zip modpacks file.

### Describe the solution you'd like

Add support to non-modrinth .zip modpacks file.

### Describe alternatives you've considered

Add support to non-modrinth .zip modpacks file.

### Additional context

Add support to non-modrinth .zip modpacks file.

**Comment by triphora** [comment]
Issue not properly filled out, closing as such
