### ISSUE TITLE
[Localization] Optimized experience for China

### ISSUE THREAD

**Issue by WhatDamon** [modrinth/code#820]
### Is your suggested enhancement related to a problem? Please describe.

1. Too slow when downloading Minecraft (**Mojang source** is generally slow in China)
2. Doesn't support third-party game launchers that are commonly used in China (the five presets that come with it are **rarely** used in China)

### Describe the solution you'd like

1. Provide a mirror source service to speed up game downloads in China (and other regions where Mojang servers cannot be connected without problems)
2. Support for more game launcher profiles

### Describe alternatives you've considered

1. _Download sources problems_: add BMCLAPI[^1], MCBBS[^2] and other mirror download sources (non-Chinese regions can also add appropriate mirror download sources)
2. _More launchers support_: The third-party Minecraft launchers commonly used by Chinese players are [**HMCL**](https://github.com/huanghongxun/HMCL) (Hello Minecraft ! Launcher), [**PCL**](https://github.com/Hex-Dragon/PCL2) (Plain Craft Launcher), [**BakaXL**](https://www.bakaxl.com/)[^3]

[^1]: API Documents: https://bmclapidoc.bangbang93.com/
[^2]: Mentioned in the BMCLAPI documentation
[^3]: This launcher is not open source

**Comment by Minenash** [comment]
I'm a bit confused on how a launcher supports other launchers?

**Comment by WhatDamon** [comment]
> I'm a bit confused on how a launcher supports other launchers?

This Issue has been inactive for too long and I'm a bit unclear on what the purpose was at the time, I've decided to Close it for now and if I can refreshen up the purpose I may create a new Issue again, thanks!

**Comment by Felix14-v2** [comment]
You shouldn't close issues for inactivity in my opinion. Players from other countries may also benefit from adding mirrors, China is not the only country with global firewall.
