### ISSUE TITLE
Make intro skippable and quieter

### ISSUE THREAD

**Issue by brawaru** [modrinth/code#841]
### Is your suggested enhancement related to a problem? Please describe.

Currently, when you launch Modrinth app with no previous profile (it's either your first launch or you deleted app's data directory), it plays a 6-7 seconds video that contains sounds that can be loud or disturb sensitive hearing. The intro screen lacks any options to skip the video playback.

This is obviously bad, because it's unexpected and disturbing, or just plain time wasting for people that have already used Modrinth app in the past, and had to reset it due to some corruption bug.

### Describe the solution you'd like

There must be an option to skip the intro with both the keyboard shortcut (Esc) and on-screen button (that also should display the shortcut). The hint button should appear at least a second before the intro starts playing, preferably with some effect, either a ripple or fade in, to draw user's attention.

![Concept image featuring a button on top of the playing intro that says ‘[Esc] Skip’](https://github.com/modrinth/theseus/assets/10401817/53a8d923-9400-405d-b88c-5649542f3d8b)

The intro itself should also be quieter and avoid ‘sharp’ sounds like at 0:04 when Modrinth logo appears, as these are disturbing people to people with sensitive hearing.

### Describe alternatives you've considered

- Intro removal or replacement with something simpler. Current intro looks somewhat imposed and unprofessional for a modern age app. Modern apps usually prefer a simpler silent loading animation (see Discord, CurseForge, Gmail), no animation at all (see Twit- X, any Windows UWP app), or placeholders with optional shimmer (see Firefox, Spotify).

### Additional context

N/A

**Comment by khui0** [comment]
I agree it looks unprofessional. I feel like removing it completely would be the best option.

**Comment by Geometrically** [comment]
Removed a while ago
