### ISSUE TITLE
more categories

### ISSUE THREAD

**Issue by ghost** [modrinth/code#854]
### Is your suggested enhancement related to a problem? Please describe.

I'm always frustrated when i am trying to find an animal mod and thers no category of that (the mob category contins both monsters and animals and i want just animals)and i need to go to youtube and search a lot of top mods video and i can't find that specific mod type that i want

### Describe the solution you'd like

more specific category and more categories like in storage:portable storage, local storage. and add a quest category in the mods categories. and add a Description for each one of the new and exiting categories

**Comment by Minenash** [comment]
(ik it's been a year)
New categories can be suggested [here](https://github.com/orgs/modrinth/discussions/105)
