### ISSUE TITLE
Custom Instances Deleted

### ISSUE THREAD

**Issue by CrypticVerse** [modrinth/code#860]
### Describe the bug

One day I went into Thesus, and all of my custom profiles were deleted. When I checked the AppData/Roaming/com.modrinth.thesus/profiles folder, the instances were still there, but the profiles were gone. 

### Expected behavior

Custom Profiles will show up.

### System information

Windows 10, version 22H2
Thesus Version 0.6.0

**Comment by triphora** [comment]
https://docs.modrinth.com/faq/app#power-outage will tell you how to fix this.

**Comment by MCAlexisYT** [comment]
> https://docs.modrinth.com/faq/app#power-outage will tell you how to fix this.

That link is outdated.

**Comment by triphora** [comment]
Sorry, the pages were reorganized. https://docs.modrinth.com/faq/app/power-outage is the new link.
