### ISSUE TITLE
Error upon launching on Ubuntu

### ISSUE THREAD

**Issue by omgaXD** [modrinth/code#867]
### Describe the bug

When calling `modrinth-app` from terminal window, I get the following error:
```
modrinth-app: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
When launching app without terminal (for example, through .desktop file), nothing happens (as expected given the error)

### Steps to reproduce

1. Install the .deb package from Modrinth website
2. On plain ubuntu 22.04, open terminal and type "modrinth-app" to attempt to launch it

### Expected behavior

The app is supposed to launch

### System information

OS: Ubuntu 22.04
I have OpenSSL 3.0.2 installed.

### Additional context

I believe downgrading OpenSSL might solve the issue on my end, however I'm not sure about how safe is that to my system as I lack some Ubuntu knowledge.

**Comment by qtchaos** [comment]
Related: https://github.com/modrinth/theseus/issues/239

**Comment by omgaXD** [comment]
Installing newest `libssl1.1_1.1.1f-1ubuntu2.XX_amd64.deb` where XX is the biggest number (20 for me) from http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/?C=M;O=D does fix the issue. I'll not close this issue myself as I believe it can be fixed on app's end too, but it's solved for me personally.

**Comment by egut** [comment]
@omgaXD its not recommended to install older versions of libssl, it can install security issues and/or stability issues on you computer.
