### ISSUE TITLE
Allow filtering of followed projects

### ISSUE THREAD

**Issue by DarkkRevenant** [modrinth/code#873]
### Is your suggested enhancement related to a problem? Please describe.

Yes, when going to the "Following" section it just displays all filtered projects. 

### Describe the solution you'd like

Add the same filtering system like being used for regular searching of projects, except in the follow projects tab. This would also allow creators to see what mods they follow have been updated to newer versions. Also including a way to filter between Mods, Data Packs, Resource Packs, etc. would be very convenient.

### Describe alternatives you've considered

N/A

### Additional context

Take the photo with the blue star, implement that into the "Following" section with the blue line in the area circled in red.

![Screenshot 2023-11-11 154118](https://github.com/modrinth/theseus/assets/92821216/2d4dd073-5bf3-4d81-9715-be365797e50d) 
![Screenshot 2023-11-11 154044](https://github.com/modrinth/theseus/assets/92821216/7e13a780-fbf1-4b70-83dd-061b37402157)
![Screenshot 2023-11-11 154102](https://github.com/modrinth/theseus/assets/92821216/cefc18af-b530-40bb-b805-99cde09a17b4)

**Comment by Minenash** [comment]
Since "Followed Projects" is now a collection, closing this in favor of #1355
