### ISSUE TITLE
Validity check do not pass on arch linux

### ISSUE THREAD

**Issue by Nissyaniss** [modrinth/code#897]
### Describe the bug

When trying to update the modrinth app to 0.6.1-2 yay does not let me install it because the sha256sums does not validate

### Steps to reproduce

1. Try to install the modrinth app 0.6.1-2 using yay 
2. Fails

### Expected behavior

Install correctly the app

### System information

Operating System: EndeavourOS 
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.6.1-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8300H CPU @ 2.30GHz
Memory: 15,5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 630
Manufacturer: LENOVO
Product Name: 81FV
System Version: Lenovo Legion Y530-15ICH

**Comment by triphora** [comment]
The AUR packages are not official. We are unable to help with this issue.

That said, `modrinth-app-bin` is working for me. Still unofficial though.

**Comment by Nissyaniss** [comment]
Oh, I'm so sorry I didn't know that those where not officials.
But is there any plan to have AUR packages that are officials or no ?

**Comment by triphora** [comment]
Likely not, but we're hoping to have a Flatpak in the future.
