### ISSUE TITLE
Appimage does not include libary libthai

### ISSUE THREAD

**Issue by linked3** [modrinth/code#900]
### Describe the bug

The appimage does not work on nixos, for the appimage does not bundled with the necessary dependencies.

### Steps to reproduce

1. installing appimage-run
2. Get the officially provided appimgae for theseus: in my case modrinth-app_0.6.2_amd64.AppImage
3. Open it with some kind of tool that shows occuring errors (I used appimage-run)

### Expected behavior

The appimage should include all necessary libraries it needs to run.

### System information

Nixos on channel 23.05/ latest at this time of writing
modrinth-app_0.6.2_amd64.AppImage

### Additional context

when running the appimage nothing happens, but appimage-run gives this error:
modrinth-app: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory

**Comment by Norbiros** [comment]
This is not problem with Theseus but with Appimage. Original issue https://github.com/AppImageCommunity/pkg2appimage/issues/538 and issue about the same problem in Tauri https://github.com/tauri-apps/tauri/issues/4930

I had the same problem on Gentoo, but I installed libthai manually and everything works.
