### ISSUE TITLE
Have settings.json follow the app directory path

### ISSUE THREAD

**Issue by Josh65-2201** [modrinth/code#903]
### Is your suggested enhancement related to a problem? Please describe.

Right now launcher settings are still in the appdata folder even when setting a custom location

### Describe the solution you'd like

The settings.json file should be stored in the same location as the App directory location

**Comment by triphora** [comment]
How else would the launcher know that you've changed the location, though? That settings file tells the launcher where the rest of the files are...

**Comment by Josh65-2201** [comment]
What about splitting them? The fixed location for where the settings would be and the reset in the chosen location

**Comment by triphora** [comment]
There would be no point. That just needlessly adds complexity when the settings file takes up barely any space anyway. On my system, it takes up less than a kilobyte. Mainly the feature of changing the app directory is offered for those who want to move their multiple-gigabyte-large instances to another disk.
