### ISSUE TITLE
Inconsistent search results

### ISSUE THREAD

**Issue by SylisMC** [modrinth/code#916]
### Describe the bug

search results will sometimes show mods that have nothing to do with the search parameters like the name and description having no mention of what was searched. (Cant get screenshot of this because it fixed itself before I realized it was happening)

Sometimes searching for mods by exact name wont be found on the app. but will if you change the "Sort  By" tab to "downloads"
![Relevance](https://github.com/modrinth/theseus/assets/19602662/77569bf2-5a03-430c-92f9-5077f63ef788)
![Capture](https://github.com/modrinth/theseus/assets/19602662/f467c90a-5717-444a-8334-8904db15a793)

**Comment by triphora** [comment]
This seems to now be fixed.
