### ISSUE TITLE
Modcards not load if the Config Directory is changed

### ISSUE THREAD

**Issue by Rajala1404** [modrinth/code#927]
### Describe the bug

Not an single modcard is loading no matter what format
![image](https://github.com/modrinth/theseus/assets/115874847/e3977e25-6d62-4ff2-b443-b8c38024179a)
No matter what Version of the App i use (AppImage, AUR) it will not load
But the Images on the Preview load
![image](https://github.com/modrinth/theseus/assets/115874847/f5276dbc-e60a-4709-8ec6-b9c3eb7b4c6d)

### Steps to reproduce
1. Change the Config Directory
2. Create or Download an Modpack
3. Add an Image as Modcard (only if self created)
4. Go to library.
5. And the images wont load

### Expected behavior

Images load

### System information
OS: Arch Linux x86_64 
Kernel: 6.8.2-arch2-1 
Shell: bash 5.2.26 
Resolution: 2560x1440 
DE: Plasma 6.0.3 
WM: kwin 
WM Theme: Breeze 
Theme: [Plasma], Breeze-Dark [GTK2], Breeze [GTK3] 
Icons: kora [Plasma], kora [GTK2/3] 
CPU: Intel i5-7400T (4) @ 3.000GHz 
GPU: Intel HD Graphics 630 
GPU: NVIDIA GeForce GTX 950M 
Memory: 11692MiB + 8GB Swap

**Comment by SmilerRyan** [comment]
I have the same issue, in my situation it works if I launch and use the Modrinth App (or app directory setting) normally but if I start it with the `THESEUS_CONFIG_DIR` variable set it only shows the one icon in the options but not the main pack preview.

![image](https://github.com/modrinth/theseus/assets/14893385/7fdedd75-0c43-45c1-a527-199bae77e10c)
