### ISSUE TITLE
When too many instances(modpacks) can't see them.

### ISSUE THREAD

**Issue by CystasysAlt** [modrinth/code#946]
### Describe the bug

So like when you have slot modpacks the modrinth windows will show only like 6 until you make the window bigger and then you finally see the other ones.

### Steps to reproduce

1. Open modrinth:
2. Create alot of modpacks.
3. Can't see them all?
4. Make the modrinth window bigger!
5. You now see them! (But still the ones that fit in the row and window)
6. So that's basically the problem.

### Expected behavior

I expected for the other ones that don't fit go like make another row and go there but it doesn't.

### System information

Windows 10.. modrinth version : latest one. (18.12.2023)

**Comment by thesuzerain** [comment]
Thanks for the issue! Can you please attach a screenshot?

If you are just looking at the home page, we only show a snippet of the projects there. You might have to click on the library to see the full list.

**Comment by triphora** [comment]
No response in more than a month, assuming fixed by above
