### ISSUE TITLE
Login Button of screen

### ISSUE THREAD

**Issue by Nachtwind1** [modrinth/code#957]
### Describe the bug

The Login Button after you start the app for the first time is offscreen
![image](https://github.com/modrinth/theseus/assets/124518219/715a7a41-3fee-40d5-aa17-6cd0cfa9eab2)

### Steps to reproduce

1. idk if it has something to do with that, scale your screen smaller using NVIDIA Control Panel.
2. open the Modrinth app with no savedata of the app (so delete: C:\Users\ <your user>\AppData\com.modrinth.theseus)
3. Press the Getting started button
4. wait for the image to load
5. Suffer because you need to use curseforge

### System information

Windows 10, Nvidia Geforce Rtx 3050, AMD Ryzen 5 and 16 Gb of ram

**Comment by triphora** [comment]
You just need to increase the size of the window.

**Comment by Nachtwind1** [comment]
You Literally can't, it's already Maximized

Emma Alexia ***@***.***> schrieb am Sa., 27. Jan. 2024, 07:19:

**Comment by triphora** [comment]
What is your screen resolution?

**Comment by Nachtwind1** [comment]
It's Something around 1600*900, because i needed to rescale It else the
taskbar goes offscreen

Emma Alexia ***@***.***> schrieb am Sa., 27. Jan. 2024, 09:29:

**Comment by wlad26** [comment]
Even on 1366x768 screen you can see the button at 100% scale:
![oQTJAqL](https://github.com/modrinth/theseus/assets/65756919/e4f41d1e-db33-4b77-b2d4-ae38f6221ad3)

I've heard about problems with 1280x720 screens, but 1600x900 should be normal
Maybe you have more than 100% scale set in your system settings?

**Comment by io-tronic** [comment]
I would suggest you reconsider @triphora. My blind friend is unable to use this launcher as a result of this issue. Accommodating a range of text sizes is important to making something accessible to disabled people. A responsive design or even a scroll bar seems like a small accessibility change that would allow a lot more people to use your project. I'll try and make it myself, but I'm not the most skilled with this type of dev work :/


<img width="707" alt="image" src="https://github.com/modrinth/theseus/assets/37963057/484e9bb4-7397-4ffc-a135-446c2856b0f5">

**Comment by triphora** [comment]
@io-tronic I am no longer a Modrinth staff member and therefore cannot reopen this issue. Please open a new issue.
