### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by marbelredlysbold** [modrinth/code#958]
### Describe the bug

it is not a bug but a feature maybe can be added

### Steps to reproduce

idk what to write

### Expected behavior

here If you update Minecraft, it will automatically check all mods. If any mods do not support the update, it will ask if you want to keep them, but they will be displayed in red to indicate that they don't support the Minecraft version. If you lower the Minecraft version, it will check all mods again. Any mods that don't support the new version will be displayed in red or yellow when you hover over them. Hovering over a mod will show a message saying that it currently only supports the version of Minecraft you had before. For example, if you downgrade to Minecraft 1.16, it will show whether the mod supports 1.17 or another version. If you want a classic experience, it will automatically adjust all mods to the supported Minecraft version. If any other mods still work in the unsupported version, they will be shown in green. You can choose the color for mods that support both the Minecraft version and the mod. If this is too difficult to code, then perhaps there could be a feature like in CurseForge, where the system detects mods that do not support the current version. and also could add a option that can be edited that the mod publisher can use to show that it support any version like animation mod or that and there have to be proof or a link to where they show that it support every version or smt like that 

### System information

i don't have anymore info

### Additional context

i don't have anymore

**Comment by marbelredlysbold** [comment]
i forgot i use windows could maybe add it to all systems that modrinth supports

**Comment by Minenash** [comment]
This should have been written as a feature request instead of a bug report. Systems like this has also been suggested in other issues, closing as duplicate
