### ISSUE TITLE
Newer Forge 1.16 versions not listed

### ISSUE THREAD

**Issue by embeddedt** [modrinth/code#966]
### Describe the bug

Recently, I contributed two PRs to Forge for the 1.16 branch aimed at making sure it can still be built in 2023, and also updating it to support running on Java 21 (previously the latest supported Java was around Java 17). These versions (36.2.40 & 36.2.41) do not appear to be listed in Theseus.

### Steps to reproduce

1. Open the app.
2. Create a Forge 1.16.5 instance and select that you want the latest version, not the stable version.
3. Notice that it chooses 36.2.39 as the version.
4. Attempt to choose a version manually and notice that 36.2.40/41 aren't in the list, the newest you can have is 36.2.39.

### Expected behavior

These newer versions of Forge would also be in the list.

### System information

OS: Arch Linux
Theseus version: 0.6.3

### Additional context

Not sure if this is just a matter of the metadata needing to be updated manually for old versions, or if it's indicative of an actual issue.

**Comment by Smartin-b** [comment]
A similar issue now exists for Forge versions 1.20.1 47.2.18 and newer
The Latest listed in the Launcher is 47.2.17, but the latest on forges Website at the moment is 47.2.23.
