### ISSUE TITLE
Ctrl+A selects all text on a page

### ISSUE THREAD

**Issue by cootshk** [modrinth/code#975]
### Describe the bug

I'm trying to remove every instance at once.

I go to my Library of installed instances, and ctrl+A

![image](https://github.com/modrinth/theseus/assets/83678457/2dfe3cc7-af6b-4763-a4f4-6c9cd46a4f01)

### Steps to reproduce

Step one: go to library
Step two: Ctrl+A

### Expected behavior

Either A: select all packs
or B: Don't do anything

### System information

Windows 11, Theseus v0.6.3

### Additional context

If I open the settings menu, the text stays selected

**Comment by triphora** [comment]
This is not a bug.
