### ISSUE TITLE
Error when creating Forge 1.20.4 profile

### ISSUE THREAD

**Issue by BlakeMpy** [modrinth/code#980]
### Describe the bug

When creating a profile for 1.20.4 Forge, the app says it is downloading Minecraft. Near the end (at around 83%) it says "Error launching Minecraft: Processing error:..." in the bottom right in a red box.

### Steps to reproduce

1. Click on the green plus icon to begin the profile creation process.
2. Type in a name for the profile, select Forge, and select the 1.20.4 game version.
3. Click the create button, and let it download Minecraft until it nears 83%.
4. A red error message should appear in the bottom right.

### Expected behavior

The profile should be created normally without failing.

### System information

Windows, Theseus v0.6.3. AMD system.

### Additional context

I had previously attempted to switch an existing Fabric profile to Forge 1.20.4, but it appeared to get stuck, and there was no indication that it was downloading or installing anything with the exception of the greyed out "installing..." text. I let it run for five to ten minutes, then deleted the profile. I suspect that this may be the cause of the error, but am not certain, so I did not include this in the steps to reproduce.

The logs say
`ERROR init_watcher:sync_projects_task{profile_path_id=ProfilePathId("magicus") force=false}: theseus_gui::error: error=Error launching Minecraft: Processor error: Exception in thread "main" java.io.IOException: Patch expected com/mojang/blaze3d/pipeline/RenderTarget to not exist, but received 11055 'bytes'`
This is largely why I suspect it is because of the files installed by the process that I forcefully ended when switching from Fabric to Forge.

I would manually go through and delete the forge 1.20.4 files, but I cannot find a file path matching the one in the error in either the Roaming/com.modrinth.theseus path, or in the modrinth.exe path, or their subfolders. It is possible modrinth has other related paths, but if so, I do not know where they might be, as the settings say that "all of its files" are stored in the Roaming location (even though this is not, in fact, where the launcher executable files are stored? Somewhat misleading...)

**Comment by brawaru** [comment]
@Kokonico Forge 1.20.4 versions are not yet supported because Forge has changed their installer. To my knowledge the team is working on a fix already, but there is no ETA.

**Comment by Ash-49** [comment]
still active. Any work arounds?

**Comment by user29348** [comment]
This is the same problem im having. if i get a forge installation and just make a new profile.json file, will it work?

**Comment by DefomCode** [comment]
the problem is still relevant.

**Comment by Erb3** [comment]
> the problem is still relevant.

@DefomCode Are you on the App beta?

**Comment by brawaru** [comment]
This has been fixed in the upcoming update, which you can test already through one of the following links:

- [Windows](https://nightly.link/modrinth/code/actions/runs/10070959133/windows-latest.zip)
- [macOS](https://nightly.link/modrinth/code/actions/runs/10070959133/macos-latest.zip)
- [Ubuntu](https://nightly.link/modrinth/code/actions/runs/10070959133/ubuntu-20.04.zip)

We also have discussion channel for this update on our [Labs Discord server](https://discord.gg/3GQAKjQR6g).
