### ISSUE TITLE
Page counter module in app is broken if instance/search has 5, 6 or 7 pages

### ISSUE THREAD

**Issue by w26ad** [modrinth/code#988]
### Describe the bug

Page counter module in Modrinth app is broken if instance/search has 5, 6 or 7 pages

Page counter on website search with 4, 5, 6, 7 and 8 pages:
![Снимок экрана (770)](https://github.com/modrinth/theseus/assets/65756919/d91ec641-23a6-4905-bec2-d7798482fe82)
![Снимок экрана (771)](https://github.com/modrinth/theseus/assets/65756919/2d1220c8-dedc-46ea-b4d8-b4c4d0dde2c3)
![Снимок экрана (769)](https://github.com/modrinth/theseus/assets/65756919/8bb5e6af-8912-45b8-910c-f0e0395916ef)
![Снимок экрана (773)](https://github.com/modrinth/theseus/assets/65756919/7515a0af-27a7-4365-86b9-8c7f3b966b53)
![Снимок экрана (774)](https://github.com/modrinth/theseus/assets/65756919/16b06a57-46dd-4ee4-aacd-b0de878d2f6f)

Page counter in Modrinth app on instance/search with 4, 5, 6, 7 and 8 pages:
![Снимок экрана (777)](https://github.com/modrinth/theseus/assets/65756919/5b667261-329e-4d44-b438-4acd05f897da)
![Снимок экрана (778)](https://github.com/modrinth/theseus/assets/65756919/1f4f4d51-6ebe-4761-a502-0a5d0350f63e)
![Снимок экрана (779)](https://github.com/modrinth/theseus/assets/65756919/ad6d4d13-99b9-4b49-981c-b37a1803099a)
![Снимок экрана (780)](https://github.com/modrinth/theseus/assets/65756919/ceb09c9c-59d7-4c85-be04-fa874a082732)
![Снимок экрана (781)](https://github.com/modrinth/theseus/assets/65756919/63195148-d3b0-4ffe-a442-160fad7fdc0c)

When pages count is less than 5 or more than 7, both website and app works correctly.

### Steps to reproduce

1. Go to instance/search
2. If you're going to instance, add or remove enough projects to have 5, 6 or 7 pages
3. If you're going to search, set filters to have 5, 6 or 7 pages
4. You'll see broken page counter module.

### Expected behavior

Page counter module in Modrinth app works as same as on the website (correctly)

### System information

Windows 11 23H2 22635.2921
Theseus 0.6.3

**Comment by Minenash** [comment]
Seems to be fixed
