### ISSUE TITLE
Allow multiple app instances to be open at once

### ISSUE THREAD

**Issue by MulesGaming** [modrinth/code#995]
### Is your suggested enhancement related to a problem? Please describe.

This would allow you to view multiple modpack _mod_ tabs to be open at once. This is useful if you want to compare mods in do different mod packs.

### Describe the solution you'd like

I would like the ability to open the app in more than one window. Currently, if you open the app and then try to open it again, nothing will happen.

### Describe alternatives you've considered

A pop-out window for individual modpacks could also work.

**Comment by JosiahFu** [comment]
Agreed, also this would benefit from #972 being addressed

**Comment by JosiahFu** [comment]
I think popout windows for modpacks and also perhaps the search tab would be more performant and focused, the main GUI could stay on the main window only (Kind of like what the Slack desktop app does)
